### ISSUE TITLE
What should I do if I don't want Keras to display progress bar?

### ISSUE THREAD

**Issue by rajareddy1863** [fchollet/keras#1007]

**Comment by EderSantana** [comment]
verbose=0 in the fit method, default is 1

**Comment by rajareddy1863** [comment]
Thanks for your early answer

**Comment by vedhas** [comment]
Somewhat related: How can I remove colour formatting? I use 'slurm' to launch the jobs on GPU cluster, and I get following kind of logs = dumped stdout outputs. The ^H characters are annoying, when trying to read through the file, I suspect it is because of colouring?

`^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^M 975/2808 [=========>....................] - ETA: 91s - loss: 5.3113 - dense_1_loss: 1.4563^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M1040/2808 [==========>...................] - ETA: 88s - l^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M1105/2808 [==========>...................] - ETA: 84s - loss: 5.3184 - dense_1_loss: 1.4460 - dense_2_loss: 3.8725 - d^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^M1170/2808 [===========>..................] - ETA: 81s - loss: 5.3082 - dense_1_loss: 1.4394 - dense_2_loss: 3.8^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M1235/2808 [============>.................] - ETA: 78s - loss: 5.2941 - dense_1_loss: 1.4313 - dense_2_loss: 3.8629 - dense_1_a`

**Comment by shllgtca** [comment]
hi @EderSantana , I defined verbose =0.
but It's still displayed the msg showed in the image. 
It sounds that the frontend does not support the widget, but I thought that once the verbose =0 it would not have any attempt to display anything!
![captura de tela 2018-07-18 as 8 30 36 am](https://user-images.githubusercontent.com/41371818/42878914-1d1feb4e-8a65-11e8-95f5-8280ff5eee7a.png)

**Comment by binlbl** [comment]
What can I do to disable the progress bar in predict()?  e.g. 92%|█████████▏| 24/26 [00:22<00:00,  5.83it/s]
