### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#1022]
I know this is quite a recurrent issue, but I think it's still an important one. I'm sure everyone is busy with adding all the new features/backends/etc but it has come to the point where a lot of keras's functionality is undocumented and changing from one commit to the other. 

Digging through the (largely also uncommented) code and trying to infer what every new thing does and how every old thing changed is becoming cumbersome and utterly intractable. Half the merge mode are missing explanation even on the shape of the output. I do recommend not accepting any more pull requests that lack some form of explanation and maybe also updating the docs a bit from behind. 

The API is awesome, but I'm starting to not know what the features are any more or what's the right way to access them >.>

**Comment by fchollet** [comment]
You're right. What are some specific features that are currently undocumented? We could start there.

**Comment by Tomtomgo** [comment]
Not sure if this is the right issue, but I had a hard time figuring out what training data should look like, specifically for the simple examples (which except for this are great). Numpy arrays? Python lists? What shape is expected?

For example, in the [multilayer perceptron example](https://github.com/fchollet/keras#multilayer-perceptron-mlp) it would be useful to use way less input nodes, leaving room to define `X_train` and `y_train`. That would be a nice bottom-up starting point for further coding.

**Comment by lemuriandezapada** [comment]
- rmse and poisson losses are missing as objectives
- all merge modes but sum, mul and concat are missing (only sum and concat are present in graph modes)
- concat_axis, dot_axes, create_output are missing from the add_node graph model documentation
- layers such as LRN2D, Lambda, MaskedLambda are missing.
- input_length and go_backwards are undocumented for recurrent layers

There are more but I'll dig through them tomorrow

**Comment by dbonadiman** [comment]
There is not the go_backwards  documentation @lemuriandezapada? I added it there https://github.com/fchollet/keras/blob/master/docs/sources/layers/recurrent.md some days after the addition of the flag to the library.

Some newer layers have not documentation yet i know but we should focus together to add it, most of this library is currently evolving through pull request from people, from one side not fast enough and from the other too fast we are in a transitioning phase that will decide if this is going to be a real widely used deep learning library.

A thing is that we should have a development branch of the library that can be partially documented but we should have some checkpoints that must be up to date. The pip version of Keras should be correctly documented the other may be partially since is under development from my point of view. 

I don't know if the administrator @fchollet  plans to add some more strict versioning system in the future. Or rules regarding unitest and documentation for all the pull request to be accepted. 
There are many things that must be addressed in particular for user demanding more from the library but the people actively developing it are really few. @fchollet @EderSantana and @farizrahman4u  are really committing a lot to the library and i'm trying to do my best too (at the best of my knowledge and capabilities). If there are problems with something just point out, if you can solve the problem by yourself just pull request, for the rest maybe someone can take care of the issue. There are a lot of things to make this library better.

**Comment by lemuriandezapada** [comment]
Maybe I'm doing it wrong(?) but I keep referring to this page, and go backwards doesn't appear to be there:
http://keras.io/layers/recurrent/
Although after some looks in the .md files some stuff is still missing even there. 


I'd love to help out but my coding skills and understanding of theano are too low to patch it up myself. ^^
Pointing things out is what I'm doing now. To be fair, I'd personally be ok with slower development but easier to understand features. I would personally suggest some more hardcore requirements for documentation from pull requests.

**Comment by farizrahman4u** [comment]
@lemuriandezapada You  have to check the docs folder in the repository. www.keras.io is not up to date

**Comment by lemuriandezapada** [comment]
Yes, I see now some of them are there, but not all.
Merge modes and everything related to them and the graph models are missing.

**Comment by fchollet** [comment]
I updated the online documentation yesterday, which fixes some but not all of the issues mentioned.

**Comment by phreeza** [comment]
Random thought: we could probably rig up travis to push the docs to wherever you are hosting them, if master is updated and all tests pass.

**Comment by gnuchoi** [comment]
@phreeza I agree with you. If there's a structure that people can take part in I'm willing to help!

**Comment by ZHRbt** [comment]
I've also noticed that the LRN2D layer is missing documentation - it may be pretty straightforward, but its existence is not even mentioned.

**Comment by lemuriandezapada** [comment]
The neural turing machine is also undocumented

**Comment by lemuriandezapada** [comment]
'trainable' option is also undocumented

**Comment by EderSantana** [comment]
@lemuriandezapada I'll work on better documentation for NTM, right now, we have some notes here: https://github.com/fchollet/keras/wiki/Tutorials-and-lessons

**Comment by lemuriandezapada** [comment]
Cool ^^
siamese layer is also undocumented

**Comment by rpinsler** [comment]
In addition to documenting the API itself it would be beneficial to have a change log, especially since there are often breaking changes. 
I also think it would be good to separate the API documentation from a more use case centered tutorial. Use cases would be something like data pre-processing, model training, evaluation, model selection, performance optimization, visualization, model debugging or extensibility. This would also be a good place to explain the main concepts in terms of composability/modularity.

**Comment by MartinThoma** [comment]
You might be interested in

* [NumpyDoc](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)
* How Lasagne did their documentation, e.g.
  * [docs/objectives.rst](https://raw.githubusercontent.com/Lasagne/Lasagne/master/docs/modules/objectives.rst) and [the rendered result](http://lasagne.readthedocs.org/en/latest/modules/objectives.html)

**Comment by fchollet** [comment]
We have had autogenerated documentation for a few weeks now. Closing this issue.
