### ISSUE TITLE
How to implement Siamese network architecture using keras

### ISSUE THREAD

**Issue by cxfneo** [fchollet/keras#1045]
HI all 
   How to implement Siamese network architecture using keras,  could u give a sample code or  a hint ?
Thank u very much

**Comment by farizrahman4u** [comment]
Its still in progress.#928

**Comment by cxfneo** [comment]
Thank u . 
BTW, Dose the graph() in keras can solve the Siamese ?

**Comment by farizrahman4u** [comment]
After #928 is merged, yes

**Comment by kylemcdonald** [comment]
Closed by #928

**Comment by psxpa3** [comment]
Hi,

I saw the implementation of Siamese network as mentioned on this link:- https://github.com/NVIDIA/keras/blob/master/examples/mnist_siamese_graph.py. 

If I understand correctly then it is a network of three layers  where the last one is the output layer. Now, I want to extract feature vector learnt by an intermediate layer which I tried to do using this code snippet as mentioned in the Keras documentation:-  val = model.layers[1].output . This gave me the output as:- 
<tf.Tensor 'input_36:0' shape=(?, 850) dtype=float32> 

So, my questions/doubts are as follows:
1)How to get the feature vector from this tensorflow "val instance" as obtained above?
2)Since the Siamese network is nothing but the twin network where two networks share the weights so if I am extracting output of this intermediate layer will be referring to either of the layer at the same level in this twin network?
3)Now, the next step I want to do is to use this extracted feature vector and add some noise and do some manipulation with this so further this feature vector can be used as an input for classification. So, would I need to create another Siamese network (if in case I need to use Siamese network only for classification) with the existing model weights or  the existing Siamese model with this modified feature vector itself as an input?. Then in either of the case how can I do implementation. 

Any guidance/direction for this implementation would be really helpful for me.

Really sorry for such a long question, but I need to clarify these doubts. Looking forward to getting the answers.

Regards,
Priya Arora
