### ISSUE TITLE
How does keras handle the mask padding  if go_backward == 1?

### ISSUE THREAD

**Issue by ypxie** [fchollet/keras#1057]
I am not sure if I get it right. But it seems to me that keras always pads the mask on the left:

```
    if pad > 0:
        # left-pad in time with 0
        padding = alloc_zeros_matrix(pad, mask.shape[1], 1)
        mask = T.concatenate([padding, mask], axis=0)
    return mask.astype('int8')
```

But if go_backward ==1, it should pad the sequence on the right, right? or override the get_input function to return X[::-1].

Can anyone help explain what did I miss?
Thanks!
@fchollet  @EderSantana

**Comment by EderSantana** [comment]
Good question, @dbonadiman was that you who was working on `go_backward`? Could you check this out? Thank you!

**Comment by fchollet** [comment]
Should be easy to configure the padding side to change depending on `go_backwards`. Thanks for pointing this out. @dbonadiman, thoughts?

**Comment by dbonadiman** [comment]
We were talking about that for a while in other threads the mask have problems when applying the backward step or the patting is on the right side. I suggested the other person that pointed that out to write something into the new backend thread since i think that is possible to solve the problem on the  rnn API. what do you think @fchollet or @EderSantana. 
Otherwise as soon as i finish some work i can try figure out how to solve this problem on each layer.

**Comment by EderSantana** [comment]
I think that a better use of `mask` could smoothly solve that problem:

```python
h_t = self.activation( x_t + T.dot(h_tm1, u))
return mask * h_t + (1 - mask) * h_tm1
```

Note that with that proposed use of `mask`, we don't washout the states when the padding starts, we simply keep the previous value of the hidden state before the zero padding. This would work regardless of padding on the left or on the right. I like that solution because it will also be useful for the transferable/stateful states here https://github.com/fchollet/keras/pull/964 
What do you guys think?

**Comment by shampool** [comment]
＠EderSantana  seems like a good solution for stateful rnn, Would you mind explaining a little bit more about how it solve the padding problem? I think you still need to adjust the padding on left or right based on go_backward. right?

**Comment by EderSantana** [comment]
paddings are zeros, we care about the `mask` from the padded sequence. Inside the RNN, we reset the state every-time we see a mask=0. This is why we pad on the left, so we can safely zero the state out before the actual sequence begins. If we pad on the right, we lose information. With the solution above, we never reset the hidden state, we just use the previous valid one and pass it along. This way, it doesn't matter if you have pad on the left or on the right.

**Comment by shampool** [comment]
Thanks for your explanations.  @EderSantana 

I am not sure if I fully understand this.  But from the following code in class SimpleRNN(Recurrent), I think if the rnn is stateful, the outputs_info should be initilized with some meaniful 'values of someth rnn's hidden states' rather than 0. and in this case the mask should also be padded with 1 rather than 0.  What do you think?


        outputs, updates = theano.scan(
            self._step,  # this will be called with arguments (sequences[i], outputs[i-1], non_sequences[i])
            sequences=[x, dict(input=padded_mask, taps=[-1])],  # tensors to iterate over, inputs to _step
            # initialization of the output. Input to _step with default tap=-1.
            outputs_info=T.unbroadcast(alloc_zeros_matrix(X.shape[1], self.output_dim), 1),
            non_sequences=self.U,  # static inputs to _step
            truncate_gradient=self.truncate_gradient,
            go_backwards=self.go_backwards)
