### ISSUE TITLE
Bug report in RNN

### ISSUE THREAD

**Issue by jeffzhengye** [fchollet/keras#1233]
Around line 68 in recurrent.py
If we are using float32, line 68 will be a float32 times int32, which will produce a float64. (is it because of theano version?)
changing line 68 to X *= K.expand_dims(mask).astype(X.dtype) will fix this problem. 

        if mask:
            # apply mask
            X *= K.expand_dims(mask)   # line 68
            masking = True

**Comment by fchollet** [comment]
As far as I can tell RNNs work fine in float32 with Theano, so it must be a problem with your Theano version.

**Comment by jeffzhengye** [comment]
@fchollet the problem only occurs when reture_sequences=True.

**Comment by jeffzhengye** [comment]
@fchollet I am using the version  '0.7.0.dev-e521b20e578c033d51e548181bd1edd24af64427'

**Comment by jeffzhengye** [comment]
@fchollet It doesn't matter which version I use, I got the same error. 
(shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix))

I believe this is a bug of theano, which is not fixed yet. You can easily test this with ipython. 
a float32 times int32, which will produce a float64. 
So I think we have to fix this in the keras side.

**Comment by fchollet** [comment]
A simple cast to `_FLOATX` in the backend function should fix it. Would you like to submit a PR?

**Comment by fchollet** [comment]
Another question is, why wasn't this caught by unit tests. What are the reproduction conditions?

**Comment by gw0** [comment]
I also stumbled upon this problem after upgrading to *Keras 0.3.0+ (master)*, *Theano 0.7.0* and *NumPy 1.10.1*. Bellow exception is raised when during compilation of:

- `Graph` model
- `Embedding(.., mask_zero=True)` -- masking is used
- `LSTM(.., return_sequences=True)` -- return_requences is used
- `TimeDistributedDense(..)`

```
Traceback (most recent call last):
...
    model.compile(optimizer='adam', loss={'foo': 'mse'})
  File "/xx/venv/src/keras/keras/models.py", line 635, in compile
    self._train = K.function(train_ins, [train_loss], updates=updates)
  File "/xx/venv/src/keras/keras/backend/theano_backend.py", line 361, in function
    return Function(inputs, outputs, updates=updates)
  File "/xx/venv/src/keras/keras/backend/theano_backend.py", line 354, in __init__
    allow_input_downcast=True, **kwargs)
  File "/xx/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/xx/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 489, in pfunc
    no_default_updates=no_default_updates)
  File "/xx/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 204, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```

After removing the `LSTM()` layer or applying the solution by @jeffzhengye (`X *= K.expand_dims(mask).astype(X.dtype)`) compilation works.

Although it is Theano-specific, solving it in the backend is not obvious. Either Theano multiplication should be overridden to cast correctly, or `K.expand_dims()` should silently cast to `_FLOATX` (and lets hope it is never used in any non-floatx situation).

As for the unit-test, I was not able to reproduce it. Probably because I do not know how to manually pass an `input_mask`?

```
        layer.get_output_mask = lambda self, train=False: K.variable(np.ones((nb_samples, timesteps)))
```

**Comment by jeffzhengye** [comment]
@fchollet  can you give me the right to make a PR?

**Comment by fchollet** [comment]
@jeffzhengye Sure, just go ahead and submit it.
