### ISSUE TITLE
Prediction with stateful deep LSTM

### ISSUE THREAD

**Issue by robclouth** [fchollet/keras#1332]
Hey guys, I'm trying to make the lstm_text_generation.py example stateful. I've added 

```
batch_input_shape=(batch_size, sequence_length, len(chars)), stateful=True
```

To the two layers, and changed 
`model.fit(X, y, batch_size=128, nb_epoch=1)`
to 

```
for batch in range(X.shape[0] / batch_size):
        offset = batch * batch_size
        X_batch = X[offset:offset + batch_size, :, :]
        y_batch = y[offset:offset + batch_size, :]
        loss = model.train_on_batch(X_batch, y_batch)
        progbar.add(X_batch.shape[0], values=[('train loss', loss[0])])
```

But when it gets to the prediction and sampling part it crashes, complaining about a dimension mismatch:

```
ValueError: dimension mismatch in args to gemm (128,512)x(512,512)->(1,512)
Apply node that caused the error: GpuGemm{inplace}(GpuDot22.0, TensorConstant{0.20000000298}, <CudaNdarrayType(float32, matrix)>, <CudaNdarrayType(float32, matrix)>, TensorConstant{0.20000000298})
Toposort index: 10
```

Thanks! Any ideas?

**Comment by tuomasr** [comment]
I have the same problem with LSTM and GRU layers. I am trying to model a time series and use the function `fit` instead of `train_on_batch`. With larger batch sizes, the error message above appears already in the training phase but with smaller batch sizes, only the prediction fails. Using the function `predict_on_batch` instead of `predict` does not have an impact.  

The first dimension of the output in the error message (in this case 128)
```
ValueError: dimension mismatch in args to gemm (8,21)x(21,21)->(128,21)
```
varies with respect to the batch size. No dimension in my model matches to 128 so I don't have an idea where it is coming from.

Btw, sometimes Keras documentation refers to an argument `batch_input_size` although only `batch_input_shape` is recognized.

**Comment by edwarner** [comment]
If anyone is still has this problem, the solution is that the number of examples has to be divisible by the max number of time steps your LSTM network can look back.

For example, the **stateful_lstm.py** example, which already has 50000 % 25 = 0, adding the following lines would make it work regardless of the value of xn:

`maxdata = len(cos) // batch_size * batch_size`
`cos = cos[:maxdata]`
`expected_output = expected_output[:maxdata]`

For more great info regarding using stateful LSTMs in Keras, see this thread (special thanks to hft7h1)  [Github Keras Issue 98](https://github.com/fchollet/keras/issues/98)

**Comment by jeffiar** [comment]
I also had the same problem earlier when I was fiddling with stateful LSTMs, but I figured it out. When predicting from stateful LSTMs, the number of samples has to be the batch size specified for training:

`model.input_shape` is `(batch_size, sequence_length, len(chars))`

So even if you only want to predict on one sample, you need to add `batch_size - 1` more dummy samples to the input passed to the model so that it has the right shape. In the case of the lstm_text_generation.py example, you wanna replace [lines 89 to 91](https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py#L89-L91) with this code:

```python
x = np.zeros((batch_size, maxlen, len(chars)))
for t, char in enumerate(sentence):
      x[0, t, char_indices[char]] = 1.
```

hft7h11 explains a bit more in [this comment](https://github.com/fchollet/keras/issues/98#issuecomment-169316842) of the thread. Hope this helps!

**Comment by 9aradox** [comment]
Can anyone verify that the stateful flag actually works? I am feeling like it doesn't actually do anything. All these example show how to get it to compile which has helped me but if I try to test it by setting the timesteps to 1 or by using hft7h11's prediction example which only uses one step at a time. Then nothing converges or makes sense.

The example stateful_lstm in the repository is not a valid example. If you change the stateful flags to False in both layers it still converges and predicts fine.

Is anyone using this class for a real example requiring state I would appreciated hearing about it. I can't figure if I should keep beating my head at this or look outside for a stateful wrapper like in the seya repository. What do people generally use when they need\want statefulness?

**Comment by philipperemy** [comment]
@9aradox I'm working on a more complex example where, I hope, stateful = true would make more sense. The cos seems to be too easy.

**Comment by sehugg** [comment]
I think I've got the stateful mode working. Instead of taking N timesteps and generating 1 output, I'm taking N timesteps and generating N timesteps via the encoder/decoder technique. Pass the input through a stateful RNN and return the last value, then run that through a Dense layer and repeat it N times. Then run that sequence through another LSTM, and time-distribute the samples across the output. Smaller values of N seem to train much faster (mine is at 4). This example is for a regression problem:

```python
model = Sequential()
model.add(GaussianNoise(0.01, batch_input_shape=(nbatch, seqlen, framelen)))
model.add(LSTM(nunits, return_sequences=False, stateful=True))
model.add(Dense(nencoder, activation='relu'))
model.add(RepeatVector(seqlen))
model.add(LSTM(nunits, return_sequences=True, stateful=True))
model.add(TimeDistributedDense(framelen, activation='sigmoid'))

```
The trick is to structure your data so that the "lanes" in the minibatch are consecutive sequences by splitting the dataset into B regions (B = batch size). Varying the regions per-iteration should improve regularization since it's a form of shuffling.

I've posted my attempt at a stateful version of the Nietzsche text generator here: https://gist.github.com/sehugg/3fdd80a08808bd275142d46863e92d68

**Comment by 9aradox** [comment]
Are you sure this example works. It is strange it seems to get a very low loss. But the generation is gibberish. Can you post an example of successfully generation text. I am pretty sure the loss is wrong but not sure why.

 It seems to me whenever timesteps is low the output looks like character frequency predictions but there is no statefulness apparent.

I am not sure about the encoder decoder approach to character generation I have not thought about ti that way. I have some example code for encoders and for text generation but now that I got latest, everything I have doesn't work for some reason or another. Be a while before I can work through all the keras api changes.

**Comment by sehugg** [comment]
I'm having a hard time with it too. The stateful RNNs don't seem stable and the prediction goes awry very quickly. I imagine with generation applications where you don't reset the state for many iterations the state can diverge from what the network is trained to stabilize. At least that's my guess; I need to figure out how to dump the states and see what is really going on. But glancing at some papers, it seems RNN stability is not a simple problem to solve.

There might be another approach besides encoder/decoder, too. The problem is that Keras expects N samples and so you need N outputs for the next iteration. (I actually tried another approach where N = batch size and batch[i] = samples[t+i:t+i+n], but that didn't work either)

**Comment by pikeas** [comment]
@sehugg Did you have any luck with this?

**Comment by sehugg** [comment]
@pikeas Nope, though I'm trying an artificial test case to see if I can tweeze out the problem.

**Comment by sehugg** [comment]
Here's a test case that performs better in the stateful mode than non-stateful: https://gist.github.com/sehugg/18e69f412b10a9c67fd6a011a66133d3

**Comment by philipperemy** [comment]
Another example is there : http://philipperemy.github.io/keras-stateful-lstm/

**Comment by eyaler** [comment]
the stateful rnn requires batch_shape specification with a given batch size. therefore your number of samples must be divisible by the batch_size so that all batches are of batch size. i think this issue can be closed

**Comment by MikeShlis** [comment]
@jeffiar you are saying it saves the states for each sample in the batch which is why you can only predict on a batch of equivalent size. Given that information, if i save the model and then i load it, will this still be the case?
