### ISSUE TITLE
Lambda layer should allow injection of globals?

### ISSUE THREAD

**Issue by jrao1** [fchollet/keras#1408]
Not a Python expert so I may be missing something here, but I think this line of code in Lambda layer's get_output:

```
func = types.FunctionType(func, globals())
```

seems to use the globals from the core module. I think it may be helpful if there is a way for caller to inject their own globals, since a lot of times the function needs custom values.

**Comment by farizrahman4u** [comment]
Hi,
When I wrote the Lambda layer I considered it, but it turns out it would be simply bloating the API.. 99% of the time the Lambda function only uses basic math operators and basic  functions like K.abs, K.exp etc, and scalar constants. Do you have any particular problem you are trying  to solve? I might be able  to provide you a work around without changing the Keras API.
Happy New Year!

**Comment by jrao1** [comment]
Hi, thanks for the quick reply. See https://gist.github.com/jrao1/9117c9f436270e8af158 for an example. Also in the past I tried to use Theano specific functions, and it won't work since core module didn't import Theano.

**Comment by farizrahman4u** [comment]
@jrao1 The easiest way would be to redefine `stepsInFuture` inside your Lambda function..We can not support injecting globals due to serialization issues.(We have to save models to json / pickle etc)..
As for theano specific functions, you can write `import theano` and `import theano.tensor as T` inside your lambda function.

**Comment by jrao1** [comment]
@farizrahman4u Ok, just to be clear (since I'm not totally familiar with Python's scoping), by redefine stepsInFuture, you mean something like this:
```
def time_slice(output):
    stepsInFuture = 20
    return output[:,-stepsInFuture:,:]
```
?

If so it seems that this doesn't solve the problem where we had to hardcode a constant inside Lambda function? If say we want to make this model a class, and stepsInFuture to be a class property/variable, passed in in the constructor, then this wouldn't work?

**Comment by farizrahman4u** [comment]
I haven't  tried it, but here is something you could possibly do. Set `stepsInFuture` as member variable of your `Lambda` layer. Then inside your  `time_slice` function, you can access it using `self.stepsInFuture`.

```
def time_slice(output):
    return output[:,-self.stepsInFuture:,:]

def shape(input_shape):
    #TODO
    return input_shape
`
lambda_layer = Lambda(time_slice, shape)
setattr(lambda_layer, 'stepsInFuture', 20)
```

**Comment by jrao1** [comment]
@farizrahman4u This seems to work:
```
    core = sys.modules['keras.layers.core']
    setattr(core, 'stepsInFuture', 20)
```

Not pretty but I guess it will do for now, thank you for the idea.
