### ISSUE TITLE
LSTM with initial weights is failing to build

### ISSUE THREAD

**Issue by jgc128** [fchollet/keras#1427]
The following model is failing to build:

``` python
model = Sequential()
model.add(Layer(input_shape=(max_len, input_dim,)))
model.add(LSTM(weights=init_weights, input_dim=input_dim, input_length=max_len, output_dim=lstm_size))
```

Keras is calling `build` several times (see #965): the first time in the `__init__` of `Layer` and the second time in the `add` -> `set_previous` because `LSTM` is not the first layer of the model.

Because `LSTM` deletes `initial_weights` in `build` ([recurrent.py](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L413-L415)):

``` python
        if self.initial_weights is not None:
            self.set_weights(self.initial_weights)
            del self.initial_weights
```

it causes an error `AttributeError: 'LSTM' object has no attribute 'initial_weights'` on the second build.

The easy fix would be just delete `del self.initial_weights` but I think it's better to build each layer of the model only one time...

**Comment by mbotumbo** [comment]
It might be better to prevent repeated setting/re-initialization of weights in the long term. Is there a reason for this?

**Comment by fchollet** [comment]
That's not even a valid Keras model. You're not supposed to use the
abstract Layer class in a model. Just start your model with LSTM.

**Comment by jgc128** [comment]
@fchollet Layer here is just for example. You can put Masking as the first layer and get the same result.

LSTM's initialization is very important and it will be great if Keras supports it

**Comment by mbotumbo** [comment]
Try removing the input information (eg input dim) from the lstm parameters. It's supposed to infer this from the previous layer, which is where you are running into problems I think.

**Comment by jgc128** [comment]
@mbotumbo Thanks, it helped!

**Comment by wchen459** [comment]
I encountered the same issue. I changed `del self.initial_weights` into `self.initial_weights = None` and it solved the problem. However I'm not sure if it's a correct solution.

**Comment by mbotumbo** [comment]
It depends. Here's more or less what happens to me when this occurs, and why your solution might not work. 

First, I create a layer with some given weights. That layer is added to a model, and build() is called as one of the steps in that. The build() sees that there were some given initial_weights, and so sets the layer weights to those given weights, and then deletes the initial_weights attribute. Next, for some  reason, I do something that causes build() to be called on that layer again (maybe I add it to a second model), this time, build tries to check for the initial_weights, but that attribute no longer exists. So, you get an error. 

Now, setting initial_weights to None addresses this problem, by making sure that the initial_weights attribute _exists_ at all. If that is all you need, then I suppose this is a possible work around. But, if you were actually trying to _use_ some initial weights, you have a problem because the weights are lost when the layer is re-built and no real initial weights are found. 

Assuming you are doing everything correctly, and you've found yourself in this situation, i'd suggest keeping track of the layer and then use .set_weights() once you are done doing everything else with it and ready to compile rather than using provided weights when you create the layer.

**Comment by wchen459** [comment]
@mbotumbo What do you mean by "re-built" ?

**Comment by mbotumbo** [comment]
@wchen459 All layers have a build(self) method that gets called when the input_shape is specified or the layer is added to a model and set_previous() is called as part of that add (e.g [here](https://github.com/fchollet/keras/blob/90aafca585ca92d7ff558d811ff8eb8d60d7c3d4/keras/layers/core.py#L151).). Build does things like create the initial random weight matrices of your layers. Under typical circumstances, this method will (and should) only be called once. In build, if you provided weights, that is also where those weights get incorporated into the layer. 

One way it gets called twice was what happened with the OP, where it is called twice incorrectly (once because input_shape was specified and once when it is added to the model). It is, however, possible to find yourself in the situation (especially when coding up your own custom layers and model handling) where .build() might get called more than once on the same layer and there is nothing you can do to avoid it. 

This is what I mean by the layer being re-built. You've done something, correct or not, that causes the build() method to be called two or more times on the same layer. If that happens, and you have provided weights when the layer was created, you will get the error discussed here because the provided weights are deleted the first time build is called. This is a good thing IMO, because 1) you don't wan't to be holding onto old unused references to those provided weight matrices and 2) you will run into this error and know about it.

The problem with setting the weights back to None is that, because build was called twice they are overwritten.

**Comment by wchen459** [comment]
@mbotumbo I see. Thank you so much for the explanation! I guess I'll use .set_weights() to set the initial weights.

**Comment by mbotumbo** [comment]
@wchen459 I hope it helps. I should add, it is probably never truly "correct" to have build called more than once. At best it'll lead to wasted computation, and ideally you'd find some way around it. But, in my experience, it is sometimes very hard to avoid that.
