### ISSUE TITLE
fit_generator uses the wrong axis to get the batch_size

### ISSUE THREAD

**Issue by berleon** [fchollet/keras#1428]
When the generator returns a numpy array and not a list, the `fit_generator` function uses the wrong axis to determine the `batch_size`. This results in a wrong counting of the samples seen.
For example, if the generator returns numpy arrays with shape `(128, 40, ..)`, then the number seen will be increased in 40 steps instead of 128. This can cause an Exception if the `sampes_per_epoche` is not dividable by 40.  This bug is fixed in pull request #1407.

**Comment by raindeer** [comment]
@fchollet I can confirm this. Currently  `batch_size = len(X[0])` in fit_generator but is should be `batch_size = X.shape[0]`. E.g., for convolutional layers `len(X[0])` will be the number of channels.

**Comment by fchollet** [comment]
Incorrect, because X in this case is always a list (of size 1 if you only
have one input).

**Comment by cbodenst** [comment]
I am facing the same problem using my own data generator. I fixed this by  `yield [X], Y` instead of `yield X, Y`. I am still not sure if I understood why the `X` data should be wrapped in a list. Can you explain this? Maybe you should add this point at the fit_generator example in the documentation.
