### ISSUE TITLE
Recurrent go_backwards and output reversal

### ISSUE THREAD

**Issue by mbotumbo** [fchollet/keras#1431]
Caveat: I'm Working in Theano, don’t know if TF is different. 

The output of a scan with go_backwards is in the order that the sequence is processed. So, the first time step in the output of a go_backwards scan corresponds to the output after processing the original last element of the input sequence. 

If return_sequences=False, this is fine. output[-1] represents the result of processing the full sequence. But in the return_sequences=True context, this is going to hurt since outputs don’t have sequential correspondence with their inputs. Consider a bidirectional sequence labeling task. The point of bidirectionality here is to have access to the entire context at each time step. Any merge on the first element contains only the recurrent output of x<sub>0</sub> and x<sub>n</sub>, but instead should contain x<sub>0</sub> and x<sub>n,…,0</sub>. 

Easy way to check this is: 

```python 
forward = Sequential()
forward.add(Embedding(100,7))
forward.add(LSTM(12, return_sequences=True))

backward = Sequential()
backward.add(Embedding(100,7))
backward.add(LSTM(12, return_sequences=True, go_backwards=True))
```
then compile
```python
forward.set_weights(backward.get_weights())

input = np.array([[1,2,3,4,5,6]])

np.all(forward.predict(input[:,::-1]) == backward.predict(input))
```

The result of that all is going to be true, which means the final output of backwards is in reverse order from the input to forward. 

# EDIT

FYI, I've addressed this locally just by overriding get_output with a final:

```python
if self.go_backwards:
    return output[:, ::-1]
else:
    return output
``` 
and have seen some pretty significant sequence labeling gains.

**Comment by farizrahman4u** [comment]
#1282

**Comment by pasky** [comment]
@mbotumbo, any particular reason you closed this? I'm pretty convinced this is still a problem. Regardless of what eventually happens with #1282, I think Recurrent go_backwards=True return_sequences=True should flip the output anyway.

**Comment by mbotumbo** [comment]
@pasky I am on the fence about this. Here's my current thinking. 

First, although a little bit buried it did seem pretty well covered in #1282, so I didn't wan to add to clutter. 

Second, I wasn't able to fully convince myself go_backwards is useful outside of bidirectional processing (e.g. if you want to process inputs backwards only, why not reverse the input?). However, one could argue if that is the case, maybe go_backwards shouldn't be exposed at it's current level as an argument.  

Third, its not totally clear to me this behavior is definitely a problem. It was annoying for me, and I gather it was for you too, but it also makes sense, in a way, why it does what it does. Again, this might indicate a little additional documentation would be helpful or, again, if i'm right about the "second" thing, perhaps it shouldn't be exposed where it is. 

Thoughts? Still think I should reopen?

**Comment by lemuriandezapada** [comment]
Thanks for this. I dug for a solution for some days.
Although I would amend it to:                 
```Python
return outputs[:, ::-1,:]
```

Since most of the time your time sequences are 3d anyway. Though I don't know if this is actually the correct way to fix this. Will autodiferentiation find the way to propagate the error if we do it like this?

This IS an issue if you want to do anything with Bi-RNNs and return_sequences = True. 

For example, in my case: I have a string of tokens, one embedding layer, that then go into two RNNs, one forward, one back with return_sequences = True. The output then gets merged. If I'd have to make another embedding layer to provide the data again in reverse order just so it comes out in the right sequence in the backwards RNN, I'd be copying shit twice. Which is pointless. Getting this properly addressed is important.

**Comment by mbotumbo** [comment]
@lemuriandezapada  Indeed that was a mistake, thanks for the catch. I'll fix it above so i don't confuse anyone. 

I think Theano handles this OK, and, just by the fact that this seems to work far better (i.e. better results) than not doing it would suggest error is getting propagated correctly. 

Regarding Bi-RNNs, yes. This is along the lines what I was saying above. Bi(directional)-RNNs is about the only case where I'm seeing a clear use for go_backwards=True, and it is what was being addressed in #1282.

**Comment by farizrahman4u** [comment]
Fun fact : #1282 do not use `go_backwards` argument.

**Comment by mbotumbo** [comment]
@farizrahman4u Yeah, but input reversal is essentially equivalent to go_backwards=True, right?

**Comment by farizrahman4u** [comment]
Yes.

**Comment by Yelrose** [comment]
Thanks, it helps a lot. The go_backward flag is confusing. @fchollet  I think you should at least mention this problem in the API document.

**Comment by pasky** [comment]
I agree, @fchollet.  I think I didn't try to add the wrapper mainly
because I ended up being in a bit of a rush and didn't want to worry
about unit tests. ;-)  I'm now offline for 14 days but I promise to
come back to this PR at the end of August and add the Bidirectional()
wrapper, unless someone beats me to it.

**Comment by nadavb** [comment]
So @farizrahman4u, @mostlymetalman, do I understand correctly, 
according to the docs the input reversal is **not** equivalent to go_backwards=True, but rather go_backwards=True means that you both reverse the input **and** reverse the outputs (meaning that you reverse the timestamp for every output).

So is the current documentation right?

Docs say: "go_backwards: Boolean (default False). If True, process the input sequence backwards and return the reversed sequence."

**Comment by mostlymetalman** [comment]
@nadavb These comments were from a while ago... a lot has changed since then. 

I just did some quick tests (TF Backend). 

go_backwards is equivalent to reversing the input. No additional reverse operation is on the output, so the output time steps are in reverse temporal order. 

I think the documentation is perhaps linguistically ambiguous. Maybe it could say "Processes the input sequence backward. The output sequence will, therefore, be in reverse temporal order. So, just to make sure we are on the same page. go_backwards works like this:

```python
def process(regular_list, go_backwards=False, op=lambda x: x+2):
    """regular_list is a regular old python list, each element is a time step"""
    if go_backwards:
        return [op(x) for x in regular_list[::-1]]
    else:
        return [op(x) for x in regular_list]
 ```

It does not work like this (reversing the input then reversing the output so that everything is in the right order):
```python
if go_backwards:
    return [op(x) for x in regular_list[::-1]][::-1]
```

But, since your problem is Bidirectional layers, have you looked at [this]( https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L217)? You can see there how the fact that output is in the wrong order is handled. When y_rev is a sequence, it is in the wrong order, to it is reversed:

```python
y_rev = self.backward_layer.call(inputs, **kwargs)
if self.return_sequences:
    y_rev = K.reverse(y_rev, 1)
```

I'm not sure how you tested this to prove it to yourself, but I did: 

```python
i = Input((None,))
e = Embedding(5,2,mask_zero=True)(i)
f = LSTM(3, return_sequences=True)(e)
b = LSTM(3, return_sequences=True, go_backwards=True)(e)
fm = Model(i, f)
bm = Model(i, b)
i = np.eye(3)
print("Regular")
print(fm.predict(i))
print("Reverse")
print(bm.predict(i))
```

**Comment by nadavb** [comment]
Okay, so we all agree that go_backwards simply changes the order of the input, and not the output.
Can you please change the documentation from:

> "If True, process the input sequence backwards and return the reversed sequence."

to something like

> "If True, process the input sequence backwards"

If someone wants to also reverse the output of an LSTM, like in bidirectional LSTM for example he should do:

`reversedLSTM = Lambda(lambda inputTensor: K.reverse(inputTensor, axes=0)) (LSTM)`
