### ISSUE TITLE
skipgram_word_embeddings.py not existing, how to test (& play) the O/P of the word2vec 

### ISSUE THREAD

**Issue by AhmedGS** [fchollet/keras#1541]
Hi,
The skipgram_word_embeddings.py file is not existing anymore in the examples!
We will have an updated version soon or what? I have the old version but it's not working anymore.

I need to validate the quality of my embedding before building on top of it.

Thanks in advance,
A

**Comment by fchollet** [comment]
I recommend you use Gensim for computing word embeddings.

**Comment by bkj** [comment]
Do you recommend Gensim because of some issue with the way skipgram was implemented in the deprecated example, or just because Gensim is better optimized? 

I'm trying to learn some nonstandard embeddings that use a skipgram model as a component -- seems straightforward enough to port the old Keras example to the new APIs, but but was wondering if there are particular problems I should be aware of.

Thanks
Ben
