### ISSUE TITLE
some problems with lstm_text_generation.py

### ISSUE THREAD

**Issue by panjinbo** [fchollet/keras#1609]
I have tried the tutorial code lstm_text_generation.py.
And it seems that it just uses the previous n chars to predict the next one, not all the previous chars, which I think is just as n-gram model.
And I want to ask can I use keras to write a model which uses all the previous chars to predict the next one?

**Comment by StephanHeijl** [comment]
The nature of an LSTM network is that it is able to take data from previous timesteps into account when predicting the next character. While the network is only 'fed' the previous `n` characters, the imprint of any characters outside the `n` range "lingers", if you will, because the neurons are connected to themselves through time. This results in a far larger range of characters being taken into account when predicting then what is actually given at any point.

**Comment by panjinbo** [comment]
@StephanHeijl  My question is ,for example, we have sequence ABCDEFGHIJKLM we use ABC to predict D , BCD to predict E etc. The  training set is [ [ ABC] [BCD]...] the target set is [D E ...] . We train on minibatch, which means the first hidden layer of [BCD] is not the last hidden layer of [ABC]
