### ISSUE TITLE
TimeDistributedMerge should support masking?

### ISSUE THREAD

**Issue by jmhessel** [fchollet/keras#1698]
I am trying to use TimeDistributedMerge but am running into some issues. Currently, it subclasses layer, but I see no reason why it shouldn't support masking (all of the merging operations could simply ignore the masked values).

I don't think I am familiar enough with the standards of MaskingLayers to implement this currently. I'm working on it right now but would appreciate any insights.

**Comment by jmhessel** [comment]
`    def get_output(self, train=False):
        X = self.get_input(train)
        mask = self.get_input_mask(train)
        if mask is not None:
            if self.mode == 'ave':
		s = K.sum(X, axis=1)
                return s/K.sum(mask)
            elif self.mode == 'sum':
                s = K.sum(X, axis=1)
                return s
            elif self.mode == 'mul':
                raise Exception("mul for masked mode is not supported")
            else:
                raise Exception('Unknown merge mode')
        else:
            if self.mode == 'ave':
                s = K.mean(X, axis=1)
                return s
            elif self.mode == 'sum':
                s = K.sum(X, axis=1)
                return s
            elif self.mode == 'mul':
                s = K.prod(X, axis=1)
                return s
            else:
                raise Exception('Unknown merge mode')`

**Comment by jmhessel** [comment]
(I am realizing that code is definitely not right, but I would appreciate input)

**Comment by wxs** [comment]
Hmm. You're not necessarily guaranteed that the masked values will be 0, so you probably want to check for that to be safe. (although you may be right for every current layer which generates a mask).

When you sum the mask for the average case, I assume that you want to take that sum across the time axis, so something like `return s / K.sum(mask, axis=1)`.

Finally: is there a reason not to support `mul`? You can set all the masked entries to 1 before the `prod` call.

Not sure if there are other issues. If I were you I would create a unit test for a masked merge in the Keras tests, then try to build the implementation. If that doesn't work you can post the test and the error. That will also make your pull-request better since it'll have a test ;)

(You'll also need to make sure that `supports_masked_input()` returns True on this new model)
