### ISSUE TITLE
preprocessing utils would greatly benefit from sklearn

### ISSUE THREAD

**Issue by pannous** [fchollet/keras#17]
>  These preprocessing utils would greatly benefit from a fast Cython rewrite.

Preprocessing utils would greatly benefit from sklearn.feature_extraction.text, no?
Or do you want to keep dependencies low and have more fine-grained vectorization?

**Comment by fchollet** [comment]
Scikit-learn provides great utilities for text preprocessing/vectorizing, and Keras does not aim at reimplementing any of that. Keras and Scikit-learn are already compatible since both work with the same numpy arrays, so no need for further integration. 

The functionality in preprocessing.text takes care of what Keras needs that scikit-learn doesn't do: for now mostly working with sequences (lists of word indexes in a vocabulary, sorted by frequency in the vocabulary for convenience). This is relevant mostly for RNNs.

**Comment by pannous** [comment]
```
vectorizer = CountVectorizer(max_features=max_words,binary=True)
vectorizer.fit(phrases)
X = vectorizer.transform(phrases)
X=[m.indices for m in X] 
# ^^ sparse matrix to sequences
```
