### ISSUE TITLE
minibatch handling could be more efficient if dataset was stored as shared variable?

### ISSUE THREAD

**Issue by nidleo** [fchollet/keras#1754]
The following Theano tutorial recommends storing the dataset as shared variables and indexing into it to form minibatches.
http://deeplearning.net/tutorial/gettingstarted.html (see shared_dataset function)

This avoids the overhead of copying a each minibatch into GPU.
From my experience, this overhead can cause x2 slowdown even for reasonable batch size (e.g. 128).

It appears Keras does not follow this recommendation. Is there a reason not to do so?

**Comment by neggert** [comment]
I'm not a core developer, but if I understand the question correctly, that would limit you to datasets that fit in GPU memory. On modern datasets and networks, you even have to be careful about choosing minibatch size so that a full minibatch fits in memory. Putting the entire dataset in there is out of the question.

**Comment by fchollet** [comment]
Loading each minibatch separately on the GPU is the right way to proceed for everything except very small models / datasets.

If you are training a small MLP on MNIST then sure, you are incurring significant overhead by loading your samples in the GPU 32 at a time, simply because the time it takes to load them is significant compared to the time it takes for the network to process them. But as soon as the processing time becomes large compared to the loading time then this is no longer an issue, e.g. if you are using:
- large enough minibatches
- large enough models
- large enough samples (e.g. "real" images (not MNIST or CIFAR10), sound files, etc).

So for anything but the smallest of toy models, data should be loaded one batch at a time. Even a toy convnet on CIFAR10 satisfies the condition above, so...

**Comment by nidleo** [comment]
Thanks fchollet.

To answer neggert:
You cannot expect to store the entire dataset, but this can be still be handled efficiently. 
Suppose the GPU has enough memory for 10K examples, and the batch size is 100. You could load a chunk of 10K examples from the dataset, do the indexing to get the 100 batches. Then continue the same for the next chunk of 10K.

**Comment by neggert** [comment]
I've found that when doing something like running GoogLeNet on 299x299 images, 4GB of GPU memory is just barely enough to hold a small-ish minibatch and all the network parameters. Putting 10k examples on the GPU is out of the question in this case.

**Comment by PeterChe1990** [comment]
@nidleo do you still have the same issue or you find a nice way to work around within keras? 
I know this will probably not be handled in keras as most dataset are too large to be stored in GPU entirely. But I also have a relatively small-mid size dataset and want to load more data into GPU than just 1 batch.

**Comment by nidleo** [comment]
@PeterChe1990 I sticked to loading each batch to GPU like Keras does for the sake of a simplicity and to support big data\models. Training on small problems is relatively quick anyway so getting some speed up  didn't justify the effort.

**Comment by PeterChe1990** [comment]
@nidleo Thanks!

**Comment by Slanothy** [comment]
I believe the notion that this problem is only valid for the "toy" models is not true when you are dealing with the a powerful processing units with a lot of RAM that would allow for a reasonable chunk of data to be stored on it:

I am running a fairly large model with several features per time distributed step on 4 Tesla P100s with 16gb RAM each. The model contains seeral embedding layers (for different types of codes), LSTM 150 layer and several dense layers with varying size. Even if I run a model on 1 GPU with the batch size of 500-1000 I am only seeing a 30-40% utilization through nvidia-smi and 80% utilization with 2000. 
I don't think increasing the batch size even more is a way to go since that will take more epochs and will lead to overfitting (correct me if this assumption is wrong) and I've already noticed the reduction in performance metrics due to less weight updates per epoch. 

I assume that prefetching parts of input data onto GPU as a macro-batch will decrease the overhead of transmitting data but as far as I am aware the only way to do this is through setting a constant tensor on GPU. However these cannot be used as input for Model.fit so for now there is not good way to move parts of input to the GPU. 

Please let me know if some of the assumptions I've made are wrong and I could try something else to increase the GPU utilization.
