### ISSUE TITLE
Tensorfuse - Wrapper around tensorflow, theano and CGT

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#1780]
Maybe it's a good idea to use this wrapper (https://github.com/dementrock/tensorfuse) instead of implement our own wrapper on keras. What do you think?

**Comment by fchollet** [comment]
It would stink, for *many* reasons. For instance, we frequently need to modify our backend API.

Just because it exists, doesn't mean we should use it. Not to mention that the common Theano-TensorFlow interface implemented by Keras was the first of its kind, so it would make more sense to ask such projects why they're not using the Keras backend instead of reimplementing it ;-)
