### ISSUE TITLE
Do we have a way to initialize the random seed for everything

### ISSUE THREAD

**Issue by fayeshine** [fchollet/keras#1795]
Do we have a way to initialize the random seed for everything? I set the numpy seed to a fixed number, however I got different results everytime.
Is there any other random component need to be fixed?

**Comment by fayeshine** [comment]
I found that it is Convolution2D generate the difference under same random seed, can anyone explain why this happen?

**Comment by parag2489** [comment]
From [here](), 

_"The Theano flag `dnn.conv.algo_bwd` can be use to force the use of a slower but deterministic convolution implementation."_

So, by default, Theano uses a non-deterministic convolution operation and Keras run on top of Theano, maybe that's why you can't see the same results. You can change the flag - `dnn.conv.algo_bwd` - in .theanorc file and see if it solves the issue for you. By the way, I think that flag is deprecated and the new flags are: `dnn.conv.algo_bwd_data` and `dnn.conv.algo_bwd_filter`.

**Comment by fayeshine** [comment]
@parag2489 thank you, I'll try this flag.

**Comment by Ogaday** [comment]
Did this work for you? @fayeshine

**Comment by fayeshine** [comment]
@Ogaday Yes, I think it just work, I'll close this
