### ISSUE TITLE
what if my data can note load into memory?

### ISSUE THREAD

**Issue by whjxnyzh** [fchollet/keras#183]
In keras examples, the data are all load in to memory at once, what if my dataset very big and can not load into memory, how to train it? thank you very much

**Comment by tleeuwenburg** [comment]
Hi Whjx,

You wouldn't normally need to load all training examples simultaneously;
the networks are trained in batches.  Tell us a bit more about your data.
You might find your problem is not really specific to Keras, but is
actually more general. You might benefit from going through some approaches
that other people have taken to similar problems.

Cheers,
-Tennessee

On 2 June 2015 at 19:26, whjxnyzh <notifications@github.com> wrote:

> In keras examples, the data are all load in to memory at once, what if my
> dataset very big and can not load into memory, how to train it? thank you
> very much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/183>.
>



-- 
--------------------------------------------------
Tennessee Leeuwenburg
http://myownhat.blogspot.com/
"Don't believe everything you think"

**Comment by whjxnyzh** [comment]
@tleeuwenburg I found that caffe use lmdb. i think i can read a batch from lmdb can train the model batch by batch. i will try it out. thank you
