### ISSUE TITLE
LSTM with multiple sequences (3d) input

### ISSUE THREAD

**Issue by tuming1990** [fchollet/keras#1838]
Hi,

I have a sequence classification task with 11 categorical outputs.
My input is 3d: nbsamples*398*40 (398 is number of time steps per sequence, 40 is the input dimension)
The output I expect is nbsamples*11

My code for building the model is:
model = Sequential()
model.add(LSTM(128,input_shape=(398,40),activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))
model.add(Activation('sigmoid'))
model.add(Dropout(0.2))
model.add(TimeDistributedDense(11))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

This gives error:
`TypeError: ('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py:380"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (128, 11).')`

I searched the internet and document hardly but didn't find something very useful.

Could anyone help me modify this code to make it work? Thank you very much! I appreciate it a lot!

**Comment by 9aradox** [comment]
This compiles fine when I tried it. You maybe should try updating keras.

**Comment by jgc128** [comment]
The problem is that you specified `return_sequences=True` for the LSTM layer. Because of it, LSTM returns its hidden state at each timestep and your output has the shape `(nb_samples, timesteps, nb_classes)`

If you want to classify the whole sequences you should specify `return_sequences=False` (which is default value so you can just drop this parameter) and replace `TimeDistributedDense` with just `Dense`. In this case LSTM will return only the last hidden state.

**Comment by tuming1990** [comment]
@jgc128  Thanks! It works!
