### ISSUE TITLE
Increasing accuracy of multi-label image classification

### ISSUE THREAD

**Issue by eldor4do** [fchollet/keras#1839]
I want to do multi-label image classification. For this, I am currently getting the pool3 features for each of my images from tensorflow's inception model, and then using those to prepare my data set for classifying it into labels.
Currently, this is my code.

```
    from sklearn.preprocessing import MultiLabelBinarizer
    from keras.models import Sequential
    from keras.layers.core import Dense
    import pickle
    import numpy as np

    data = pickle.load(open('/data.p','rb'))  # contains pool3 feature vector
    target = pickle.load(open('/target.p','rb'))  # contains multi label as text
    data = np.array(data)
    mlb = MultiLabelBinarizer()
    mlbtarget = mlb.fit_transform(target)
    # mlbtarget.shape is (1001, 238)
    testdata = [data[2],data[3]]
    testdata = np.array(testdata)
    testtarget = [mlbtarget[2],mlbtarget[3]]


    model = Sequential()

    model.add(Dense(output_dim=2048, input_dim=2048, init='uniform', activation='tanh'))
    model.add(Dense(output_dim=238, init='uniform', activation='sigmoid'))
    model.compile(optimizer='adadelta', loss='binary_crossentropy')

    model.fit(np.array(data), mlbtarget)
    objective_score = model.evaluate(testdata, testtarget, batch_size=1)
    print objective_score`  # currently objective_score is 0.0898
```

Is this approach correct? What things should I be doing better?

**Comment by keunwoochoi** [comment]
Any regularisation and optimisation technique is worth to try - using ReLU and it's variants, dropouts, Maxout. I'll first try with ReLU+Dropout as you may want sparsity.

**Comment by eldor4do** [comment]
Okay, will add those changes and see how it affects my score. And to be honest, the current parameters, activation of tanh and the rest, I just saw it on a sample example somewhere and wanted to see if the code worked. I'm just starting out with this. Thanks for the help!

**Comment by keunwoochoi** [comment]
Welcome :) the situation is simpler than usual as you don't care about convolution layers. Then I'll add some more explanations. ReLu: because it is very common and usually outperforms tanh regarding speed/performance. Then Dropout: because it encourage the sparsity. Then probably increase the dense number 2048 to something like 4096 and/or add more layers (+1 or +2 layers sounds reasonable) as 238-dim multi-label is quite harsh problem I guess. Also try to add Batch Normalisation especially at the beginning if your input data is not whitened.

**Comment by eldor4do** [comment]
Hi, I considered all of that, but still my accuracy is about 0.27 (val_acc)
This is my current code, are there any more obvious changes that I can make to increase the accuracy?

 ```
model = Sequential()
model.add(Dense(output_dim=4096, input_dim=2048, init='uniform', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5)) 
model.add(Dense(output_dim=4096, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(output_dim=2048, activation='relu'))
model.add(Dense(output_dim=mlbtarget.shape[1], activation='sigmoid'))
model.compile(optimizer='adadelta', loss='binary_crossentropy')
model.fit(data, mlbtarget, batch_size=32, validation_split=0.15, nb_epoch=100, show_accuracy=True)

```
Currently, I have about 21000 samples, and I need to predict a 238-dim multi label.
Do I need to get more data?

**Comment by keunwoochoi** [comment]
It's always not easy to analyse what's going on inside of the networks. But what's the patterns of training/validation loss/acc? If it doesn't even overfit you should have more complex model. If it overfits add more regularisation. Otherwise you may need more data. 21000 samples for 238-dim multi label could be not enough I guess.

**Comment by alyato** [comment]
@eldor4do Do you solve your problem? I does  multi-label image classification and don't know how to do.
Do you share your code or  give me one simple example,especilly how to load the dataset

**Comment by keunwoochoi** [comment]
It's the same except...
* use `sigmoid` for output activation function instead of `softmax`
* use `binary_crossentropy` (or `mse`&friends) for loss function instead of `categorical_crossentropy

I don't get what kind of dataset loading procedure you're wondering, but that seems like not much about multilabel classification and a more general issue.

**Comment by alyato** [comment]
@keunwoochoi  Thanks

**Comment by RanaSamy** [comment]
@eldor4do  I wonder what  the format of pickle file is or what you are saving in it , because I save a dictionary whose key is the image name  and its value is 2048 features extracted from pool-3 , but when I run your code I encounter this error "ValueError: Error when checking input: expected dense_29_input to have 2 dimensions, but got array with shape ()" at this line "model.fit(data, mlbtarget, batch_size=32, validation_split=0.15, nb_epoch=100)"

**Comment by eldor4do** [comment]
@RanaSamy I don't think my code here will work now, this was written for an older version of Keras. I would need to check if it will work for Keras 2.

**Comment by RanaSamy** [comment]
@eldor4do I think I don't have a problem in the code my problem is in the input data (features pickle file)
there is a problem in data dimensions so i need to know how you save the data in pickle file , as i saved it as a dictionary

**Comment by alyato** [comment]
hi @eldor4do I use function API in keras_1.2.1 to train my model.
I want to call `model.predict_proba`,like the Sequence,But the API don't have the `predict_proba`.
I cheak that The APi can get  `predict_classes`,like the Sequence.
How do i do? Thanks.
