### ISSUE TITLE
Convolutional network in Theano on GPU creates graphic artifacts

### ISSUE THREAD

**Issue by marcj** [fchollet/keras#1887]
![keras-gpu-convolutional-errors](https://cloud.githubusercontent.com/assets/450980/13513078/e2e30cfc-e19e-11e5-8aa6-ec543c4a31b9.gif)

I used pretty much this code here https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py to train MNIST dataset and got very strange effects in other applications. I have a GeForce 690, which has two GPU each 2GB RAM, so it should enough for the rather little convolutional network.

On the right, where the strange things happen, is normally an Java application called JetBrains PHPStorm.

Several things I could imagine:

1. GPU RAM full, which wasn't the case.
2. GPU RAM access collision, which shouldn't happen?
3. GPU is dying?

Another interesting facts: Does only happen with the convolution layer. Stops when the training is done. Artifacts increases when I start another conv net at the same time.

Anyone else ever notices such behaviour?

**Comment by fchollet** [comment]
This would happen when you are nearing complete RAM occupation on your GPU. It's not related to Keras per se, it's an issue with the GPU drivers for your platform. The best solution is to keep 2 GPUs on your machine, one for deep learning and a small one for your graphical environment.

Closing because not Keras-related.

**Comment by marcj** [comment]
Thanks @fchollet, I keep watching this gpu issues.
