### ISSUE TITLE
Custom Recurrent Model

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1896]
I want to implement the recurrent model explained in eqn 11,12,13 of [this](http://arxiv.org/abs/1509.06664) paper. As far as I understand, I need to subclass the recurrent layer from keras, but I do not understand where is the state being glued together. eg. In GRU,

```
        x_z = x[:, :self.output_dim]
        x_r = x[:, self.output_dim: 2 * self.output_dim]
        x_h = x[:, 2 * self.output_dim:]
```

But where do I stitch the vectors together?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by farizrahman4u** [comment]
You could ave just checked out the code for GRU in recurrent.py. Here are the list of functions you have to re-implement to get you started:

* `__init__`
* `preprocess_input` : The input gates (Which are outside the main "loop" of your RNN is written here
* `step` : Write your step function here. (The loop of your RNN)
* `build` : Define your params and the initial states
* `output_shape`
* `get_initial_states` : Not required always.. it depends
* `get_config` : Optional.

**Comment by Sandy4321** [comment]
Super, do you have example for rnn last gru sentiments analysis or other
text classifications

**Comment by farizrahman4u** [comment]
@Sandy4321 Its in the examples directory `examples/imdb_lstm.py`.

**Comment by Sandy4321** [comment]
pls help get it running:
super I try to use on windows pc but have this error

File "C:\Sander\my_code\keras-master\examples\imdb_lstm.py", line 49, in
<module>
  model.add(Embedding(max_features, 128, input_length=maxlen, dropout=0.5))
File "C:\Anaconda\Lib\site-packages\keras\layers\embeddings.py", line 68,
in __init__
  super(Embedding, self).__init__(**kwargs)
File "C:\Anaconda\Lib\site-packages\keras\layers\core.py", line 47, in
__init__
  assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' +
kwarg

AssertionError: Keyword argument not understood: dropout



at output
Using Theano backend.
C:\Anaconda\lib\site-packages\theano\tensor\signal\downsample.py:5:
UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Loading data...
20000 train sequences
5000 test sequences
Pad sequences (samples x time)
X_train shape: (20000L, 100L)
X_test shape: (5000L, 100L)
Build model...

keras upgrade does not help

ocal\temp\tmptwliy1pip-wheel- --python-tag cp27:
  lapack_opt_info:
  openblas_lapack_info:
    libraries openblas not found in ['C:\\Anaconda\\lib', 'C:\\',
'C:\\Anaconda\
\libs']
    NOT AVAILABLE

  lapack_mkl_info:
  mkl_info:
  C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:635:
UserWarning:
 Specified path C:\aroot\stage\Library\lib is invalid.
    warnings.warn('Specified path %s is invalid.' % d)
  C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:635:
UserWarning:
 Specified path C:\aroot\stage\Library\include is invalid.
    warnings.warn('Specified path %s is invalid.' % d)
    libraries mkl_core_dll,mkl_intel_lp64_dll,mkl_intel_thread_dll not
found in
[]
    NOT AVAILABLE

    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in C:\Anaconda\lib
    libraries lapack_atlas not found in C:\Anaconda\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\Anaconda\libs
    libraries lapack_atlas not found in C:\Anaconda\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in C:\Anaconda\lib
    libraries lapack_atlas not found in C:\Anaconda\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\Anaconda\libs
    libraries lapack_atlas not found in C:\Anaconda\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda\lib
    libraries lapack_atlas not found in C:\Anaconda\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda\libs
    libraries lapack_atlas not found in C:\Anaconda\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in C:\Anaconda\lib
    libraries lapack_atlas not found in C:\Anaconda\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\Anaconda\libs
    libraries lapack_atlas not found in C:\Anaconda\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1552:
UserWarning
:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  lapack_info:
    libraries lapack not found in ['C:\\Anaconda\\lib', 'C:\\',
'C:\\Anaconda\\l
ibs']
    NOT AVAILABLE

  C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1563:
UserWarning
:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    warnings.warn(LapackNotFoundError.__doc__)
  lapack_src_info:
    NOT AVAILABLE

  C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1566:
UserWarning
:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    warnings.warn(LapackSrcNotFoundError.__doc__)
    NOT AVAILABLE

  Running from scipy source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py", l
ine 265, in <module>
      setup_package()
    File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py", l
ine 262, in setup_package
      setup(**metadata)
    File "C:\Anaconda\lib\site-packages\numpy\distutils\core.py", line 135,
in s
etup
      config = configuration()
    File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py", l
ine 182, in configuration
      config.add_subpackage('scipy')
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
1002
, in add_subpackage
      caller_level = 2)
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
971,
 in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
908,
 in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
1002
, in add_subpackage
      caller_level = 2)
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
971,
 in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py", line
908,
 in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
Successfully built keras
Failed to build scipy
Installing collected packages: keras, scipy
  Found existing installation: Keras 0.3.1
    Uninstalling Keras-0.3.1:
      Successfully uninstalled Keras-0.3.1
  Found existing installation: scipy 0.14.0
    DEPRECATION: Uninstalling a distutils installed project (scipy) has
been dep
recated and will be removed in a future version. This is due to the fact
that un
installing a distutils project will only partially uninstall the project.
    Uninstalling scipy-0.14.0:
      Successfully uninstalled scipy-0.14.0
  Running setup.py install for scipy ... error
    Complete output from command C:\Anaconda\python.exe -u -c "import
setuptools
,
tokenize;__file__='c:\\users\\sander\\appdata\\local\\temp\\pip-build-biafff\\
scipy\\setup.py';exec(compile(getattr(tokenize, 'open',
open)(__file__).read().r
eplace('\r\n', '\n'), __file__, 'exec'))" install --record
c:\users\sander\appda
ta\local\temp\pip-49mkul-record\install-record.txt
--single-version-externally-m
anaged --compile:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Anaconda\\lib', 'C:\\',
'C:\\Anacond
a\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
    C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:635:
UserWarnin
g: Specified path C:\aroot\stage\Library\lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:635:
UserWarnin
g: Specified path C:\aroot\stage\Library\include is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
      libraries mkl_core_dll,mkl_intel_lp64_dll,mkl_intel_thread_dll not
found i
n []
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in C:\Anaconda\lib
      libraries lapack_atlas not found in C:\Anaconda\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\Anaconda\libs
      libraries lapack_atlas not found in C:\Anaconda\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in C:\Anaconda\lib
      libraries lapack_atlas not found in C:\Anaconda\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\Anaconda\libs
      libraries lapack_atlas not found in C:\Anaconda\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda\lib
      libraries lapack_atlas not found in C:\Anaconda\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\Anaconda\libs
      libraries lapack_atlas not found in C:\Anaconda\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in C:\Anaconda\lib
      libraries lapack_atlas not found in C:\Anaconda\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\Anaconda\libs
      libraries lapack_atlas not found in C:\Anaconda\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1552:
UserWarni
ng:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    lapack_info:
      libraries lapack not found in ['C:\\Anaconda\\lib', 'C:\\',
'C:\\Anaconda\
\libs']
      NOT AVAILABLE

    C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1563:
UserWarni
ng:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    lapack_src_info:
      NOT AVAILABLE

    C:\Anaconda\lib\site-packages\numpy\distutils\system_info.py:1566:
UserWarni
ng:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py",
 line 265, in <module>
        setup_package()
      File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py",
 line 262, in setup_package
        setup(**metadata)
      File "C:\Anaconda\lib\site-packages\numpy\distutils\core.py", line
135, in
 setup
        config = configuration()
      File
"c:\users\sander\appdata\local\temp\pip-build-biafff\scipy\setup.py",
 line 182, in configuration
        config.add_subpackage('scipy')
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 10
02, in add_subpackage
        caller_level = 2)
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 97
1, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 90
8, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 10
02, in add_subpackage
        caller_level = 2)
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 97
1, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Anaconda\lib\site-packages\numpy\distutils\misc_util.py",
line 90
8, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources
found

    ----------------------------------------
  Rolling back uninstall of scipy
Command "C:\Anaconda\python.exe -u -c "import setuptools,
tokenize;__file__='c:\
\users\\sander\\appdata\\local\\temp\\pip-build-biafff\\scipy\\setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
'\n'), __
file__, 'exec'))" install --record
c:\users\sander\appdata\local\temp\pip-49mkul
-record\install-record.txt --single-version-externally-managed --compile"
failed
 with error code 1 in
c:\users\sander\appdata\local\temp\pip-build-biafff\scipy
You are using pip version 8.0.2, however version 8.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.

C:\Users\Sander>

**Comment by farizrahman4u** [comment]
After cloning Keras, did you run setup.py?

**Comment by Sandy4321** [comment]
Fariz ,
thank you very much for answer
do you mean
keras-master\setup.py


I am afraid to install re install new packages , since I am beginner

and it is very difficult to make it right on my pc windows computer
it took me al lot of efforts to install fresh version of  theano

and in this file I see

      install_requires=['theano', 'pyyaml', 'six'],
      extras_require={
          'h5py': ['h5py'],

may I run it without theano upgrade ?
to have this your code running
now I have
theano.__version__
'0.8.0.dev0.dev-b2362664ccd92adcddbac3ed0d8c456d2b519006'


Regards
Sander

**Comment by farizrahman4u** [comment]
```shell
sudo pip install git+git://github.com/Theano/Theano.git
git clone http://www.github.com/fchollet/keras.git
cd keras
sudo python setup.py install
```

See http://keras.io/#installation

**Comment by Sandy4321** [comment]
sudo python setup.py install

but I use windows pc??

may I use

pip setup.py install

but remove manually from

setup.py theano update

**Comment by farizrahman4u** [comment]
If on windows, just drop the sudo.

**Comment by Sandy4321** [comment]
But I do not want reinstall Theano,
So may I manually remove it from setup

**Comment by farizrahman4u** [comment]
Just type the commands I commented above without sudo. Or just see "Installation" in the docs. If you don't want to reinstall theano, omit the command for that.

**Comment by Sandy4321** [comment]
ok
1
so I changed set up and run and it is the massage
usage: setup_changed_wo_theano_update.py [global_opts] cmd1 [cmd1_opts]
[cmd2 [cmd2_opts] ...]
   or: setup_changed_wo_theano_update.py --help [cmd1 cmd2 ...]
   or: setup_changed_wo_theano_update.py --help-commands
   or: setup_changed_wo_theano_update.py cmd --help

error: no commands supplied

2

I updated all needed packages manually
C:\Users\Sander>conda install  h5py
Fetching package metadata: ....
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
h5py                      2.5.0               np110py27_4

C:\Users\Sander>pip install --upgrade six
Requirement already up-to-date: six in c:\anaconda\lib\site-packages

C:\Users\Sander>pip install --upgrade pyyaml
Requirement already up-to-date: pyyaml in c:\anaconda\lib\site-packages

C:\Users\Sander>


3

but still have this error

File "C:\Sander\my_code\keras-master_Mar11\examples\imdb_lstm.py", line 49,
in <module>
  model.add(Embedding(max_features, 128, input_length=maxlen, dropout=0.5))
File "C:\Anaconda\Lib\site-packages\keras\layers\embeddings.py", line 68,
in __init__
  super(Embedding, self).__init__(**kwargs)
File "C:\Anaconda\Lib\site-packages\keras\layers\core.py", line 47, in
__init__
  assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' +
kwarg

AssertionError: Keyword argument not understood: dropout



4
pls pay your attention that problem in is in keras File
"C:\Anaconda\Lib\site-packages\keras\layers\core.py", line 47

variable is
allowed_kwargs
set(['batch_input_shape', 'cache_enabled', 'input_shape', 'name',
'trainable'])
when call is
kwarg
'dropout'

error happen in this code

        allowed_kwargs = {'input_shape',
                          'trainable',
                          'batch_input_shape',
                          'cache_enabled',
                          'name'}
        for kwarg in kwargs:
            assert kwarg in allowed_kwargs, 'Keyword argument not
understood: ' + kwarg
