### ISSUE TITLE
mnist_irnn.py fails with Python 3 (Keras 0.3.2, Theano 0.8.0rc1)

### ISSUE THREAD

**Issue by pminervini** [fchollet/keras#1978]
``` bash
keras/examples$ python3 mnist_irnn.py 
Using Theano backend.
X_train shape: (60000, 784, 1)
60000 train samples
10000 test samples
Evaluate IRNN...
Traceback (most recent call last):
  File "mnist_irnn.py", line 59, in <module>
    activation='relu', input_shape=X_train.shape[1:]))
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/recurrent.py", line 257, in __init__
    super(SimpleRNN, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/recurrent.py", line 132, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 60, in __init__
    self.set_input_shape((None,) + tuple(kwargs['input_shape']))
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 223, in set_input_shape
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/recurrent.py", line 270, in build
    name='{}_W'.format(self.name))
TypeError: <lambda>() got an unexpected keyword argument 'name'
```

**Comment by grahamannett** [comment]
Yeah, think this may be related to my issue as well (but uncertain).  When building models, using tensorflow doesn't seem to work if the input is a 1D array and I either get the 
> got an unexpected keyword argument 'name'

error or (for instance if I use one of the examples "python3 keras/examples/addition_rnn.py")
> TypeError: expected bytes, str found

when using Tensorflow but this error doesn't occur when using Theano

**Comment by grahamannett** [comment]
Seems to be fixed for me using the latest keras

**Comment by jk123vip** [comment]
Yeah, same error, still don't know how to fix it and ... I'm going crazy.

Win10 x64, Keras 0.3.3, Theano 0.8.0, Anaconda

The problem is that it works fine on Ubuntu. What's wrong with Windows?

**Comment by jk123vip** [comment]
Finally! I know what's going on...
In fact, the error occurred in this part of code
`model.add(SimpleRNN(output_dim=hidden_units,
                    init=lambda shape: normal(shape, scale=0.001),
                    inner_init=lambda shape: identity(shape, scale=1.0),
                    activation='relu', input_shape=X_train.shape[1:]))`
You can use the default initialize functions written in the [initializations.py](https://github.com/fchollet/keras/blob/master/keras/initializations.py)  instead of using the lambda expressions.
Like this
`model.add(SimpleRNN(output_dim=output_dim,
                    init='normal',                         # lambda shape: normal(shape, scale=0.001),
                    inner_init='identity',               # lambda shape: identity(shape, scale=1.0), 
                    activation='relu',
                    input_shape=X_train.shape[1:]))`
Well, If you really want to change the initialize functions' parameters, just set them in you local initializations.py source code. :)
Well, If you really want to change the initialize functions' parameters, just manually set them in you local source code initializations.py. :)
Yeah, I know, this is definitely not a beautiful solution, but it seems to be my only solution.
So, have fun! And Excuse my poor English, please.
