### ISSUE TITLE
CPU Error causing machine to shut down

### ISSUE THREAD

**Issue by bkj** [fchollet/keras#1990]
Has anyone else ever had their machine throw a CPU error and shut off while fitting a model on the GPU?

This has happened to me ~10 times, both on my Macbook Pro (GeForce GT 750M) and on a Dell server (Tesla M2070-Q).

**Comment by nouiz** [comment]
Hardware proplem or overheat could cause that. On the server, bad power
supply can cause that. We had "certified" workstation do that due to bad
power supply.

Can you lower the bach-size significatively? it would be less efficient so,
would heat less. Try on a 3rd computer with different configurartion?

**Comment by bkj** [comment]
This was more than likely due to overheating.
