### ISSUE TITLE
Implement stack-based RNN layers

### ISSUE THREAD

**Issue by ihodes** [fchollet/keras#206]
Cf. http://arxiv.org/abs/1506.02516

**Comment by fchollet** [comment]
I was precisely reading that paper. It is very interesting indeed.

It sounds like it shouldn't be too difficult to reproduce in Keras, however I have no time for this. Want to give it a shot?

**Comment by ihodes** [comment]
I would like to! We'll see if that translates into actually giving it one :) 

Any high-level pointers with respect to implementing them in Keras, for posterity?

**Comment by fchollet** [comment]
It would quite similar to the existing layers in `layers/recurrent.py`. Instead of a single `step` function you'd have 3 helper functions, each for one of the 3 equations of paragraph 3.1 in the paper (separation is cleaner).

You maintain a stack matrix (for performance reasons you might want to have it be of fixed-size, with a separate integer parameter indicating the position of the "latest" vector in the matrix). Iterating over the matrix would be done with Theano `scan`.
