### ISSUE TITLE
SequencialModel() will deal with the batch-left data, however, the GraphModel() does not?

### ISSUE THREAD

**Issue by gmyofustc** [fchollet/keras#2222]
Currently, I'm trying to use Graph Model for my experiment.
So, firstly, I just rewrite the code in [/keras/example/mnist_cnn.py](https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py), and replace the Sequential Model with Graph Model

in mnist dataset, the **X_train** has **50000** samples, and the batch size is set **128**, the program goes well until it gets the **49920th** sample(which is exactly 390 batches), the batch-left data has **80** samples, which is not the same as batch size(128), and the program stopped, gives me an error.

I change the batch size to 100, it will perform well.

I set the batch size to 128, and use SequencialModel, it also goes well.

So, I'm not sure whether the Graph Model can deal with the batch-left data? If it supports, how can I use it?

**Comment by philipperemy** [comment]
You batch size must be a multiple of your samples count. 50000 / 128 is not an integer. That's why you have this error. The fact that the SequentialModel handles the batch-left data is fortuitous. 

I don't have a clear explanation why the Graph fails here but I can tell that it's not a good practice to have batch-left data.

**Comment by gmyofustc** [comment]
@philipperemy  Thanks for your reply. I think I should drop the batch-left data of X_train manually before I feed it into the network.
