### ISSUE TITLE
Model.fit may cause an error

### ISSUE THREAD

**Issue by OlafLee** [fchollet/keras#226]
If the input is a list and the parameter of model.fit validation_split is active, then  standardize_X(X) will be called and it return X itself and it is expected to have a "shape" like (1, n_samples, n_features), but users will provide it like (n_samples, n_features) list.

**Comment by fchollet** [comment]
I don't get it. Example please?

**Comment by CrazymageLee** [comment]
OK. if X_train = numpy.array([[1,3,4],[2,5,6]]) then model.fit(X_train, y_train, nb_epoch=200,validation_split=0.03, batch_size=50) works fine, because after standardize_X((X_train) it will become [array([[1,3,4],[2,5,6]]) ] , so slice_X works fine. But if X_train = [[1,3,4],[2,5,6]], then after standardize_X((X_train) it is still [[1,3,4],[2,5,6]], then there is a error in slice_X for it assumes X is a 3 rank tensor.

**Comment by fchollet** [comment]
Keras is just not supposed to work with list inputs. It expects numpy arrays as inputs.
