### ISSUE TITLE
One Hot Encoding giving same number for different words

### ISSUE THREAD

**Issue by bhaveshoswal** [fchollet/keras#2294]
**Why I am getting same results for different words?**

```
import keras
keras.__version__
'1.0.0'
import theano 
theano.__version__
'0.8.1'

from keras.preprocessing.text import one_hot
one_hot('START', 43)
[26]
one_hot('children', 43)
[26]
```

**Comment by LiuJinxue** [comment]
accoding to the document,
"Return: List of integers in [1, n]. Each integer encodes a word (**unicity non-guaranteed**)."

may be it is better to preprocess the text by ourself

**Comment by codekansas** [comment]
It does one-hot encoding by hashing, so if you want true one-hot encoding it is better to fit on some dictionary of words using the `Tokenizer`.

**Comment by sallamander** [comment]
@codekansas Is there a method directly on `Tokenizer` that does this, or are you just saying that we should get back the  `word_index` from `Tokenizer` after fitting on it and then do it ourselves? I've done it in the past using the `word_index`, but am curious if there was a direct way with the `Tokenizer` that I've missed.

**Comment by talpay** [comment]
The one_hot function needs a rework. It's a hash function and not a one-hot mapping by any definition that I have ever encountered:
```
def one_hot(text, n, filters=base_filter(), lower=True, split=" "):
    seq = text_to_word_sequence(text, filters=filters, lower=lower, split=split)
    return [(abs(hash(w)) % (n - 1) + 1) for w in seq]
```

On top of that, it's buggy and/or has some weird behavior: 

- You have hash collisions (no unicity) once n is larger than the number of words.
- In fact, it doesn't look at the number of words. It looks at the number of characters even though the call to text_to_word_sequence suggests otherwise.
- Adding +1 at the end ensures that nothing will be mapped to 0 (why?). This results in the bug that passing  n as the sequence length will actually internally be processed as n-1, causing collisions in this case.
- abs(hash()) is obviously causing additional collisions.
