### ISSUE TITLE
stateful RNN when input length changes

### ISSUE THREAD

**Issue by BaldwinTheThird** [fchollet/keras#2328]
This relates to issues #1125 #1130  and #2030; I am also using batch_input_size = (batch_size, input_length, input_dim) but the issue is that input_length changes between training set and validation set. The reason for this is the type of data I have. I basically have 1 long very high dimensional time series (weather data of rougly 5000 sensors => input_dim=5000). This time series covers several years (=1 millions time points), so I split it up into 80% training data; 10% validation data and 10% test data and feed the training data as one batch (batch_size=1) to the RNN. Hence my input_length is different for training (800k) and validation/test(100k each). The error I get seems to indicate that this is the issue:

> ValueError: total size of new array must be unchanged

Is it possible to use stateful RNN in my case? I need it because after training I would like to generate weather data step by step feeding outputs of the RNN back as inputs and the earlier solution of recalculating the whole history of predictions each time is too inefficient.

**Comment by carlthome** [comment]
Have you considered padding the validation time series such that it is of equal length to your training data? Basically adding a zero value per sensor for every non-existing timestep in your validation data.

Or perhaps the Masking layer could work? http://keras.io/layers/core/#masking

**Comment by BaldwinTheThird** [comment]
Wouldn't I still have to feed in individual time steps into the model at some point (the last input) to get new outputs? In this case my input will again have a wrong dimension "input_length". 

So to take a step back... how could this ever work with any kind of model? We want to generate predictions for t+1 using predictions from t as input while retaining the activations present in t (instead of resetting them). In any model, during training my inputs will always have several time steps that the RNN goes trough, so I will have to set input_length to something greater than 1, but then to solve the above problem of generating data step by step it has to be equal to one. Am I missing something here? Can somebody point me to code which implements this using stateful RNNs?

**Comment by carlthome** [comment]
I'm a bit shaky on the details still, so take the following with a grain of salt... :smiley: 

If you look at the [provided stateful RNN example in the repo](https://github.com/fchollet/keras/blob/master/examples/stateful_lstm.py) you'll see that since the LSTM units are stateful the model can be fed data just one timestep at a time during training (and predictions too, of course). I propose you try this. Consider running the example and playing around with it, and slowly change the source code to fit your use case, step-by-step.

Note that while you'll be able to maintain states over several minibatches there will be no [BPTT](https://en.wikipedia.org/wiki/Backpropagation_through_time) longer back in time than the amount of states you actually maintain in your model (i.e. the number of RNN units), since they're effectively overwritten when fed new batches.

Your batch size should be 1 in your case, I assume? Since you said you have just one time series, I mean. Then unfortunately training will be very slow, since it's not possible to parallelize computation __within__ a single sequence, since the current states depend on both their ancestors and successors. If you were able to naturally segment your time series into several shorter sequences with the data still making sense (meaning, every start and end point for each subsequence shouldn't depend on the actual future and past) then you could gain the benefit of GPU parallelization. As an example, if your time series was audio samples, a natural split point could maybe be during a long silence. Or for a video sequence perhaps you could split it into sequences when there's a lot of black frames. 

Finally, a subtle point with the repo's stateful example is that its batch size can only be 25 because the period of the cosine is precisely that. That's a bit exotic, and worth thinking about because it probably doesn't apply to most real-world data.

**Comment by BaldwinTheThird** [comment]
I'm completely confused now. The example in the repo does't make sense to me. A one dimensional time series is generated as input, call it (x0,x1,..,xn). Then output is generated which is the same series just shifted (x1,x2,..). The goal is to predict the output from the input "predict the next value". So far so good. However I suspect this is not really processed as a time series, it is actually processed as a bunch of input output samples (x0,x1), (x1,x2), (x2,x3) etc and there is no learning going on through time just cross-sectionally (all that is used to predict the output is the input in the same tuple, not anything in previous tuples). 
Here is why I think this is the case and please correct me if I am wrong: normally when learning a recurrent network we have input in form of a 3D tensor (#samples, #timesteps, input_dim), when processing this input in batches, it would take a chunk of that, i.e. a smaller 3D tensor (batch_size,#timesteps,input_dim) where batch_size is some fraction of #samples. It would then take this batch and process all samples in timestep by timestep. Assume some initial hidden state it would take the first time slice of that batch, feed it as input to the hidden layer along with the initial hidden state and compute output for this time step; it then feeds the second time slice along with the previous hidden state as input to the current hidden state and generates output etc. until we have processed the last time slice (this could be called a forward pass through the RNN). Now errors can be calculated at every time step and backpropagated in a backward pass. They can only be backpropagated to the first time step. The example in the repo has effectively removed the time dimension so how could that work? I suspect that the final plots only look good because this model can be "learned" with the tuples already. If you simply always predicted output = input and plot it it will look like the original series. Given that there are so many datapoints it will not be noticeable.

**Comment by carlthome** [comment]
No, that is not the case. You are right in that a single sample is of the form (x0, x1) but since the LSTM units start with the same states for (x1, x2) the temporal dependencies can be learned over the entire time series. Although yes, the error cannot be propagated backwards further in time than the number of states you maintain in your model.

Again, one subtle weirdness is the fact that the model actually learns from 25 sequences at once, since the batch size is 25, which only works in this particular case because the time series is periodic with a period of precisely 25. If the time series was not periodic it would be a bit like shuffling every 25 data points, which probably would not turn out very good for the predictions (although I guess it could still work if the function was sampled with a high enough resolution).

**Comment by carlthome** [comment]
Actually come to think of it, if one timestep is shown to the model at a time (timesteps=1) as in the example, it seems like this is how the network sees the samples:

![rnn-bptt1oneatatime](https://cloud.githubusercontent.com/assets/1595907/14604419/d92432ec-0573-11e6-978d-015658d697da.png)

And if that's the case I'd expect future samples to be shown to past states, improperly. @fchollet, are we being noobs?

**Comment by pikeas** [comment]
I'm interested in doing something very similar, and I'm completely confused by the stateful RNN documentation and examples.

**Comment by khaotik** [comment]
I'm having the same issue.
While it's possible to train RNN with 1-time-step, I doubt this works generally, without causing gradient bias or temporal interference.
It would be nice if there's an online optimizer designed specially for 1-time-step RNNs. Methods like [NoBackTrack](http://arxiv.org/abs/1507.07680v2) could be a promising choice.

**Comment by philipperemy** [comment]
@pikeas Have a look at this : http://philipperemy.github.io/keras-stateful-lstm/
It might help you understand how statefulness works
