### ISSUE TITLE
How to implement a new train_function by inputting additional data to control the input gate of LSTM?

### ISSUE THREAD

**Issue by jackyetz** [fchollet/keras#2358]
Hi all,
I have a list of words. If any input single word is one of the list, the input gate will be modified.
Then how to modify the train_function at engine\training.py\Class model\def _make_train_function to achieve that?

**Comment by carlthome** [comment]
Modify input gates how? Could you specify your use case a bit more?

**Comment by jackyetz** [comment]
For example, I have a list of words, it is [371, 77, 66], and a sentence as the input, it is  [589,9991,776,371,78,99], where the integer numbers inside the list and the input sentence are the index of certain words in a vocabulary dictionary. 
U can see, the list and the input sentence have the same word "371". At the timestep 4, the word "371" is put into the LSTM model, and I wanna change the value of the variable for the input gate. Can I and how?

**Comment by carlthome** [comment]
You mean you want to be able to manually override the model's learned weight for the input gate at a given time step when being shown a sequence, but the input's weight, output gate's weight and forget gate's weight should still be their learned current values?

I don't believe this is possible because you probably want to learn batches of sequences at once (for computational efficiency) and you would not expect the special words with fixed input gate weights to show up at the same time steps throughout all your sequences, I assume?

If you were okay with feeding the model a single sequence at a time (batch_size=1), then you could consider splitting the sequence into subsequences at the special words and manually resetting the weights between `model.fit()` calls. The weights are simple values in the Python object `model` that you can access at will (look into the layer objects).

**Comment by jackyetz** [comment]
Thank u, carlthome. U help me a lot. I'd like to think this matter over.
