### ISSUE TITLE
[feature] validation-only metrics

### ISSUE THREAD

**Issue by cmyr** [fchollet/keras#2448]
I've been playing around with some new metrics, some of which are informative but computationally inefficient. It would be useful if I could specify metrics that would only be used during the validation phase.

In the naive case this might be as simple as passing a `validation_metrics` list to `model.compile`, and including these metrics in `_make_test_function`. @fchollet, is this a feature you would consider merging? Should I take a stab?

**Comment by fchollet** [comment]
> I've been playing around with some new metrics, some of which are
informative but computationally inefficient. It would be useful if I could
specify metrics that would only be used during the validation phase.

The canonical way to do this would be via a callback, or simply outside of
the `fit` loop (run `predict` on some test data then run arbitrary metrics
on the predictions).

I don't think this would be a common enough use case to justify making the
API more complicated to cover it, especially since it can already be done
rather easily with the current API.

**Comment by cmyr** [comment]
okay, thanks for the input.
