### ISSUE TITLE
multi core support in keras

### ISSUE THREAD

**Issue by suraj-deshmukh** [fchollet/keras#2516]
I have a access to a cluster having multiple cores and I want to run my keras model on limited number of cores of that cluster. Is there any way to use fix number of cores in a cluster. 

I have looked in to [multi core support for theano](http://deeplearning.net/software/theano/tutorial/multi_cores.html) but in that there is no way to control number of cores except threads as per my understanding. Also does openmp uses all available cores by default because I have not found any flag in theano which can tell openmp that how many cores to use

Thank you

**Comment by sschnug** [comment]
Maybe [this](http://serverfault.com/questions/32322/is-it-possible-to-limit-a-linux-process-so-that-it-can-only-run-on-a-particular) might help.
But i don't really understand your setting. I would always prefer limiting the threads.

If you run 3 threads on 4 cores, all of the cores will be used (and i'm sure there is a good reason for this), but the load will be distributed.

If you are only concerned about not exploiting the whole cluster because of other users, the limiting of threads is enough (and every well-managed cluster has some scheduling tool which will enforce these limits anyway; especially memory).

**Comment by fchollet** [comment]
This is not even a Theano issue; you probably don't have a proper BLAS
installed. Theano just delegates to the BLAS.
