### ISSUE TITLE
Unsupervised Loss

### ISSUE THREAD

**Issue by braingineer** [fchollet/keras#2517]
Currently, I'm running some loss functions by ignoring the y_pred and y_true inputs.  But it'd be nice to be able to define some unsupervised losses. 

For example, [cross covariance loss](http://arxiv.org/abs/1412.6583v3)

or TD loss for RL applications

``` python
### SARSA TD
def TD(reward_t, gamma, Q_tp1,  Q_t):
    td_error = reward_t + gamma*Q_tp1 - Q_t
    def loss(*args):
        return K.mean(K.square(td_error))
    return loss 
```

There seems to be a couple different ways one could handle this. One is just like I've done.  

Some initial ideas I have would be to make decisions about the relationship between the [numbers of outputs vs the number of losses](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L482) or whether to just mark certain outputs as not needing an input, [which could be done here](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L569), and then ignored in the following loop.

**Comment by braingineer** [comment]
this is fixed in keras 2. 
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L722

**Comment by vodp** [comment]
I have a similar concern, says I want to minimize a loss computed sorely based on inputs X's and not their groundtruth label Y. For instance the maximum mean discrepancy (MMD) between two batches X and Z forwarded by two separate convnets. This the top layer MMD should get two inputs X and Z and outputs a scalar tensor. How should I define the loss wrt to the new changes in Keras 2?

**Comment by braingineer** [comment]
there may be a couple different ways.

the one that comes first to mind because I just did something similar: 

1. write a layer which computes the thing you want to compute.  so it'll take as input X and Z and then compute your MMD
2. write an activity regularizer (see the documentation or look at regularizers.py) and use it on your layer (see the `Dense` layer code for how this would be used)
3. Have the value be output, but pass no data for it (corresponds to my answer above)

**Comment by vodp** [comment]
Thanks for your instant reply. It turns out that I took the first approach, using Lambda to write a small layer that takes two inputs and outputs a float:
`mmd_net = Lambda(mmd_discriminator, name='mmd')([src_net, dst_net])`
where the callback `mmd_discriminator` is defined as:

```
def mmd_discriminator(args):
    
    bandwidths = [2.0, 5.0, 10.0, 20.0, 40.0, 80.0]
    src, dst = args
    dist = mix_rbf_mmd2(src, dst, sigmas=bandwidths)
    return K.sqrt(dist)
```
My problem is that I don't know to feed it into the compile function. What I am doing now is 
```
model = Model(inputs=[src_input, dst_input], outputs=mmd_net)
model.compile(loss={'mmd': mmd_metric}, optimizer=solver,..)
```
Here I assume mmd_discriminator returns the value that is stored in `y_pred`
```
def mmd_metric(y_pred, y_true):
    
    return y_pred
```
This way I got error `TypeError: range() integer end argument expected, got NoneType.`

**Comment by braingineer** [comment]
@vodp did you solve this?  the `ndim` argument, which comes from `K.ndim(score_array)` in that situation is somehow None.   My typical problem solving strategy starts with running the training script with 
`python -m pdb script.py anyargs`.  If you don't know pdb, I would highly recommend reading up on it. It will make your debugging much,  much easier.    In this situation, it'll let you walk up the call stack from the TypeError, and see exactly score_array is so that you can find out why its `ndim` is `None`.

**Comment by rawmean** [comment]
@vodp  Found the solution!
I also defined a network whose output is a scale that's computed using a Lambda layer and I've encountered the same problem.
****Solution:
Let's say your custom loss function has computed the variable `loss`.  Add this line right before returning the loss.  This is needed because Keras expects the output of the network to be a tensor that has a dimension associated with sample index.
`    loss = K.expand_dims(loss, 0)
`

**Comment by rex-yue-wu** [comment]
I had encounter the same issue, i.e. failing to write an unsupervised loss without `y_true`. I find one workable solution, that is to implement this unsupervised loss as an `activity_regularizer` function. This solution works fine for me, because I also have a main supervised task besides of this unsupervised loss. However, it is still unclear for me to quickly train a network with only unsupervised losses.

**Comment by isaacgerg** [comment]
@braingineer   I read through this thread.  Its still not clear to me what to do for an unsupervised loss. Can you post an example or elaborte on what you have?
