### ISSUE TITLE
How to multiply Tensor with a vector

### ISSUE THREAD

**Issue by LiuAndYang** [fchollet/keras#2601]
Hi,  I am confused about a very simple operation. I have some output A of shape (None,15,200),  and the 15 is the timestep.  I have anoter vector B of shape(None, 15), each dimension of B is the weight value of the 200-D representation of each time step .  I wanted to multiply A with B, which means a weighted output of shape(None, 15, 200), how can i compute this in Keras? It is a basic operation in Keras , sorry about not knowing that.  Thx so much!

**Comment by carlthome** [comment]
Available mathematical operations are defined [here](https://github.com/fchollet/keras/tree/master/keras/backend).

I'd guess you're looking for something like this `K.dot(A, B)`. It's very much like numpy.

**Comment by amirmazaheri1990** [comment]
@carlthome Hi, Do you know if this is possible to take the output of `k.dot(A, B)` and pass it to the next layer? I believe it causes an error about the input shape for the next layer. I guess, just output of keras.layers can go to keras.layers as an input.

Does anybody know if I'm right?

**Comment by silentsnooc** [comment]
@amirmazaheri1990 This sound similar to what I want to do (see [here](http://stackoverflow.com/questions/42297359/typeerror-output-tensors-to-a-model-must-be-keras-tensors)). Were you able to pass the result into the next layer?

**Comment by George-Zhu** [comment]
@LiuAndYang you can directly use the keras Multiply layer to do this (15,200)  * (15, 1) -> (15, 200), because keras Multiply layer use straightforward "*" to do muliplication just like tf.multiply, and tf.multiply supports broadcasting like numpy.
Refrence:
https://github.com/fchollet/keras/blob/master/keras/layers/merge.py
https://github.com/fchollet/kerAas/issues/2601
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
