### ISSUE TITLE
Loading Lambda function which calls other functions

### ISSUE THREAD

**Issue by wddabc** [fchollet/keras#2637]
I think this is related to #1487 I guess. Here is an sample code

```
def b(x):
    return x
def a(x):
    return b(x)
c=Lambda(a)(x) 
```

When load such and architecture from a .json or .yml file and make prediction. It returns 

> global name 'b' is not defined

I'm guessing the serialization ignores b. If I define:

```
def a(x):
    def b(x):
         return x
    return b(x)
```

It works correctly. So the lambda should be self-contained. One solution for this is defining b from another file (say util.py) and do:

```
def a(x):
    from util import b
    return b(x)
```

What if I need to define b() locally (a and b are in the same .py file)? Are there any ways to do self import? Seems this question is not related to keras, but might be useful if the lambda function are complex.

**Comment by braingineer** [comment]
> seems this question is not related to keras

I mostly agree.  I do think it has implications on some keras things, but on the whole 'saving' functions is not a trivial task.  Especially in Python.

But in general, I think it's a very bad practice to rely on Lambda functions and another anonymous structures to parameterize your model.  While they can be successfully saved as JSON and other things, if you're going to start wrapping complex layers inside complex layers, it might be worth it to invest in some self-built layers.  That way, you parameterize your layers with basic variable types so that you can be sure it won't go awry.

**Comment by wddabc** [comment]
Thanks! Yes, you are right! We should make the best use of layers - otherwise there is no difference from using Theano/TF directly. I was just wondering whether there should be a note about the usage of the Lambda functions. Especially for some users in transition from Theano to Keras that want to take the advantage from both sides :)
