### ISSUE TITLE
Siamese network with Keras

### ISSUE THREAD

**Issue by sanjeevmk** [fchollet/keras#2651]
Hi, I want to implement a network of a Siamese network-like structure, as depicted below. I saw this closed issue here : [https://github.com/fchollet/keras/pull/928](here) , but it seems those commits were not merged, so there is no inbuilt support in Keras to implement a siamese network.

Is it possible to do this in some other way?

![siamese](https://cloud.githubusercontent.com/assets/1523786/15087457/77a5944c-1406-11e6-81ee-54fcd72a6d47.png)

**Comment by GregorySenay** [comment]
You can look here: https://github.com/fchollet/keras/blob/master/examples/mnist_siamese_graph.py

**Comment by fchollet** [comment]
Yes, there's an entire tutorial section on it in the functional API guide, plus an example script available.

**Comment by giladdiv** [comment]
I want to implement Siamese network on the base of https://github.com/yhenon/keras-frcnn
the problem is that he has Models and all layers have names and when i try to use the same network for two different inputs it say that "the name conv1 is used more than once" (in the example the layers don't have names but here i need the name for loading the weights)
what should I do?

**Comment by harish-git08** [comment]
Hi , 

I was looking for the page link given above , but couldnt find the page.I got error page displaying Page not found. Please find me a resource
