### ISSUE TITLE
Bug or misunderstanding in keras  code example mnist_siamese_graph.py

### ISSUE THREAD

**Issue by cxfneo** [fchollet/keras#2665]
Hi  
   I am learning the keras code example mnist_siamese_graph.py. The Lambda layer in this example accepts two inputs from below layers, so I think  eucl_dist_output_shape function would also process a list of two corresponding input shapes.  Assume  input "processed_a" and processed_b have  shapes with (nsamples,dim)., then the input shape will be like [(nsamples,dim),(nsamples,dim)]
According to function method "eucl_dist_output_shape(shapes)", it will give a result (nsampels,dim). But actually, the result of eucl_dist is (nsamples,1). 
I am not sure whether I have a misunderstanding about Lambda layer's input.

---

1.distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])
2.def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return shape1
3.def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))

**Comment by braingineer** [comment]
try and format your code next time
```python
distance = Lambda(euclidean_distance, 
                  output_shape=eucl_dist_output_shape)([processed_a, processed_b])

def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return shape1

def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))
```

anyway, the shape function returns an estimate of the shape. it's to let keras know about things so it process stuff.  If the shape estimate is mistaken, then it's mistaken.  it doesn't enforce the output.  This is actually a source of bugs sometimes for me: I will think the shapes are working one way, but a mysterious shape change will occur and I will have to track it down.  

the `euclidean_distance` function returns as you'd expect: squares the differences, sums over the last dimension.  The keepdims means that instead of being `(nsamples,)` when it's finished, it will be `(nsamples,1)`.

**Comment by cxfneo** [comment]
OK  .  thanks you for your reply.
BTW, how to format code in github, I am an initial learner of github. 
thanks again
