### ISSUE TITLE
Conversion of X to list does not play well with alternative data structures that implement the ndarray interface

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#271]
In model.py, `standardize_X` converts X into a list for some reason I was not able to find in the code. Since all that should be needed is to get slices from X, why is that necessary? If one implements an alternative data structure that has the same API as `numpy.ndarray`, nothing should break. `slice_X`, for example, supports both list and non-list arguments, as long as they support slicing. `standardize_X` currently breaks the `HDF5Dataset` interface (and some of my personal code as well).

**Comment by fchollet** [comment]
The input to Keras models is a list of `ndarray`. The role of `standardize_X` is to turn a potential standalone `ndarray` `X` into `[X]` to become a valid input. 

The reason for this is that models can have multiple inputs, due to the Merge system. Such as `[X1, X2, X3]`...

Does this clarify the situation?

**Comment by jfsantos** [comment]
I see. That does make sense, but it seems there's something broken when using non-standard ndarrays. I'll investigate and submit a PR if that's the case. Thanks!

**Comment by jfsantos** [comment]
Turns out it was an error in my tests. Sorry for the noise!
