### ISSUE TITLE
Error when using BatchNormalization in TimeDistributed

### ISSUE THREAD

**Issue by jimfleming** [fchollet/keras#2827]
I ran into this issue when using batch normalization in a sub-model applied to a time distributed layer:

> tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'input_3' with dtype float
     [[Node: input_3 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Attached is a minimal example demonstrating the problem (the first comment on the gist has the error logs):

https://gist.github.com/jimfleming/1c15dcda3e0d05b3947ac28fc757714a

TensorFlow backend. Latest Keras as of today.

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
That's a known issue with model templating. In your case you can fix it by changing your model creation functions to *apply layers on top of existing tensors* instead of returning template models.

Something like:

```python
def InterModel(input_):
    x = Dense(10)(input_)
    x = BatchNormalization()(x)
    output = Activation('relu')(x)
    return output
```

If you want to share layers, you can reuse all layers except BatchNorm.

We will fix this in the future.

**Comment by fchollet** [comment]
I "fixed the glitch": there is no an exception when one attempts to share a BN layer across different datastreams. Making the BN layer work properly in a shared setting would just be too cumbersome and complicated.

So, when having different datastreams: either instantiate a new BN layer every time, or use BN in mode=2 (uses per-batch statistics to normalize, rather than moving averages, and thus is shareable).

**Comment by jimfleming** [comment]
Easy enough, thanks!

**Comment by abnera** [comment]
When using `BatchNormalization(mode=2)` I was able to fix problems in TimeDistributed but for some reason, I always have to set `generator(shuffle=True)` for both the validation and test evaluation/predict for the validation/test data to give any meaningful results. With shuffle=False validation/test = 1% with shuffle=True it's 70% (as expected). I believe is because mode=2 uses per-batch statistics. How to solve this? I need to set shuffle=False to match `generator.filenames` to my predictions.

**Comment by QuentinFresnel** [comment]
Same problem, and new version of keras don't accept modes :
```The `mode` argument of `BatchNormalization` no longer exists. `mode=1` and `mode=2` are no longer supported.```

I tried the sequential and functional approach, I get the same result

 https://gist.github.com/QuentinFresnel/9ed54473b87167713fcf2baa40bffe50
 
How can we use batch normalization in time distributed models ?

**Comment by redsphinx** [comment]
Same issue here as @QuentinFresnel

**Comment by rex-yue-wu** [comment]
Same issue, but solved after setting learning phase. 
```python
from keras import backend as K

K.set_learning_phase(1) 
```
See original post [here](https://stackoverflow.com/questions/42969779/keras-error-you-must-feed-a-value-for-placeholder-tensor-bidirectional-1-keras).
