### ISSUE TITLE
convolution much slower in current implementation

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#2891]
I just upgraded Keras from version 0.3.2 to the latest, then found with the newest Keras, CNN runs much slower (17s VS 180s per epoch in my code) when device = gpu.

By comparing the codes, previously I suspected ths is caused by removing of explicit usage of cudnn in the newest Keras. But after also removing explicit usage of cudnn in Keras 0.3.2, the speed is not affected (still 17s per epoch). So I believe this is caused by the newest Keras, in some other code places.

Currently I noticed the floatX of theano is not correct in the newest Keras, it always equals 'float64' even after I set the environment flag and/or set the configure file .theanorc. This problem does not exist in Keras 0.3.2

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [\* ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by daweileng** [comment]
I believe the problem rises from how Keras does its self-initilization. For the latest version, the numeric precision can only be set or modified by a file named as **keras.json** hiddenly stored under user's root folder. Set environment flags as specified in theano documentation is invalid when keras is imported. So  even after I set the environment flag to 'float32', keras will reset it to 'float64', and that's why the convolution is slow.

I'd call this a bug by designing. Maybe keras should provide an explicit API to set/change numeric precision.

**Comment by jonilaserson** [comment]
I had a similar issue to yours. After investigation, the reason was change
#1388 that was made to border_mode="same" (a parameter of conv2d) that made
everything slower. The slow down was only relevant to runs with a conv2d
with border_mode="same" on cudnn.

**Comment by jonilaserson** [comment]
Also, if you are using the newest Theano, make sure you are also using the
newest CUDNN. (currently cudnn5).

**Comment by ghs2015** [comment]
@jonilaserson Thanks for your answer. The program is much faster now.
