### ISSUE TITLE
Maximum Recursion Depth error in Model.fit

### ISSUE THREAD

**Issue by nitish11** [fchollet/keras#2931]
I am running a deep net model on Keras code. The training model was running perfectly fne on image size 76*76, but it not working on image dimension 128*128.

I got the below error :

  <i>File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 4262, in get_num_denum
    pairs = [self.get_num_denum(input2) for input2 in parent.inputs]
RuntimeError: maximum recursion depth exceeded

if isinstance(c, graph.Constant) and (len(c.clients) <= 1):
RuntimeError: ('maximum recursion depth exceeded while calling a Python object', 'Please, report this to theano-dev mailing list. As a temporary work around, you can raise Python stack limit with: import sys; sys.setrecursionlimit(10000)')</i>

I am using a GPU machine (NVIDIA GF110GL [Tesla M2075]) with fairly good configuration. I don't want to proceed with temporary work-around because in that case, the code is getting stuck before training. Kindly suggest some better way to handle this issue.

**Comment by nitish11** [comment]
The Keras build used is from the below URL : https://github.com/fchollet/keras/tree/d6e33ce5558169de2c85bad5360609323cdc44c5

The Model architecture can be found in the below gist.

https://gist.github.com/nitish11/d1e90390a5cc203e9e7a493a9e1d85e9

**Comment by ymcui** [comment]
the error massage gives clear solution
write the following code at the beginning
```
import sys
sys.setrecursionlimit(10000)
```

**Comment by nitish11** [comment]
Hi @ymcui ,
thanks for the reply. 

I have already tried this approach and I have already mentioned the code is getting stuck in training. 
It's taking more time (waited for 30 minutes)  to start the training.

**Comment by nouiz** [comment]
The long traning time is due to the size of the graph. You can use the Theano flag optimizer=fast_compile to get something faster, but would slow down the run time.

**Comment by nitish11** [comment]
I used following command to run the training and waited for an hour, the training is not getting started.

<i>THEANO_FLAGS=mode=FAST_RUN,optimizer=fast_compile,device=gpu,floatX=float32  python model_training.py </i>

**Comment by nouiz** [comment]
There is a new undocumented flag that can help speed up the compilation by
~5-10%:

optimizer_excluding=UnShapeOpt

We are actively working on making the optimizer in fast_compile faster. We
should have something merged next week for this in the new back-end. Follow
this PR to stay up to date: https://github.com/Theano/Theano/pull/4570/files

Another option for now is to pickle a compiled Theano function. When we
unpickle it, we skip the longer part in this case.

The first time you compile it on one computer, the compilation can be
slower due to the C compilation, but as we cache this, the recompilation
will be faster. This with the pickle should make something fast (but yes,
the pickle isn't super trivial to use)

**Comment by nitish11** [comment]
Thanks @nouiz. I will follow up the PR https://github.com/Theano/Theano/pull/4570/files
