### ISSUE TITLE
How to use the pretrained model such as imagenet-vgg-f?

### ISSUE THREAD

**Issue by willard-yuan** [fchollet/keras#30]
Hi, fchollet

I'm wondering there is possibility to use the pretrained model such as [imagenet-vgg-f](http://www.vlfeat.org/matconvnet/pretrained/) with keras?

**Comment by fchollet** [comment]
It is absolutely possible to instantiate models with pre-trained weights (by passing a "weights" argument at layer initialization, or using the set_weights/get_weights methods of layers.

However there is no existing pre-trained model for you to use at the moment. In the future, I will likely train a Keras deep convent on ImageNet and upload the resulting model somewhere, because it seems it could be useful to a lot of people. But that's not very high on my priority list.

**Comment by whjxnyzh** [comment]
@fchollet  I think one can use caffe python wapper to read caffe model, extract the weights and then give it to keras model. I am not sure if it will work...

**Comment by pranv** [comment]
I'm working on this. Caffe-Keras interaction will be ready in a couple of days.Sequential Models like VGG  were easy to convert. But the non sequential models took some time since Caffe handles it in form of blobs and it needs to be processed as a graph.




I'll finish it soon and submit it, hopefully you can use it soon.

**Comment by superhans** [comment]
Hey @pranv. Any progress on this ?

**Comment by paulogaspar** [comment]
Any progress on this?

**Comment by elbamos** [comment]
@superhans @paulogaspar  If what you want is specifically the vgg model:  https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

**Comment by willard-yuan** [comment]
@pranv Any progress on this?

**Comment by Patriciasr92** [comment]
Any progress on this?
