### ISSUE TITLE
Graph container

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#302]
Following the discussion in: https://github.com/fchollet/keras/pull/291, let's design a `Graph` container class, as well as a `Graph` model inheriting from `containers.Graph` and from `models.Model`.

Based on @pranv's initial work, here's a proposal for an API:
```python
model = Graph()

model.input(shape=(3, 32, 32), name='input1')
model.input(shape=(3, 32, 32), name='input2')
model.node(MaxPooling2D(poolsize=(2, 2)), name='base', inputs=['input1', 'input2'], merge_mode='sum'))

model.node(Convolution2D(64, 64, 1, 1), name='conv11', input='base')
model.node(Convolution2D(64, 64, 1, 1), name='conv12', input='base')
model.node(MaxPooling2D(poolsize=(3, 3)), name='pool1', input='base'))

model.node(Convolution2D(64, 64, 1, 1), name='conv21', input='base')

model.node(Convolution2D(64, 64, 3, 3), name='conv22', input='conv11')
model.node(Convolution2D(64, 64, 5, 5), name='conv23', input='conv12')
model.node(Convolution2D(64, 64, 1, 1), name='conv24', input='pool1'))

model.output(inputs=['conv21', 'conv22', 'conv23', 'conv24' ], name='output1', merge_mode='concat')
model.output(input=['conv24'], name='conv24_output')

# loss_merge can be a custom function
model.compile(loss={'output1':'mae', 'conv24_output':'mse'}, loss_merge='sum', optimizer='sgd')
model.fit(train={'input1':X1, 'input2':X2, 'output1':Y1, 'conv24_output':Y2})
```
Basic behavior:

- no merge / fork layers; every node can act as a merge over a list of inputs. Supports arguments `input` (name of layer) or `inputs` (list of names of layers).
- the fit/evaluate/etc methods interface with `models.Model`, which takes list of inputs and list of outputs. Internally the input/output dictionary are flattened in a list following the expected order.
- layer names (unique identifiers) are mandatory
- use of the same layer identifier twice results in an exception

Remarks, suggestions, and questions welcome.

**Comment by fchollet** [comment]
First amendment: since we want `Graph` to be a container, i.e. to implement a superset of the `Layer` API, `input` is already taken as a class property. 

We can use the following namespace, less elegant but more explicit;
- `add_input`
- `add_node`
- `add_output`

**Comment by fchollet** [comment]
I made a minimally viable implementation of such a container / model. It doesn't entirely respect the `Layer` API because it doesn't implement the `connect` method, and its `get_input` / `input` and `get_output` methods return lists of tensors rather than single tensors in the case of standard layers.

It's not clear if this breach of API means that `Graph` should be implemented as a `Model` only, or if the `Layer` API should be extended (to introduce support for list input/output). I'm thinking about it. 

First observation is that some refactor of `models.Model` will be in order, where quite a bit of code will be moved to `models.Sequential` (because it is not as generalizable as I first thought) while some more abstract training loop code will be added.

**Comment by fchollet** [comment]
Wisest would most likely be to implement `Graph` as a model, and reintroduce the more elegant API. I'll sleep on it.

**Comment by pranv** [comment]
I think implementing `Graph` as a model is a good idea. However, I still think having it as `Sequential` itself is a better idea. Much less to learn, maintain. Maybe we can add documentation to help with the polymorphism.

**Comment by lukedeo** [comment]
Why not have both? For beginners, `Sequential` makes things a bit more explicit and easy to understand, while advanced users can work with `Graph`.

**Comment by phreeza** [comment]
There is a pretty good implementation of a graph very similar to what we will need here: https://github.com/Debilski/mdp-toolkit/blob/master/mdp/graph/graph.py

Might be useful to have a look there for inspiration. Useful things might include cycle detection , because this needs to be a directed acyclic graph.

**Comment by pranv** [comment]
I had implemented similar functions while doing processing for Caffe Integration. Real power of them can be only be used if the `models` supports it. For Example: If a layer has 0 out-order, its an output layer

**Comment by tleeuwenburg** [comment]
To me it doesn't make any sense to have a Graph also be a Sequential. One
is about complex interconnection, the other is about stacking up a linear
flow in the data. Honestly, I have only used Sequentials in my use of the
library so I may not fully grok the architecture here. It think it's funny
having Sequential as a Layer and then again as a Model which also inherits
from Layer. I guess it's just saying that a Sequential model has the same
interface as a single layer in this case -- starts and end with a single
layer.

A Graph, I suppose, can also be a layer in the sense it has inputs and
outputs that are flat, even if the internal structure of the graph is more
complex. But is that true -- is a graph going to have just one set of
inputs which is like a layer?

I would have expected a Graph to be a Model but not a Layer.

But I really may well not understand fully what's going on here.

On 30 June 2015 at 17:38, Pranav Shyam <notifications@github.com> wrote:

> I think implementing Graph as a model is a good idea. However, I still
> think having it as Sequential itself is a better idea. Much less to
> learn, maintain. Maybe we can add documentation to help with the
> polymorphism.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/302#issuecomment-117040612>.
>



-- 
--------------------------------------------------
Tennessee Leeuwenburg
http://myownhat.blogspot.com/
"Don't believe everything you think"

**Comment by phreeza** [comment]
Maybe it would be clearer to think about `Graph`s consisting of `Node`s and `Edge`s instead of `Layer`s.

`Layer`s would then be replaced by `Node`s (though we may still alias them as such just because that is a terminology that people are used to.

A `Graph` would need the ability to impose constraints on the topology that is added, ie no cycles. A `Sequential` would then just be a `Graph` with the additional constraint that all indegrees and outdegrees must be 1 except for input and output nodes.

For people who like to think in terms of layers and 'pseudolayers' like split and merge, we could easily add special nodes that perform this function. Split for example would just be an identity node with indegree 1 and outdegree `n`.

`Graph` should probably only be concerned with topology, a `Model` would then take a `Graph` and in addition to that an optimizer, handle compilation, etc.

**Comment by pranv** [comment]
Having it as sequence simply means that the newly added layer could be connected to the previous one, without explicit mention

**Comment by fchollet** [comment]
- `Graph` cannot be the same as `Sequential`, because graphs and lists are distinct concepts in CS, with different properties and different implementations (except in some edge cases like priority queues where you implement a tree as a list for performance reasons...). `Sequential` is a list of layers, `Graph` is a graph of layers.

- On cycle checks: there are a few more constraints that we should check for, for instance all inputs should be connected to at least one output, and all outputs should be connected to at least one input. However all of this is already taken care of by the Theano compiler. We will only implement our own checks if it turns out in practice that this is a significant UX problem.

- On `Container` vs. `Model`: having thought about it, I came to the conclusion that `Graph` does indeed need to be implemented as a container. This is important for two reasons:
   - conceptual clarity. Containers are the level of abstraction that deals with topology, while models deal with optimization. We should not mix the two. Model topology should be inherited from containers.
   - expressiveness and flexibility through recursion. Currently you can use any `containers.Sequential` as a layer which you can then reuse in a new `containers.Sequential`, or in a `models.Sequential` (inheriting from the same class). This is very powerful (eg. implement a 'VGG' layer, then implement a VGG net as a stack of such layers). In the same way, we want to be able to build `containers.Graph` structures that we can reinject into new architectures (either `Sequential` or `Graph`). For instance, you should be able to implement an inception layer using a `Graph`, or a Neural Turing Machine layer using a `Graph`, then use these layers in new models. 

This is easily made possible by restricting the use of `containers.Graph` as a layer (methods `connect`, `get_input`, `get_output`, and `input` attribute) to cases where the graph has exactly one input and one output. Any other case would raise an exception. In that sense,  `containers.Graph` will implement a superset of the `Layer` API.

Recursion is the most powerful concept in CS, and we need to be able to utilize it fully in Keras.

**Comment by iskandr** [comment]
>This is easily made possible by restricting the use of containers.Graph as a layer (methods connect, get_input, get_output, and input attribute)

If I have `Graph` A with two outputs, can I connect it to `Graph` B with two inputs?

**Comment by iskandr** [comment]
Also, @fchollet, what do you think of making multiple input/output functionality default to using named slots instead of sequences? When a network has two inputs and two outputs I would rather call `model.fit({'peptide_sequences': X_pep, 'protein_sequences': X_prot}, {'binding_affinity': Y_aff, 'binding_stability': Y_stab})` rather than remember the order in which these arguments are supposed to go.

**Comment by fchollet** [comment]
> If I have Graph A with two outputs, can I connect it to Graph B with two inputs?

I've considered it initially; it would be preferable to implement through a new set of API methods in the Graph class.

> what do you think of making multiple input/output functionality default to using named slots instead of sequences?

That will be the case for Graph models; Sequential models will keep working as before (supporting multiple inputs but only a single output). Any complex network should be built as a Graph; I can't imagine anyone using Sequential with more than 2 inputs after Graph is available.

**Comment by iskandr** [comment]
> I've considered it initially; it would be preferable to implement this through a new set of API methods in the Graph class.

What would those look like?

**Comment by iskandr** [comment]
@fchollet I have to admit I don't actually understand the conceptual universe you've built up with Containers, Models, and Layers. That said, here's a little experiment in making Layers always just be nodes of a graph, which connect to each other freely. I find this a little cleaner than the example above (since does away with the indirection of always associating a node with a string name). The only names I usually care about are named labeled on the inputs & outputs. Otherwise I'd rather just string objects together directly. 

What do you think? I get the sense this won't fit in with your vision for Keras but I'm curious to hear why. 

```
input1 = Input(shape=(3, 32, 32)
input2 = Input(3, 32, 32)

base = MaxPooling2D(poolsize=(2, 2)), inputs=[input1, input2], merge_mode='sum'))

conv11 = Convolution2D(shape=(64, 64, 1, 1), input=base)
conv12 = Convolution2D(shape=(64, 64, 1, 1), input=base)
pool1 = MaxPooling2D(poolsize=(3, 3), input=base)
conv21 = Convolution2D(shape=(64, 64, 1, 1), input=base)
conv22 = Convolution2D(shape=(64, 64, 3, 3),  input=conv11)
conv23 = Convolution2D(shape=(64, 64, 5, 5), input=conv12)
conv24 = Convolution2D(64, 64, 1, 1),  input=pool1))

concat = Concat(conv21, conv22, conv23, conv24)
output1 = Output(concat, loss="mae")
conv24_output = Output(conv24, loss="mse")

model = Model(
    inputs={"input1": input1, "input2": input2},
    outputs={"output1": output1, "conv24_output": conv24_output},
    loss_merge="sum",
    optimizer="sgd")
model.fit(train={'input1':X1, 'input2':X2, 'output1':Y1, 'conv24_output':Y2})
```

**Comment by fchollet** [comment]
Looking at:
```
input1 = Input(shape=(3, 32, 32)
input2 = Input(3, 32, 32)
sum_inputs = Sum(input1, input2) 
base = MaxPooling2D(poolsize=(2, 2)), input=sum_inputs)
conv11 = Convolution2D(shape=(64, 64, 1, 1), input=base)
conv12 = Convolution2D(shape=(64, 64, 1, 1), input=base)
pool1 = MaxPooling2D(poolsize=(3, 3), input=base)
conv21 = Convolution2D(shape=(64, 64, 1, 1), input=base)
conv22 = Convolution2D(shape=(64, 64, 3, 3),  input=conv11)
conv23 = Convolution2D(shape=(64, 64, 5, 5), input=conv12)
conv24 = Convolution2D(64, 64, 1, 1),  input=pool1))
concat = Concat(conv21, conv22, conv23, conv24)
output1 = Output(concat, loss="mae")
conv24_output = Output(conv24, loss="mse")
model = Model(
    inputs={"input1": input1, "input2": input2},
    outputs={"output1": output1, "conv24_output": conv24_output},
    loss_merge="sum",
    optimizer="sgd")
model.fit(train={'input1':X1, 'input2':X2, 'output1':Y1, 'conv24_output':Y2})
```
@iskandr Besides the fact that this is syntactically incorrect, it is conceptually the exact same thing as the `Graph` container. Just with a different syntax. And this new syntax replaces the container/layer 2-level abstraction with a single abstraction, the layer. This is somewhat impractical as it prevents you from using global management methods such as `get_weights`, `set_weights`, `get_params`, `get_config`, etc.

> I find this a little cleaner than the example above (since does away with the indirection of always associating a node with a string name). The only names I usually care about are named labeled on the inputs & outputs.

Again, it is actually the exact same thing, but now you are picking names in the Python namespace instead of string names. You are still picking the same number of unique names, but now if you make a naming mistake (eg. redundancy) your variable is overwritten which will later cause strange compilation crashes, instead of you getting a helpful error message such as "Identifier already taken: conv24".

**Comment by iskandr** [comment]
@fchollet Sorry for the syntactic error clutter, it was quickly rearranged from your example code. 

It's not clear to me why you can't implement `get_weights`, `set_weights`, &c of a `Model` (via a graph traversal). 

>Again, it is actually the exact same thing,

It's the same but (1) less magical (since I'm creating the node objects instead of a helper method) and (2) each line is shorter. 

I do acknowledge that making the nodes anonymous might make for a more confusing debugging experience. It might be worth sticking with explicit naming just for clarity but I wanted to explore the alternative and hear why you didn't like it.

**Comment by fchollet** [comment]
> It's not clear to me why you can't implement get_weights, set_weights, &c of a Model (via a graph traversal).

You can, but not recursively. Because these methods already exist on the layer object, you *need* a higher-level object to apply the same methods to groups of layers. 

It's not that I don't like it, it's just that I think it's cleaner (though a tad more verbose) to have layers and containers, behaving in the exact same way and being interchangeable. It allows you to build complex networks recursively via object-oriented blocks. What you propose is the functional equivalent to that, and it seems to me that in this case the functional approach does not handle complexity and reusability as well. If the cost is longer lines, that's fine with me.

**Comment by fchollet** [comment]
For those interested, here is a branch with a working version of the Graph container and a minimal Graph model: https://github.com/fchollet/keras/tree/graph

It's a quick refactor of my draft from yesterday. The Graph container behaves like a layer (when used with one input and one output) and can be composed with other layers and other containers in arbitrarily complex structures. See this script: https://github.com/fchollet/keras/blob/graph/tests/manual/check_graph.py

I am now refactoring the models to make them more abstract. Callbacks have also been rewritten in the same way, which is necessary now that we are dealing with multiple loss functions to monitor.

**Comment by phreeza** [comment]
@fchollet so in your scheme of addressing nodes by strings, in the 'recursive' case, when a node of a graph is another graph, would one have to make sure beforehand that the names used in the graphs do not overlap? Or could there be some form of namespacing? I feel like this might be a case where using object names might be cleaner because it allows us to use pythons inherent namespace capabilities.

**Comment by pranv** [comment]
> so in your scheme of addressing nodes by strings, in the 'recursive' case, when a node of a graph is another graph, would one have to make sure beforehand that the names used in the graphs do not overlap? Or could there be some form of namespacing?

@phreeza, that wont be necessary. Names are used to connect layers. If you have already done the connections and you are good to go, it won't (shouldn't) matter.

@fchollet your `Layer`, `Container` and `Model` universe is perfect. It allows epic modularity and composability. I don't think we should have multiple outputs. By definition, a `Layer` is fundamental unit of computation and I feel it shouldn't do multiple things and give multiple outputs. Power of Composition should give all the expressivity needed and `Container` does just that. 

> `Graph` cannot be the same as `Sequential`, because graphs and lists are distinct concepts in CS

Seriously?

And do you need me to do anything here?

**Comment by phreeza** [comment]
@pranv I was thinking about a situation like in the example given:
    model.output(inputs=['conv21', 'conv22', 'conv23', 'conv24' ], name='output1', merge_mode='concat')

So what if conv21 is actually a node in a recursively added subgraph?

**Comment by pranv** [comment]
@phreeza 
Can you clarify if you are using `Graph` as a `Model` or a `container`? If graph is a `container`, such a thing won't be an issue

**Comment by phreeza** [comment]
Independent of the final implementation I was thinking about a situation where you want to tell a `Model` which nodes of the `Graph` are the output and how they should be mapped to the training data. That would be a case where you need to address nodes after they are already connected.

**Comment by pranv** [comment]
Having `Graph` as a `container` that is once built up and then can be used itself as a `Layer` in a `Model` is a great idea. Having multiple outputs is not an issue, as they can be merged and then used. I would push for integrating the graph architecture to the core `Sequential` one, maybe rename it. But if @fchollet  and rest think that it's not a great idea, its best we leave it as a `container`.

**Comment by kenterao** [comment]
+1 for the current ```Layer```, ```containers```, ```Model``` architecture, keeping ```Sequential``` and ```Graph``` separate.

@fchollet What do you anticipate ```containers.Graph``` ```get_config()``` will look like?  For ```containers.Sequential``` the config was descriptive enough that I could do something like

```python
def load_model(self, model_cfg):
    ''' call on default model to reconstruct from get_config() output '''
    for layer_cfg in model_cfg:
        cls_name = layer_cfg.pop('name')
        cls = getattr(layers, cls_name)
        self.add(cls(**layer_cfg))
```

For a ```Graph```, can we take the ```Layer``` configs and append name and other input relationships needed for ```add_node()``` so it is descriptive enough to reconstruct the ```Graph```?

**Comment by fchollet** [comment]
> For a Graph, can we take the Layer configs and append name and other input relationships needed for add_node() so it is descriptive enough to reconstruct the Graph?

Yes, the `get_config` method returns all the information need to reconstruct the model from scratch (basically, the constructor arguments to every method called during the construction of the graph).

The graph branch is now merged into master. This means we can now build neural Turning machines and memory networks with Keras. Happy graphing!

**Comment by nzer0** [comment]
I am looking for a method for Splitting a tensor. Splitting is used in AlexNet for the purpose of using two GPUs. In Caffe, it is implemented with [group option](http://caffe.berkeleyvision.org/tutorial/layers.html). I am not actually running on two GPUs but I need Splitting because the model will be different without it.

I think Splitting is different from the Graph model because it actually **divides tensor dimension in half**. Do you think it is possible with current API somehow?

**Comment by pranv** [comment]
You can selectively set the weights of some filters to zero like currently done in caffe conversion code.
Look at the fork

**Comment by fchollet** [comment]
It would simple to implement your own version of Splitting that does
precisely what you want. This is possible now that the general framework
supports multi-input and multi-output layers.

Basically, create a Split layer that has two outputs, then connect it
downstream to a Graph that has two inputs.

**Comment by Mofef** [comment]
Even though the discussion of #224 is apparently over and a decision is made. Even though `Graph` is already a solution – I feel like sharing my idea of an API for this splitting problem.
So starting from here
```python
model_merged = Sequential()
model_merged.add(Merge([model1, model2], mode=‘concat’))
```
respectively here
```python
merged = Merge([model1, model2], mode=‘concat’)
model_merged = Sequential()
model_merged.add(merged)
```

I think if `Merge()` consumes a list of Models, a `Fork()` / `fork()` :one:  that returns a list of Models :two: would be an elegant soluton
```python
head1, head2 = Fork(some_model, 2)
head1.add(something)
head2.add(something_else)
# optionally later on:
merged = Merge([head1, head2], mode=‘concat’)
model_merged = Sequential()
model_merged.add(merged)
```
:one: Obviously it is not a class/constructor. Just that a capital F emphasises the relation to Merge
:two: Since I'm not familiar enough with the code of Keras, maybe rather a list of Containers/Layers? Essentially I mean something `add()`-able and `Merge()`-able. 

btw: What if `Merge()`would return a Model instead of a Layer. Then this 
```python
merged = Merge([model1, model2], mode=‘concat’)
model_merged = Sequential()
model_merged.add(merged)
```
might boil down to 
```python
model_merged = Merge([model1, model2], mode=‘concat’)
```

If this is not feasible/appealing. Maybe this is a discussable approach?
```python
head1, head2, head3 = model.fork(3)
```

I wouldn't be surprised if all my proposals are foolish. If you can spare the time to explain me why, I'd love to learn from you. :)
Otherwise I can offer to try to implement it.
