### ISSUE TITLE
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

### ISSUE THREAD

**Issue by yhifny** [fchollet/keras#3208]
Hi

I use this code for Keras==1.0.5,theano 0.8.2 h5py-2.6.0

```
print('build model...')
model = Sequential()
model.add(GRU(output_dim=hidden_units,  activation='relu',input_shape=(max_seq_len, input_dim)))                
model.add(Dense(nb_classes))
model.add(Activation('softmax'))
rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=rmsprop,
              metrics=['accuracy'])

print('train model...')
print(model.summary())
#plot(model, to_file='model.png')

checkpoint = ModelCheckpoint(filepath=out_path+'/checkpoint-{epoch:02d}-{val_loss:.2f}.hdf5')

model.fit_generator(
        cacdi_data_generator(train_embedding_dir,train_encounter_filelist,train_ref_file, batch_size, max_seq_len),
        samples_per_epoch=len(open(train_encounter_filelist, "rb").readlines()),
        validation_data=cacdi_data_generator(dev_embedding_dir,dev_encounter_filelist, dev_ref_file , batch_size,max_seq_len),
        nb_val_samples=len(open(dev_encounter_filelist, "rb").readlines()),
        nb_epoch=nb_epochs,callbacks=[checkpoint])

save_model(model,out_path)
```

 and I got this error

File "cacdi_train_deep.py", line 138, in <module>
    main()
  File "cacdi_train_deep.py", line 132, in main
    nb_epoch=nb_epochs,callbacks=[checkpoint])
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/keras/models.py", line 661, in fit_generator
    max_q_size=max_q_size)
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/keras/engine/training.py", line 1454, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/keras/callbacks.py", line 39, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/keras/callbacks.py", line 295, in on_epoch_end
    self.model.save_weights(filepath, overwrite=True)
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/keras/engine/topology.py", line 2329, in save_weights
    g.attrs['weight_names'] = weight_names
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/nrg8/clu/users/steven_reber/dist/h5py-2.6.0/h5py/_objects.c:2682)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/nrg8/clu/users/steven_reber/dist/h5py-2.6.0/h5py/_objects.c:2640)
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/yasser_hifny/python/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 175, in create
    space = h5s.create_simple(shape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/nrg8/clu/users/steven_reber/dist/h5py-2.6.0/h5py/_objects.c:2682)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/nrg8/clu/users/steven_reber/dist/h5py-2.6.0/h5py/_objects.c:2640)
  File "h5py/h5s.pyx", line 101, in h5py.h5s.create_simple (/nrg8/clu/users/steven_reber/dist/h5py-2.6.0/h5py/h5s.c:1533)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

any help is appreciated.

Thanks,
Yasser``

**Comment by linkoffate** [comment]
I believe this has been an issue for quite a long time.
In my case, I supposed that this happens when any layer(i.e. Dropout layer) had no 'weight_names', meaning no weights.

Anyway, adding the first line in the following code at /engine/topology.py helped for now.
```
if weight_names != []:
    g.attrs['weight_names'] = weight_names
    for name, val in zip(weight_names, weight_values):
        param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
        param_dset[:] = val
```

I'm now wondering if this is really the best solution to this issue.

**Comment by yhifny** [comment]
Thank you very much for your help. indeed your observation is correct

**Comment by linkoffate** [comment]
@yhifny 
Here are some additional comments about this annoying issue. If you use load_weights() with save_weights() being like the above code, the following error will be shown. 

`KeyError: "Can't open attribute (Can't locate attribute)"`

Before I talk about how I fixed this, I found out why this really happened in the first place. It seems that h5py can't store empty arrays [] to an attribute. Each layer has a h5 attribute 'weight_names', but because h5py can't handle empty arrays, it can't make them.

Because of this, load_weights() tries to find the attribute 'weight_names' and fails to find it because it isn't even there.

There are two options:
1. using exceptions
2. hard coding

I simply used 2 as in the following code (from /engine/topology.py - load_weights())
```
weight_value_tuples = []
for k, name in enumerate(layer_names):
    g = f[name]
    print (g.attrs.keys())
    if 'weight_names' not in g.attrs:
         continue
    weight_names = [n.decode('utf8') for n in g.attrs['weight_names']]
```

**Comment by Bilokin** [comment]
Hello,  I have exactly the same problem. After fixing initial error: 
`ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)`
I got stuck on 
`KeyError: "Can't open attribute (Can't locate attribute)"`
and solution by @linkoffate  didn't help me, unfortunately. 
Does anyone has other ideas?

**Comment by linkoffate** [comment]
@Bilokin 
If you're using the solution I wrote previously, make sure you changed the code in load too.
The problem is that this solution is most likely only useful in keras 1.0.6.

There is actually a radical solution to this problem. It's not this library's problem, it is most probably because hdf5 is not the recent version.

At least a few months ago, when you use pip to install h5py, the library version for hdf5 isn't able to handle empty lists. You have to reinstall hdf5 manually:
`wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar`

After updating hdf5, you should reinstall h5py, too.
Finishing the reinstall, check the update with:
```
>>> import h5py
>>> print h5py.version.info
Summary of the h5py configuration
---------------------------------

h5py    2.6.0
HDF5    1.8.17
Python  2.7.12 
...
```
