### ISSUE TITLE
How can one enforce tied weights in Keras? 

### ISSUE THREAD

**Issue by hadi-ds** [fchollet/keras#3261]
I have built an auto-encoder consisting of a single hidden layer (hence, two weights and two biases to be learned). I want to impose weight tying, that is to force the network to learn the same weight matrix for input-to-hidden and hidden-to-output transformations.

I wonder how this can be implemented in Keras.

thanks,
Hadi

**Comment by ncullen93** [comment]
If the layers come back-to-back, you can combine them into one custom layer that uses the same weights. Otherwise, you have to instantiate the first layer, and pass that instantiation as an argument to the second layer where you will just use the weights from the first.  Either way, you have to use a custom layer. There are many different examples out there..

**Comment by dswah** [comment]
I've been working on Convolutional Auto-encoders and wanted tied weights, so I tried what @ncullen93 suggested.

It was easier than expected :)

[Here is a Gist](https://gist.github.com/dswah/c6b3e4d47d933b057aab32c9c29c4221) that implements special layers for Conv1D and Conv2D.

**Comment by farizrahman4u** [comment]
You can tie weights using a Lambda layer:

```
model = Sequential()
model.add(Dense(10, input_dim=10, bias=False))
W = K.transpose(model.layers[-1].W)
model.add(Lambda(lambda x: K.dot(x, W)))
```

**Comment by aidinhass** [comment]
Here is a sample solution for people who are still wondering about an auto-encoder with tied weights.[http://www.pythonexample.com/snippet/python/autoencoder_extrapy_njellinas_python](url)
