### ISSUE TITLE
val_loss becomes higher as train_loss lower

### ISSUE THREAD

**Issue by zhaopku** [fchollet/keras#3328]
I'm training a single-layer LSTM on a sentence classification task. Each sentence has two labels: pos/neg. But as I train the model, the training acc and loss do decrease, but the val_loss becomes higher, which is quite weird. Here is my code (I use pre-trained word embeddings):

```
model = Sequential()
model.add(Embedding(total_words + 1, EMBEDDING_DIM, weights = [embeddings_matrix], input_length = MAX_SEQUENCE_LENGTH,
                            trainable = True, mask_zero = True))
model.add(LSTM(100, return_sequences = False))
#model.add(Dense(1))
#model.add(Activation('sigmoid'))
model.add(Dense(2, activation='softmax'))

sgd = SGD(lr = 0.1, decay = 1e-6, momentum = 0.9, nesterov = True)
model.compile(loss = 'binary_crossentropy', optimizer = sgd, metrics = ['acc'])

model.fit(train_x, train_y, validation_data = (cv_x, cv_y), nb_epoch = 50, batch_size = 50)
score, acc = model.evaluate(test_x, test_y, batch_size = 100)

```

part of the result:

```
Train on 8529 samples, validate on 1067 samples
Epoch 1/50
8529/8529 [==============================] - 37s - loss: 0.6966 - acc: 0.5301 - val_loss: 0.7023 - val_acc: 0.5089
Epoch 2/50
8529/8529 [==============================] - 32s - loss: 0.6780 - acc: 0.5763 - val_loss: 0.7338 - val_acc: 0.5098
Epoch 3/50
8529/8529 [==============================] - 33s - loss: 0.6549 - acc: 0.6113 - val_loss: 0.7129 - val_acc: 0.5220
Epoch 4/50
8529/8529 [==============================] - 33s - loss: 0.6216 - acc: 0.6576 - val_loss: 0.7478 - val_acc: 0.5267
Epoch 5/50
8529/8529 [==============================] - 33s - loss: 0.5766 - acc: 0.6959 - val_loss: 0.8012 - val_acc: 0.5323
Epoch 6/50
8529/8529 [==============================] - 32s - loss: 0.5153 - acc: 0.7422 - val_loss: 0.8858 - val_acc: 0.5361
Epoch 7/50
8529/8529 [==============================] - 33s - loss: 0.4449 - acc: 0.7940 - val_loss: 0.8978 - val_acc: 0.5211
Epoch 8/50
8529/8529 [==============================] - 34s - loss: 0.3561 - acc: 0.8428 - val_loss: 1.1019 - val_acc: 0.5127
Epoch 9/50
8529/8529 [==============================] - 34s - loss: 0.2648 - acc: 0.8893 - val_loss: 1.1911 - val_acc: 0.5258
Epoch 10/50
1250/8529 [===>..........................] - ETA: 27s - loss: 0.1780 - acc: 0.9400^CTraceback (most recent call last):

```

**Comment by sinjax** [comment]
Is this not a classic symptom of a model overfitting? 
In many machine learning applications it is good to stop training early when the predictive power of the model on some validation set starts to reduce. Keras provides an EarlyStopping module to help do this automatically: http://keras.io/callbacks/

**Comment by zhaopku** [comment]
@sinjax but the val_loss start to increase when the train_loss is relatively low......

**Comment by sadeghmir** [comment]
> but the val_loss start to increase when the train_loss is relatively low

That is over-fitting. It happens when your model explains the training data too well, rather than picking up patterns that can help generalize over unseen data. As **sinjax** said, early stopping can be used here. You can also reduce the size of your LSTM layer. Having said these, your val_loss is worse than your loss from the get go and then it improves. This might be an indication that your validation data is not of the same distribution as your training data.

**Comment by zhaopku** [comment]
I still find it weird. It shouldn't be the distribution problem because I randomly shuffled the data before feeding them to the network. I've trained the same data using my own code, it works well. I've set the drop out rate of the current model to 0.6, but it still keeps overfitting......

**Comment by the-moliver** [comment]
You are fitting a very flexible model to 8529 data points. Of course its going to overfit. With that little data something simpler will likely work much better. You simply don't have enough data to constrain the model you've built.

**Comment by linxihui** [comment]
Make the learning rate smaller? You have high learning rate + high momentum + small decay.

**Comment by zhaopku** [comment]
Hi guys, I've set the momentum to zero and use a dropout of 0.5, but nothing it still happens

**Comment by ersinyar** [comment]
@sinjax providing an early stopping criteria as you suggest is a good idea. But, I think val_acc fluctuates in an interval.  What should we do in this case? If val_acc first starts at a low value say 0.4 and increase up to a higher value and then decreases continuously early stopping at the highest value of val_acc would be the best option. However, I see fluctuations in a limited interval in this case. Val_acc starts from 0.5 and does not show a major improvement. Why don't we stop at epoch 2? I think 0.02 accuracy increase should not be the point of running over epochs.

**Comment by leedrake5** [comment]
I am re-upping this, because I see similar behavior in one of my models. I am running Keras 2.2.4 in R, using plaidml as a backend on a Mac. 

When I use validation_split to create a test set, The val_acc and val_loss either go inverse to the training data (e.g val_acc stays the same while val_loss goes up) or both stay static. However, if I pull data entirely from the data and keep validation_split at 0 (e.g. I manually split the data) the training accuracy is around 99% while the manually withheld data is at 87%, about what you'd expect from a mediocre model. I don't think there's data leakage, otherwise the test data accuracy would be as high as model accuracy. I can see that only a subset (80% or so) of the data is being trained on. 

So, to summarize, the difference between acc and val_acc is consistent with what you'd expect for overfitting. But the model itself generalized very well to data not passed to Keras. 

Examples: (validation_split=0.1, with an additional 0.1 held form Keras entirely):

> Epoch 100/100
> 529/529 [===] - 1s 2ms/step - loss: 0.3362 - acc: 0.8752 - val_loss: 19.4010 - val_acc: 0.0678
> 

Classic overfitting. But the 0.1% that never got passed to Keras has an accuracy of 74% against what I'm being told is an overfit model. Again, this isn't data leakage because (a) the test accuracy isn't as good as the training accuracy and (b) the total sample is 654, while I can see that training occurred on 529 samples. Maybe I'm taking crazy pills, but it seems like val_loss and val_acc aren't meaningful.
