### ISSUE TITLE
Bias initialization

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#339]
Hello!

I was looking my network weights, when I realize that all my bias values on a Dense layer were 0s. I saw on the Dense Layer initialization: self.b = shared_zeros((self.output_dim)). Shouldn't be self.b = shared_ones((self.output_dim))? 

I don't know if I didn't understand, or if it exists somewhere inside the code that changes it. I'm kinda new on Theano stuff.

**Comment by fchollet** [comment]
Starting with zeros for the bias is the norm in fully-connected layers. 

It has recently been shown that one-initialized biases worked better in LSTM, though. But LSTM are very different from feedforward dense nets.

**Comment by felipefariax** [comment]
Thanks for the quick answer @fchollet!

Do you know which paper states that?

**Comment by Smerity** [comment]
Re: which paper, whilst it was introduced far earlier (Gers et al., 2000), the improvements were again shown in a variety of tasks in [An Empirical Exploration of Recurrent Network Architectures](http://www.jmlr.org/proceedings/papers/v37/jozefowicz15.pdf) (Jozefowicz et al., 2015):
"We found that adding a bias of 1 to the LSTM’s forget gate closes the gap between the LSTM and the GRU."

**Comment by felipefariax** [comment]
Thank you, @Smerity!

Do you know my previous question about the velocity calculation?

**Comment by geminatea** [comment]
@fchollet, I wouldn't be surprised that initializing biases to zero is standard, but it seems to be unlikely to be optimal for many normal problems one might want to solve with FC NNs.  For instance, consider regression with relu-style activations.  If the biases are initialized to zero, the half-planes of positive activation specified by each neuron are starting in a non-generic configuration (the bounding hyperplanes all pass through the origin)!  This seems like a terrible way to start finding a solution to the regression problem since you would want the positive domains to have irregular overlaps.

It would be nice to have options for bias initialization.

**Comment by sun9700** [comment]
Or add a Bias core layer

**Comment by sun9700** [comment]
@fchollet  or add a Bias in Core Layer
In this famous bioinformatics paper published in nature
http://www.nature.com/nbt/journal/v33/n8/extref/nbt.3300-S2.pdf
the bias final Dense layer is init to -0.4 due to the dataset

**Comment by hubayirp** [comment]
Nice find, SunYu!
