### ISSUE TITLE
How to use keras model with golang or C++?

### ISSUE THREAD

**Issue by cdj0311** [fchollet/keras#3456]
Hi all,
   I have trained a text classifier with keras , but the speed of predict is very slow (above 100ms/time) , so I want to use the keras model with golang or C++ to predict . I think it is difficult for me to write a keras structure , so whether there is a related work to my reference ?

**Comment by denlecoeuche** [comment]
Maybe you could look into this : [keras2cpp](https://github.com/pplonski/keras2cpp)
(I did not test it myself though.)

**Comment by fchollet** [comment]
if you need to put a Keras model in a C++ codebase, you should consider loading your Keras model using the TF backend then exporting the TF graph to a PBTXT that could be loaded using the TF C++ API.

Of course that won't do anything to speed things up, since your Keras models are already running in C++ / CUDA (if applicable) anyway.
