### ISSUE TITLE
`RuntimeWarning: divide by zero encountered in log` in `lstm_text_generation.py`

### ISSUE THREAD

**Issue by hdmetor** [fchollet/keras#3496]
I trained the model but I encountered a problem in line 65 because some values underflow in the log. Note that after the problem is encountered, I only obtain nonsensical text (more like a collection of vowels).

Such a problem is solved if the values are clipped, as in

`preds = np.log(preds.clip(min=minval)) / temperature`

Does anybody else have this problem? I can open a PR

**Comment by hdmetor** [comment]
There is also something else weird: [this commit]( https://github.com/fchollet/keras/commit/01d5e7bc4782daafcfa99e035c1bdbe13a985145) replaces 2 LSTM with a single one. Is that wanted? If so, the comment on line 51 should be taken off.

**Comment by sliedes** [comment]
I saw this same issue on today's HEAD. Before that, something weird happened, making me suspect something went wrong during the training.

I'm running lstm_text_generation.py on a 4.2M text file with TensorFlow on CPU.

Observations:

1. On epoch 1, the loss dropped quickly to something like 2.2 and reached 1.5589 at the end of the epoch.

2. The text generated after epoch 1 somewhat resembled the input corpus.

3. On epoch 2, the loss continued dropping until it reached something like 1.4 at around 80% of the epoch. After that, the loss started to rapidly climb, reaching 1.89 at the end of the epoch.

4. The text generated after epoch 2 was significantly more gibberish than the one generated after epoch 1.

5. In the middle of the text generated after epoch 2, I see this warning:

"./lstm_text_generation.py:66: RuntimeWarning: divide by zero encountered in log
  preds = np.log(preds) / temperature"

6. When epoch 3 started, loss was somewhere between 6.0 and 9.0. It slowly decreased from there, reaching 5.0 at around 70% mark of the epoch (when I terminated the script).

I will try running with the same corpus again to see if this happens again. It will just take some time, because each epoch takes >1000 seconds. I can provide the corpus (of some Finnish text) if it helps.

-----
Using TensorFlow backend.
corpus length: 4031908
total chars: 51
nb sequences: 1343956
Vectorization...
Build model...
-----

**Comment by sliedes** [comment]
On the second run, I saw this warning already during epoch 1, but the loss hasn't started to grow, so those might be two unrelated issues.

**Comment by sliedes** [comment]
Ok, also on the second run the loss started to grow during epoch 2.

I also found something that looks fishy to me in the saved models, which I dumped using h5dump. Before the training started to worsen (i.e. after epoch 1 in the my original example), all the numbers, and especially the optimizer weights, were small numbers. After it went haywire, I'm seeing in the optimizer_weights group values up to around +4.8e13.

Perhaps I should open a new issue for this, if this is unrelated?

**Comment by gewoonrik** [comment]
I also see this happening on my own dataset:
during the first epoch the loss decreases to around 2.9, but during epoch 2 it increases to 12.xxxx

**Comment by jtmckinley** [comment]
I just received this error also on Ubuntu 16.04 using tensorflow-gpu with GTX 1080 Ti, Python version:
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux

Training output:

Iteration 58
Epoch 1/1
200285/200285 [==============================] - 87s - loss: 14.2811     

--------------------------------------------------
Iteration 59
Epoch 1/1
200285/200285 [==============================] - 87s - loss: 12.3760    Using TensorFlow backend.
lstm_text_generation.py:63: RuntimeWarning: divide by zero encountered in log
  preds = np.log(preds) / temperature

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fa7bb303d30>>
Traceback (most recent call last):
  File "/home/jim/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__
TypeError: 'NoneType' object is not callable


I then loaded the model that was saved with model.save() and got:


Using TensorFlow backend.
corpus length: 600893
total chars: 57
nb sequences: 200285
Vectorization...
2017-10-04 20:16:20.543477: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-04 20:16:20.543508: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-04 20:16:20.543518: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-04 20:16:20.696139: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-04 20:16:20.696532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 10.90GiB
Free memory: 10.53GiB
2017-10-04 20:16:20.696548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-04 20:16:20.696553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-04 20:16:20.696560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)

----- diversity: 0.2
----- Generating with seed: "a more refined uprightness; and above al"
generate_nietzsche.py:53: RuntimeWarning: divide by zero encountered in log
  preds = np.log(preds) / temperature
a more refined uprightness; and above al ee  e ie  i  i i iie  ie i i ie  e  ie i i  ii e   e e  e eee i  e e ii eeeei i  e  e e ie  e  e ee i ie  i ee ii e  i ei   ee ee  ie ee   i e i ee i ie  ie iiee  e e  ee iie  e i  eeee  e ee  i eee i  ii ee eie  i ie  iiie  iii ee ie  ie e ie  e ee ee eeeee  e i iei   e i e iee ee ee ie  ee iei 2 i i  e ee ee e e 5e i 5 i ie  ee  e ie  i ie  ee eie  i eeee  eeei i  e  eee  e  ee  e e i i ei i  e

----- diversity: 0.5
----- Generating with seed: "a more refined uprightness; and above al"
a more refined uprightness; and above al ee  e ie  ee ii ei i  ei i i e ie i i e ie eee  e e  e i i eeee iee i i ee  ie i i ie ee eee  eiii  ee ie  e e i  e e ie  e e ieei i  e ee  e i ie  iei ie  eieeei i i iie e e  e ee  i e ie   e ee ee e  iiee ee  i i i ie e e i iiii ee  ee ie ee ei e e i e i i e i iieee ee  ii ieeeiei  i iee 2 i ie  ee ee  e  i e i e e ee  ee eee  e eei ie eieeei i ie  e e ee ei ei ii e e i  e  e i eee ie  e ie e e

----- diversity: 1.0
----- Generating with seed: "a more refined uprightness; and above al"
a more refined uprightness; and above al i i i e  e e ie  e e e ee  i  e i eee  e ieeee  i i  e  e  e ie  iee ii  e eei iiiee  e i i iiee  e ee  e ie ie  e i ie  e ei  e i e e  e ie  i e ii ie  ei e i eiiee i ee eeie ii e  e ee ee  e ie  ie e ii i ee  e ee i eeiii 5i i e  ee eee eee  eeie i i  e ie  e e e ee i e ie  e  e eeeiei ii eee  i e ee  eieei i  e  eee  eii i ee i  ei e ie  ie  ei iie iie  i ee eee ei e e  eee e iie  iie e e e i 

----- diversity: 1.2
----- Generating with seed: "a more refined uprightness; and above al"
a more refined uprightness; and above al ee  i ie  e  ei e iie iieee  ee i i  i e  eeeeeei i  i eee ie  e ie  ei i  iiee  i  e  i ie  i ee ee ie ii  eee  e ii  ei i ii i  e e ie  e e i e ie  e eei i e iei i   e i  ii e ii iee  e eeiie i ie  7i ee  ee eei e e  eeie i e ei iie e  e ii ee  e e  ii eie e e  e i ie  e i ii  ie  ei ie  ie  ie e i i  ii  7e  ie e ee ee e ee iiei i  eeie  i iee  e ee  ie  i i ie e e  i ii ei e i ie  e i i i ii 

Any ideas on how I can resolve this problem?  Thanks!

**Comment by hdmetor** [comment]
Have you tried to clip the value?

`preds = np.log(preds.clip(min=minval)) / temperature`

**Comment by jtmckinley** [comment]
Thanks for your response hdmetor and sorry for the delay in my response, I was away from my computer for a few days.  I thought you had located the problem and I assumed that I had simply misread the stacktrace which pointed to the sampling part of the program (I read the last line and probably mistakenly attributed it to Keras which is very new to me), so I ran it again unmodified and reproduced the problem, but then I made the change to the sample method as you suggested by changing:

preds = np.log(preds) / temperature

to:

preds = np.log(preds.clip(min=0.0000000001)) / temperature

but it again failed with the following stacktrace, which is strangely less deep than the previous run I posted above.  Maybe I'm doing something wrong and did not in fact implement your suggested change.  The stacktrace from my initial post does seem to point to the np.log method, but still resulted in the stacktrace below after your suggested change:

Iteration 59
Epoch 1/1
200285/200285 [==============================] - 87s - loss: 1.3193     
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7efc83a03d30>>
Traceback (most recent call last):
  File "/home/jim/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__
TypeError: 'NoneType' object is not callable

I ran the program again on the night I posted my initial problem on a computer with a GTX 780 Ti  and it completed all 60 iterations without the divide by zero error on the Nietzsche text file.  I then tried running it on the Shakespeare text file from Peter Norvig's site:

http://norvig.com/ngrams/shakespeare.txt

on the GTX 780 TI machine and it seemed to get stuck in some kind of local minimum and produced nonsensical output that mostly consisted of punctuation and whitespace characters and I killed it after maybe 20 iterations with no loss reduction. 

Whilst I was re-running tonight on the Nietzsche test after making your suggested change I re-read this thread and saw that sliedes and gewoonrik also experienced some strange behaviour with input other than the Nietzsche text.  My experience was somewhat different however, the loss did not increase but rather looked like it got stuck in a local minimum since the loss was constant over many iterations, it did not increase as they described.

I'm very new to Keras and fairly new to machine learning in general, so I'm not sure how to proceed, or what exactly is causing these problems, but thanks very much again for your response hdmetor.

**Comment by hdmetor** [comment]
I have a limited understanding of the tensorflow internals, and I can't be of any help about the stack trace. I would do one last try with a larger `min` (for example `min=0.0001`) to see if it's a rounding problem

**Comment by jjangsangy** [comment]
@jtmckinley you should set `min` with less decimal precision as suggested by @hdmetor since it's likely you are running 32-bit floating point arithmetic, which ironically leads to clipping your clipping parameter.

It's likely the bug is caused by this weird casting to `float64` in the `sample` function.

```python
    preds = np.asarray(preds).astype('float64')
```

## Floating Point Underflow Bug
Not sure what is the underflow behavior is for numpy floats, is but `model.predict` returns an array of `tf.float32`.

As well, numpy is set to ignore underflow which may lead to errors not being propagated,

You can check the error mode by running

```python
    >>> np.geterr()
        {'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}
```

**Comment by jtmckinley** [comment]
Thanks for responding hdmetor and jjangsangy.  Sorry for my delayed response but I was waiting to get a new machine up and running at work (another GTX 1080 Ti GPU).  I reproduced the problem on this new GPU (this one is an ASUS vs. my other one at home is an EVGA, but same chipset of course) by saving the model at iteration 59 and then writing a generator python script that loaded and used the model.  I think jjangsangy is correct that the divide by zero error is not being caught in numpy and getting propagated up into the tensorflow code and resulting in a misleading traceback as well as my clip value getting clipped (LOL) due to float32 precision.  I changed the clip value in the log to 0.0001 as suggested by hdmetor and that prevented the error.  

Now I need to try and figure out what causes the strange behavior when using the Shakespeare corpus, maybe it's the formatting, all the punctuation is separated by spaces in the file from Peter Norvig's site, I'll see if I can find a different version.  

Thanks again very much to both of you for your help!
