### ISSUE TITLE
Speed of model.predict() for a network with residual blocks

### ISSUE THREAD

**Issue by stillbreeze** [fchollet/keras#3517]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I have a model made up of primarily of residual blocks which is described [here] (https://cs.stanford.edu/people/jcjohns/papers/fast-style/fast-style-supp.pdf) on page 1.

There are around 50 odd layers in the network and it's taking around 5.5 sec for *model.predict()* to produce an output on a GTX Titan X.
Is this time normal for a model that deep? A 50 layer Resnet model takes 403 ms for one forward and backward pass according to [this] (http://torch.ch/blog/2016/02/04/resnets.html) blog. Isn't *model.predict()* just a forward pass through the network and hence shouldn't it take less than a second to produce the output?

Thanks for the help in advance!

**Comment by bernardohenz** [comment]
Two possible explanations:
1) size of images: CIFAR and Imagenet images have a reduced resolution (32x32 and 224x224 I think). Remember that if are predicting a larger image (1080p), the time may grow drastically.

2) CUDA and cudnn settings right: check if you are indeed running the predict on the GPU (but I think that the prediction of such net in the CPU would be very slow). But check also if the cudnn is set properly. Check your CNMem also, you can set 50% or more if you want, see what happens when I start importing keras modules:

```
Using Theano backend.
Using gpu device 0: GeForce GTX 970 (CNMeM is enabled with initial size: 20.0% of memory, cuDNN 5005)
```

**Comment by stillbreeze** [comment]
Thanks for the reply.

About the size, yes, the size is 400x400 but I doubt it will increase the forward pass time by such a large value.
Importing Keras gives me the correct GPU and cudnn version. I have tried to run with garbage collection turned off and with CNMem of up to 60%. It's faster by no more than 0.5-0.75 sec.

I was wondering how Keras compares with other frameworks at test time. I tried the resnet-50 from [here] (https://github.com/raghakot/keras-resnet/blob/master/resnet.py) and it took about 13 seconds to predict(). Is this how long it should take?

**Comment by esube** [comment]
Try and predict several hundred or several thousand images but initialize the model and load the weights once, you will see that most of the time is spent in building the model and very few msec is actually spent for each image prediction. You need to mask the initial model compilation and weights loading somehow. Let me know if that is the case with you.

**Comment by stillbreeze** [comment]
Thanks for the reply @esube 
Actually the time I quote above (5.5 sec for my network and 13 sec for Resnet-50) only corresponds to the model.predict() function. I've already loaded and compiled the model.

**Comment by esube** [comment]
Then, there must be something wrong, the forward pass per image should only
take very few msecs depending on your GPU and processor configuration. Can
you list your hardware config here?

**Comment by stillbreeze** [comment]
Sure.
I'm using a `GTX Titan X (GM 200)` Nvidia GPU and a `Core i7-5820K, 3.30 GHz` Intel CPU.
My Theano flags are:
```[global]
floatX=float32
device=gpu0
optimizer=fast_run

[nvcc]
fastmath= True

[cuda]
root = /usr/local/cuda-7.5
```

How long does it take to model.predict the above Resnet-50 model or a VGG-16 model for you? @fchollet : Has anyone timed it anywhere?

**Comment by stillbreeze** [comment]
So, I tried using the Theano backend to get the results instead of predict() function and got what I wanted.
```
get_output = K.function([model.layers[0].input],[model.layers[56].output])
model_output = get_output([X_test])[0]
```
Getting the symbolic outputs (first line) of course takes most of the time, but can be done beforehand after loading the model. So, effectively generating the predictions at test time only takes around 0.2 sec now. 

Closing the issue, but still not sure why model.predict doesn't just compute a pre-compiled graph.  I always believed it was what I was supposed to use at test time to get the results. 
Anyway, thanks a lot for your time @bernardohenz & @esube !

**Comment by esube** [comment]
@stillbreeze I am glad you figured it out. As you have found out, the Keras predict function essentially is doing what you just did above with some pre- and post- processing steps. Since each predict function is making the theano predict_function on: https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1174 
it is essentially recompiling the whole computation graph as sub-graph in each call to predict. So, the predict function isn't appropriate for what you are looking for as it doesn't mask the creation of the predict function after one initial call to it. Perhaps you could make another function that does this. I had to run predictions in a real-time environment and noticed that lag too. May be you should do a PR for another function that does that.

**Comment by stillbreeze** [comment]
Introduction of a new method for real time predictions will need another method for compiling the  Theano function (to get the output of the last layer) which needs to be called before the new predict method. There may be other ways to do it too.
@fchollet : Do you think this is needed?

**Comment by pGit1** [comment]
@stillbreeze I am using the TF backend and I find to the predict to be extremely slow as well. Your solution above won't work for me for some reason. I keep getting a size mismatch error. Is this:

> get_output = K.function([model.layers[0].input],[model.layers[56].output])
model_output = get_output([X_test])[0]

the only way to make predict fast? I wish there was a native Fast_Predict or something.

**Comment by stillbreeze** [comment]
The probable reason for a size mismatch error in these two lines should be that your `X_test` input isn't the same size as specified by your model definition.

**Comment by pGit1** [comment]
It is. I have made sure of it. It works fine when I do the predict method. It looks like I wasn't feeding the function a list. When I modified my code to do that, it still gave me some weird error regarding specifying "backend.learning_phase."

**Comment by stillbreeze** [comment]
Can you post your complete code and their respective error logs.

**Comment by pGit1** [comment]
Code:
`#Preferred method to test is to use model to access aribtrary layers`
`t = imagenet_utils.preprocess_input(X_train[:10].astype('float32'))`

`resnet50 = Model(input=resnet50.input, output=resnet50.get_layer(index=-2).output)`

`get_output = K.function([resnet50.layers[0].input],[resnet50.layers[-1].output])`

`model_output = get_output([t])[0]`

### Error
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-20-9a4293a7c7eb> in <module>()
      1 get_output = K.function([resnet50.layers[0].input],[resnet50.layers[-1].output])
----> 2 model_output = get_output([t])[0]
      3 print X_train.shape

/Users/sot3z-mac/Conda/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
   1601         session = get_session()
   1602         updated = session.run(self.outputs + [self.updates_op],
-> 1603                               feed_dict=feed_dict)
   1604         return updated[:len(self.outputs)]
   1605 

/Users/sot3z-mac/Conda/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    370     try:
    371       result = self._run(None, fetches, feed_dict, options_ptr,
--> 372                          run_metadata_ptr)
    373       if run_metadata:
    374         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Users/sot3z-mac/Conda/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    634     try:
    635       results = self._do_run(handle, target_list, unique_fetches,
--> 636                              feed_dict_string, options, run_metadata)
    637     finally:
    638       # The movers are no longer used. Delete them.

/Users/sot3z-mac/Conda/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    706     if handle is None:
    707       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 708                            target_list, options, run_metadata)
    709     else:
    710       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/Users/sot3z-mac/Conda/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    726         except KeyError:
    727           pass
--> 728       raise type(e)(node_def, op, message)
    729 
    730   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'keras_learning_phase' with dtype bool
	 [[Node: keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'keras_learning_phase', defined at:`

**Comment by stillbreeze** [comment]
Resnet50 has batch normalisation layers which behave differently at train and test time. You need to define a `K.learning_phase()` placeholder and pass it when you evaluate the graph (ie, when you call `get_output()`). 

See this:
https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

**Comment by pGit1** [comment]
@stillbreeze You are amazing!! Works perfectly now. Testing speed differences. :1st_place_medal:

**Comment by stillbreeze** [comment]
Glad I could help!

As for the speed, in testing environment, you can define the model and the symbolic variable `get_output` and load it all beforehand.
Then when a new input comes in, you just evaluate the symbolic variable, which should take a few ms only

**Comment by pGit1** [comment]
Thanks! What I do not understand is this portion: 

> you can define the model and the symbolic variable get_output and load it all beforehand.

What does "load it all beforehand" mean exactly? How do I do this? When I did some testing with get_output I did not see any speed differences with .predict(). I may be doing it wrong though!

**Comment by stillbreeze** [comment]
The forward pass is computed in the computational graph when you finally do `model_output = get_output([X_test])[0]` and the time it takes for the model for this forward pass is the testing time for the model.

You can define both the model, ie. `model = Model(input = abc , output = xyz)` and the symbolic variable which contains the output of the model, ie. `get_output = K.function([model.layers[0].input],[model.layers[56].output])` before you start testing and load them as variables in the memory.

Now, when you send an input `X_test` into the network and get the output, ie. `model_output = get_output([X_test])[0]`, this should be counted as the actual prediction time.

**Comment by pGit1** [comment]
Excellent thank you sir.

**Comment by munsanje** [comment]
For what it's worth, I've found that having overly an small value for `batch_size` compared to the size of the data significantly affects prediction speeds. In my case I was getting prediction times of ~5 minutes on a 2000 by 2000 by 5 image (4,000,000 by 5 data points) The default `batch_size` is 32 so clearly this wasn't making good use of parallelism. Kicking the batch size up to ~ 8000 brought times down to < 1sec. Hope this helps someone.

**Comment by dberma15** [comment]
I'm also having trouble with a slow model.predict significantly bottle necking my code. I am running Python 3.5 on a Windows 7 laptop, so no GPU and 8GB of RAM, . The model is VGG_16 (https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3) with the last four layers (two dense layers and two drop out layers removed). I am using it as a feature extractor so that I don't have to build a CNN on my own. I resize the images and then use predict on them. 
`features=featureExtractor.predict(X_train)`
I decided to try it on a subset 3,600 images, a fraction of all of the images I have, and I found that it took over an hour. That's only 1% of my images. If I use all of them, it'll take four days just to load it all in. Is there anything I can do to speed this up?

I have already tried using
```
get_output = K.function([featureExtractor.layers[0].input],[featureExtractor.layers[32].output])
model_output = get_output([X_test])[0]
```
and that takes even longer. 

I have also tried changing batch_size and that only increases the time as well. 

Does anyone have any suggestions?

**Comment by pGit1** [comment]
This is still kinda slow but do the predict on one image at a time. In
general all of these tricks should not be necessary though. :(

**Comment by pGit1** [comment]
@dberma15 

This still my experience as well. Even when I boost my batch size per @munsanje 's recommendation. Whether I use the function or predict I get REEALLY slow performance.

**Comment by trevor-richardson** [comment]
@stillbreeze 
Background: I am building a video prediction system that I want to run in real time on a robot but it is too slow.
I followed your instructions and I did not get any increase in speed in my prediction time. 
I previously used:

start = time.time()
model.predict(single_input, batch_size = 1)
end = time.time()

And my prediction time for a tensor with the shape (1, 15, 64, 64,3 ) was .3 seconds. I am using a ConvLSTM model with 3 layers and one fully connected layer with a probability output. I use batch norm and flatten but I correctly quiet those in the prediction. 15 is the number of images in my video.

I switched to using your suggestion and I even reduced the model and the input to (1, 1, 64, 64, 3) aka a single image.

get_output = K.function([model.layers[0].input, K.learning_phase()], [model.layers[-1].output])
 start= time.time()
 model_output = get_output([video, 1])[0]
 end = time.time()

My prediction time is still .3 seconds. This is weird.... If your experienced orders of magnitude of speedup and I experience no speed up even though I'm using the back-end and I reduced the video to a single image so my recurrent network doesn't have to run multiple images through it in a single prediction.

Can anyone help me. My model is basically useless unless I get to milisecond prediction. 

LASTLY I am using intel i7 cpu 3.3 ghz and 11gb GTX 1080ti [brand new basically] with 16 gigbytes of ddr4 ram. I don't think the hardward is a problem. I don't understand why model.predict() is so slow and I don't know why the back-end is so slow. 

Can someone point me in the right direction to having a model whose prediction is in miliseconds .013s or around that time.

**Comment by stillbreeze** [comment]
@trevor-richardson :
Firstly, `K.learning_phase()`, should be 0 for test mode.
Try this instead:

```
get_output = K.function([model.layers[0].input, K.learning_phase()], [model.layers[-1].output])
start= time.time()
model_output = get_output([video, 0])[0]
end = time.time()
```
If that doesn't make any difference, can you post your full model along with the input shape it expects.

**Comment by trevor-richardson** [comment]
@stillbreeze 
I tried with both 1 and 0. It doesn't change the prediction speed. Sorry I didn't mention that. Here is the full model and the input dimension is (1, 1, 64, 3)

[model.zip](https://github.com/fchollet/keras/files/968559/model.zip)


I am using TensorFlow as my backend.

**Comment by stillbreeze** [comment]
I can't decode the json (perhaps because it's version 2). Can you just post the code for the model.

**Comment by trevor-richardson** [comment]
Thanks for the help but I can't do that yet. The code is private for now. Here is how I decode the .json.

def load_deep_architecture(filepath_arch, filepath_weight):
    json_file = open(filepath_arch, 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)
    # load weights into new model
    loaded_model.load_weights(filepath_weight)
    loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
    print("Loaded model from disk")
    return loaded_model

If that doesn't work for you no worries. I'll post if I can fix the problem. I do get a speedup if I use the cpu which is odd. With cpu I'm getting a prediction time of .05 seconds.

**Comment by stillbreeze** [comment]
So, I tried a small model of my own with two dense layers and a softmax and I do notice a large difference in time between the two methods on CPU (0.3 seconds vs 0.002). Additionally, in the experiments with resnet, I found the same difference in timing on a GPU too.
If your problem exists only on a GPU, I won't be able to reproduce it as I don't have access to one right now. Do post your solution if you figure it out.

**Comment by trevor-richardson** [comment]
Figured out the problem. Make sure that you are not only checking the time of your first prediction. My first prediction in a live setting takes .3 seconds and everyone after that takes .02 seconds. Basically, I call my first prediction before the live experiment even runs so that the model is loaded and ready to go for every subsequent single prediction in a live setting. In a live setting my gpu is much faster. The cpu is only faster on the first prediction time and much slower on every subsequent one.

**Comment by pGit1** [comment]
@trevor-richardson your experience has been mine as well but from I gather without a GPU you can't use .preict() for anything useful in real time. 

I wish there were a more permanent fix though!

**Comment by aniket03** [comment]
@stillbreeze @trevor-richardson @pGit1 

I tried experimenting with both keras .predict()  method and the backend K.function() methods but I get approximately same prediction time on both around 0.37 s for 1 image.
I am using Tensorflow backend and CPU based computations.

Code snippet is:
```
       resnet_model = resnet50.ResNet50(weights='imagenet', input_shape=(224, 224, 3), include_top=False)
       get_output = K.function([resnet_model.input, K.learning_phase()], [resnet_model.output])
        t1 = time.time()

        batch_features = get_output([X_batch, 0])
        print ("Time using backend of keras directly", time.time()-t1)

        t1 = time.time()
        batch_features = resnet_model.predict(X_batch)
        print ("Time using keras only", time.time() - t1)
``` 
Also I am using K.learning_phase=0 since I am using this in test.
