### ISSUE TITLE
model.fit ValueError: I/O operation on closed file .. GPU DEAD AFTER THIS ERROR 

### ISSUE THREAD

**Issue by ibrahim-amer** [fchollet/keras#3632]
I got an exception while fitting the model using model.fit() similar to the one [here  ](https://github.com/fchollet/keras/issues/2110) , then I put my computer on hibernate, till now everything is normal. On the next day I tried to start my PC but the monitor didn't detect any GPU I tried to change graphic card slot but with no change, the GPU fans are spinning. I also tried to change the monitor with my Samsung LED TV, the TV was able to detect that there is a current coming from the HDMI cable but the TV stated that there is no signal. So, what is going on !! has this something to do with the exception thrown?  I tried all possible solutions and I think the GPU is dead and it needs to be replaced.
I'm using nvidia 660 on windows 10 
Theano and Keras are updated to the latest version
If you have any questions let me know in the comments

**Comment by fchollet** [comment]
`ValueError: I/O operation on closed file` is an error you get in older versions of IPython notebooks, due to the notebook's inability to cope with fast stdout refreshing. It's not related to Keras, and it's not related to GPU usage in any way.

Your dying GPU has clearly nothing to do with the error you are reporting.
