### ISSUE TITLE
OverflowError: Range exceeds valid bounds

### ISSUE THREAD

**Issue by jagiella** [fchollet/keras#3781]
I just transfered my scripts to a different machine (**both Ubuntu 16.04**) and the error (see Issue title) popped up. On my old machine it is working flawlessly.

My code causing the problem:

``` python
model = Sequential()

model.add(Convolution2D(nb_conv_filters, conv_kernel_size, conv_kernel_size, border_mode='valid', input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(pool_kernel_size, pool_kernel_size)))

model.add(Flatten())

model.add(Dense(nb_dense_neurons)) #128
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
                  optimizer='adadelta',
                  metrics=['accuracy'])
```

The error is the following:

``` python
Traceback (most recent call last):
  File "sensitivityAnalysis.py", line 14, in <module>
    cnn.buildModelLargeKernels( [4])
  File "/home/user/CNN.py", line 341, in buildModelLargeKernels
    model.add(Dense(nb_dense_neurons)) #128
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 487, in __call__
    build(input_shapes[0])
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/usr/local/lib/python3.5/dist-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/usr/local/lib/python3.5/dist-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/theano_backend.py", line 140, in random_uniform_variable
    return variable(np.random.uniform(low=low, high=high, size=shape),
  File "mtrand.pyx", line 1565, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:17311)
OverflowError: Range exceeds valid bounds
```

Any idea what causes this problem and how to get rid of it? It seems to occure while adding a dense layer.

**Comment by varoudis** [comment]
#2681 
Same problem with me and others

**Comment by Viveksbawa** [comment]
I am facing the same problem. the networked which were working perfect on ubuntu 14 are generating error "OverflowError: Range exceeds valid bounds" in ubuntu 16. issue is with dense layer. can't figure out the problem. please share if anyone has resolved this issue.

**Comment by Simmetria0** [comment]
Same problem, and I have an OSX. Exactly same code started to give this problem after I reinstalled keras....

**Comment by Simmetria0** [comment]
Ok, I solved the problem adding these two lines at the beginning of the code:

from keras import backend as K
K.set_image_dim_ordering('th')

Hope can help

**Comment by wac81** [comment]
@Simmetria0 it works for me! thanks!

**Comment by dwiprasetyo-an** [comment]
@Simmetria0 it also works for me. Thank you.

**Comment by jiangyangbo** [comment]
is works for me, tks

**Comment by wenliang** [comment]
Thanks. It works for me.

**Comment by steindor** [comment]
I have the same problem on ubuntu 16.04 and the image_dim_ordering is not working for me since keras.json has 'theano' and 'th' already set. It seems to be connected to the dense layers since when I remove them the error dissapeares. 

Here is my code: 

`def get_conv_model():
    model = Sequential([
            Lambda(norm_input, input_shape=(1,28,28)),
            Convolution2D(32,32,3, activation='relu'),
            Convolution2D(32,32,3, activation='relu'),
            MaxPooling2D(),
            Convolution2D(64,64,3, activation='relu'),
            Convolution2D(64,64,3, activation='relu'),
            MaxPooling2D(),
            Flatten(),
            Dense(512, activation='relu'),
            Dense(10, activation='softmax')
        ])
    model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

model = get_conv_model()
`
and the error:

`---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-12-9bc2790037dc> in <module>()
----> 1 model = get_conv_model()

<ipython-input-11-906d311336cd> in get_conv_model()
     10             Flatten(),
     11             Dense(512, activation='relu'),
---> 12             Dense(10, activation='softmax')
     13         ])
     14     model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/models.pyc in __init__(self, layers, name)
    253 
    254         for layer in layers:
--> 255             self.add(layer)
    256 
    257     def add(self, layer):

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/models.pyc in add(self, layer)
    306                  output_shapes=[self.outputs[0]._keras_shape])
    307         else:
--> 308             output_tensor = layer(self.outputs[0])
    309             if type(output_tensor) is list:
    310                 raise Exception('All layers in a Sequential model '

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in __call__(self, x, mask)
    485                                     '`layer.build(batch_input_shape)`')
    486             if len(input_shapes) == 1:
--> 487                 self.build(input_shapes[0])
    488             else:
    489                 self.build(input_shapes)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/layers/core.pyc in build(self, input_shape)
    693 
    694         self.W = self.init((input_dim, self.output_dim),
--> 695                            name='{}_W'.format(self.name))
    696         if self.bias:
    697             self.b = K.zeros((self.output_dim,),

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/initializations.pyc in glorot_uniform(shape, name, dim_ordering)
     57     fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
     58     s = np.sqrt(6. / (fan_in + fan_out))
---> 59     return uniform(shape, s, name=name)
     60 
     61 

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/initializations.pyc in uniform(shape, scale, name)
     30 
     31 def uniform(shape, scale=0.05, name=None):
---> 32     return K.random_uniform_variable(shape, -scale, scale, name=name)
     33 
     34 

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.pyc in random_uniform_variable(shape, low, high, dtype, name)
    138 
    139 def random_uniform_variable(shape, low, high, dtype=_FLOATX, name=None):
--> 140     return variable(np.random.uniform(low=low, high=high, size=shape),
    141                     dtype=dtype, name=name)
    142 

mtrand.pyx in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:17303)()

OverflowError: Range exceeds valid bounds`

Anyone have any other solutions to try?
