### ISSUE TITLE
Arbitrary recurrent connection between layers

### ISSUE THREAD

**Issue by helange23** [fchollet/keras#3790]
Is there a straight-forward approach to create an arbitrary recurrent connection between layers?

Say I have a 3 layer RNN and I want the output of the last layer at (t-1) to be fed in as an additional input of the intermediate layer at time t. Is there a straight-forward way to do that?

Am I right that the easiest way is to create a custom layer that controls the logic of the three layers I talked about?

**Comment by unrealwill** [comment]
Standard user here.
 
Yes the functionality you want should probably be done as a custom recurrent layer. But you can reuse the "step" functions of your existing RNN inside your own step definition (so you don't have to recode the logic of existing RNNs, you just have to wire them as desired)

If you really do not want to write your RNN layer, you would have to have your RNN be stateful with a single timestep and manually unroll the RNN, but this would be really ugly.

Even with a single layer RNN I don't think it is possible to feed the (t-1) output of one layer as input for the next time. And I don't think it would be a good idea to allow to do so because it would allow cycles in the layer graph.

Finally, my curious side is wondering why you would want to do such thing ? 
It seems to me that this kind of wiring would cause some self reinforcing pseudo-loops or chaotic behavior. (Like higher level feature sees a square at time t-1, and "tell" lower level feature at time t to look for equal size sides and 90° angles which makes it see a square at t). Both of which will probably generate numerical issues during the learning process (exploding and vanishing gradients)
