### ISSUE TITLE
Who knows the secret behind the example "conv_filter_visualization.py"?

### ISSUE THREAD

**Issue by jf003320018** [fchollet/keras#3935]
The code "conv_filter_visualization.py" is what I am looking for eagerly, and its results are so amazing. After read the code, I know the meanings of the code in each line. But I don't know the principle or the secret of the method behind the code. 

So could someone can provide me some papers or blogs explaining the visualization method for the "conv_filter_visualization.py"?   
Thank you very much.

**Comment by crowsonkb** [comment]
It's basically [Deep Dream](https://en.wikipedia.org/wiki/DeepDream) applied to one filter at a time instead of a whole layer of filters. It performs [gradient ascent](https://en.wikipedia.org/wiki/Gradient_descent), starting from a gray noise image instead of a user-provided image, to maximize the activation of each filter in turn.

**Comment by jf003320018** [comment]
@crowsonkb According to your answer, I have found a paper that introduces this topic. Thank you very much. 

But may I ask another question: Is there any way to visualize the weights in the second convolutional layer?  Many examples plot these weights directly, but I think visualizing these weights should consider the relationships between the second convolutional layer and the first convolutional layer, as well as the pooling layer. 

I'm really looking forward to your reply.

**Comment by robertomest** [comment]
If you want to visualize other layer you should change `layer_name = 'block5_conv1'` to the name of the layer you'd like. The second convolutional layer should be `'block1_conv2'`. You can see the model definition (which has the layer names) [here] (https://github.com/fchollet/keras/blob/master/keras/applications/vgg16.py).

**Comment by jf003320018** [comment]
@robertomest Thanks for your answer. In my opinion, "conv_filter_visualization.py" visualize the outputs of the weights, namley the activation of a neuro. So, what I want to know is how to visualize the weights themselves. Maybe I misunderstand the code.

**Comment by robertomest** [comment]
I'll try to explain the idea behind the script:
As you said, simply looking at the matrix would not be very useful, since it is not connected to the pixels. You should, instead, take the first layer into consideration in order to visualize the filters. What this script does is use optimization to find the image that most excites (large activation values) the neuron of your choice (or, on this case, the neurons of a layer). This means that the image that is generated is what the neuron 'likes' to see, which is related to the pattern that the neuron detects. This is usually what you want when visualizing the weights, knowing what it is detecting.

**Comment by jf003320018** [comment]
@robertomest   Wow, I think that I begin to understand the real idea of this code.  Really thank you!
