### ISSUE TITLE
Keras MaxPooling2D gives ValueError: Negative dimension size caused by subtracting 2 from 1 for 'MaxPool_x'

### ISSUE THREAD

**Issue by pranay360** [fchollet/keras#3945]
Please look into the following link.
http://stackoverflow.com/questions/39815518/keras-maxpooling2d-layer-gives-valueerror

I have been facing this issue on the following config Ubuntu 16.04, Keras, TensorFlow GPU and Cuda 7.5.
On my windows config with GPU enabled Theano there is no issue in executing the script.

What might be the reason for this?

**Comment by cdalbergue** [comment]
Hello, I think taht you need to specify the dimension ordering:

- Either change image_dim_ordering: 'tf' to image_dim_ordering: 'th' in your ~/.keras/keras.json
- Specify the dim_ordering in your model like so:
```python
model.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))
```

**Comment by burgalon** [comment]
thanks @cdalbergue That actually resolves the issue however I'm not sure why it's needed as we are using the Tensorflow backend - shouldn't the dim_ordering be 'tf' ?

**Comment by cdalbergue** [comment]
@burgalon It depends of the version of tensorflow that you are using. 0.10 would use "tf", 0.11 would use "th"

**Comment by jeffreynghm** [comment]
That's weired. It's th for the latest version of keras... is there any reason? behind it @cdalbergue ?

**Comment by PonyboyYbr** [comment]
In fact, this problem results from your initial input. 
`input_shape=(3,224,224)` is for "theano"
and your backend should be "tensorflow", so it should be
`input_shape=(224,224,3)`.

**Comment by arashmh** [comment]
Just change everything from the beginning and add this:

from keras import backend as K
K.set_image_dim_ordering('th')

**Comment by sivakumar05** [comment]
Your suggestion really helped me,arashmh!

**Comment by OmarMAmin** [comment]
guys how am i supposed to set image dim ordering to theano while my backend is tensorflow?

I made your suggested fix, and it's somehow working

**Comment by whitmera** [comment]
If you try the above and continue to get similar error caused by the MaxPooling2D layer, try adding "data_format="channels_first" to MaxPooling.

i.e., MaxPooling2D(data_format="channels_first")

**Comment by ZioPwnstar** [comment]
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'max_pooling2d_3/MaxPool' (op: 'MaxPool') with input shapes: [?,1,1,256].

guys I'm lost I have tried everything mentioned here and on stackoverflow. My dataset is grayscale 17x17x1, 3 classes, and I'm using Alexnet architecture.

This is output of x_train.shape & y_train.shape : 

> x_train shape: (18079, 17, 17, 1)
y_train_shape: (18079, 3)

Explicitly I have used : 
`from keras import backend as K
K.set_image_dim_ordering('tf')`
and my keras.json : 
`{
    "floatx": "float32",
    "backend": "tensorflow",
    "epsilon": 1e-07,
    "image_data_format": "channels_last"
}
`

**Comment by Priyankk18k** [comment]
> In fact, this problem results from your initial input.
> `input_shape=(3,224,224)` is for "theano"
> and your backend should be "tensorflow", so it should be
> `input_shape=(224,224,3)`.

This helped me thanks.

**Comment by sammilei** [comment]
`from keras import backend as K
if K.image_data_format() == 'channels_first':
    input_shape = (IMG_CHANNELS, IMG_WIDTH, IMG_HEIGHT)
else:
    input_shape = (IMG_WIDTH, IMG_HEIGHT, IMG_CHANNELS)
`

**Comment by PallawiSinghal** [comment]
> 

Hi @sammilei how does this help. can u explain!

**Comment by wtyn** [comment]
> In fact, this problem results from your initial input.
> `input_shape=(3,224,224)` is for "theano"
> and your backend should be "tensorflow", so it should be
> `input_shape=(224,224,3)`.

This help me, Thanks very much

**Comment by mrgransky** [comment]
in keras 2.2.5, I tried:
`model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), data_format='channels_first'))`

**Comment by knownstranger03** [comment]
> Hello, I think taht you need to specify the dimension ordering:
> 
> * Either change image_dim_ordering: 'tf' to image_dim_ordering: 'th' in your ~/.keras/keras.json
> * Specify the dim_ordering in your model like so:
> 
> ```
> model.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))
> ```
> 
> hope that helps

there is no dim_ordering parameter when using tensorflow.keras this line will throw another error

**Comment by knownstranger03** [comment]
> thanks @cdalbergue That actually resolves the issue however I'm not sure why it's needed as we are using the Tensorflow backend - shouldn't the dim_ordering be 'tf' ?

there is no parameter dim_ordering() when you're using functions from tensorflow.keras. The problem here has different reasons in keras and TF.

In keras: change the input shape accoring to the backend framework in use or change the dim_ordering=(tf/th)

In tensorflow: goto the the code line where error is raised and change the padding='valid' parameter to padding='same'.If the parameter doesn't exist then add as in the example below.

model.add(MaxPooling2D((2,2), strides=(2,2), padding='same'))

more info on the topic can be found here - https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D

**Comment by Lotus-Blue** [comment]
> In fact, this problem results from your initial input.
> `input_shape=(3,224,224)` is for "theano"
> and your backend should be "tensorflow", so it should be
> `input_shape=(224,224,3)`.

thank you

**Comment by jashshah999** [comment]
ValueError: Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling2d_2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1]](activation_2/Identity)' with input shapes: [?,1,1,64].


Tried all of the above solutions but nothing has worked. Please help! 

CODE is below for reference: 

import os
import numpy as np
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras import optimizers
import scipy
import keras
import pylab as pl
import matplotlib.cm as cm

img_width, img_height = 150, 150

train_data_dir = '/home/jashshah999/Desktop/data/train/'



datagen = ImageDataGenerator(rescale=1./255)


train_generator = datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=16,
        class_mode='binary')




model = Sequential()
model.add(Convolution2D(32, 3, 3, input_shape=(img_width,img_height,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2),strides=(2,2),data_format="channels_last"))

model.add(Convolution2D(32, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2),strides=(2,2),data_format="channels_last"))

model.add(Convolution2D(64, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2),strides=(2,2),data_format="channels_last"))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))



model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


nb_epoch = 10
nb_train_samples = 2500

model.fit_generator(
        train_generator,
        samples_per_epoch=nb_train_samples,
        nb_epoch=nb_epoch,
        validation_data=validation_generator,
        nb_val_samples=nb_validation_samples)

**Comment by Light--** [comment]
> @burgalon It depends of the version of tensorflow that you are using. 0.10 would use "tf", 0.11 would use "th"
> 
> Edit: or the opposite, can't really remember

what about tf2? 
@burgalon

**Comment by HiroshanG** [comment]
> > thanks @cdalbergue That actually resolves the issue however I'm not sure why it's needed as we are using the Tensorflow backend - shouldn't the dim_ordering be 'tf' ?
> 
> there is no parameter dim_ordering() when you're using functions from tensorflow.keras. The problem here has different reasons in keras and TF.
> 
> In keras: change the input shape accoring to the backend framework in use or change the dim_ordering=(tf/th)
> 
> In tensorflow: goto the the code line where error is raised and change the padding='valid' parameter to padding='same'.If the parameter doesn't exist then add as in the example below.
> 
> model.add(MaxPooling2D((2,2), strides=(2,2), padding='same'))
> 
> more info on the topic can be found here - https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D



> > thanks @cdalbergue That actually resolves the issue however I'm not sure why it's needed as we are using the Tensorflow backend - shouldn't the dim_ordering be 'tf' ?
> 
> there is no parameter dim_ordering() when you're using functions from tensorflow.keras. The problem here has different reasons in keras and TF.
> 
> In keras: change the input shape accoring to the backend framework in use or change the dim_ordering=(tf/th)
> 
> In tensorflow: goto the the code line where error is raised and change the padding='valid' parameter to padding='same'.If the parameter doesn't exist then add as in the example below.
> 
> model.add(MaxPooling2D((2,2), strides=(2,2), padding='same'))
> 
> more info on the topic can be found here - https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D

this worked for me... Thanks

**Comment by ronghui19** [comment]
> Just add this:
> 
> from keras import backend as K
> K.set_image_dim_ordering('th')

save my life

**Comment by fatemeshahbazi** [comment]
> `from keras import backend as K`
> `if K.image_data_format() == 'channels_first':`
> ` input_shape = (IMG_CHANNELS, IMG_WIDTH, IMG_HEIGHT)`
> `else:`
> ` input_shape = (IMG_WIDTH, IMG_HEIGHT, IMG_CHANNELS)`

thanks a lot , it helped me:))

**Comment by kangzhiq** [comment]
For keras 2.0, it becomes:
```
import tensorflow.keras.backend as K
# to set the image order
K.set_image_data_format('channels_first')
```
See the link below:
[Keras 2.0 release note](https://github.com/keras-team/keras/wiki/Keras-2.0-release-notes#misc)
