### ISSUE TITLE
Sharing layers between models

### ISSUE THREAD

**Issue by mossaab0** [fchollet/keras#4029]
I have 9 models with identical architecture and embedding weights But they differ in the weights of the upper layers. The models are already trained, and I need to use them only for predicting some binary labels through majority voting.

My issue is that these 9 models take a good chunk of memory. Is there a way to keep one copy of the embedding layer (e.g., from model 1), and point the other models to it?

**Comment by dieuwkehupkes** [comment]
One option would be to just construct a model containing the part that is identical for all models and treat this as a layer to construct all other models. 

If you always want to use all nine models anyways, you can also consider merging them into one model in a similar fashion: create the part that is identical for all of them and then add the different upper layers as nine output units to predict everything in one go.

Does that help?

**Comment by mossaab0** [comment]
It is not clear to me how to do that. Can you, please, be more specific? If I start with the following. What should I do next?

    model_1 = load_model('model_1.h5')
    model_2 = load_model('model_2.h5')

Please note that the differences between the models is that they were trained on different datasets. Otherwise, the architectures and the embedding layers are identical.

**Comment by dieuwkehupkes** [comment]
I'll explain to you the second option (because it seems like it would make more sense given that you want all the predictions anyways).

So you have all your loaded models, `model_1, model_2, ..., model_9`. Say the generic part consists of layers 0-n and then layer n+1 - m are the layers that are different for every model. The only problem is here that your layers will have the same names (if you named them)

```
outputs = []
for model in [model_1, model_2, ... ]:
   # apply first non-shared layer to last shared layer taken from model1
   new_layer = model.layers[n+1](model_1.layers[n].output)

   # loop over all non shared layers
    for layer in model.layers[n+2:]:
          new_layer = layer(new_layer)
   
   # add last layer to outputs
   outputs.append(new_layer)

# then create your model:
new_model = Model(input=model_1.layers[0].input, output=outputs)
```

Then you should compile the model.

**Comment by dieuwkehupkes** [comment]
Oh I just discovered that if your layers have names then this will get you into trouble, because no layers can have the same name. In that case you can either loop through a list of names if you still want them to be sensible, or just create dummy names:

```
outputs = []
dummy_name = 'x'
for model in [model_1, model_2, ... ]:
   # apply first non-shared layer to last shared layer taken from model1
   new_layer = model.layers[n+1]
   new_layer.name = dummy_name
   new_layer = new_layer(model_1.layers[n].output)
   dummy_name += 'x'

   # loop over all non shared layers
    for layer in model.layers[n+2:]:
          layer.name = dummy_name
          new_layer = layer(new_layer)
          dummy_name += 'x'

   # add last layer to outputs
   outputs.append(new_layer)

# then create your model:
new_model = Model(input=model_1.layers[0].input, output=outputs)
```

Maybe there is a more elegant way of doing that but I can't come up with something of the top of my head now.

**Comment by mossaab0** [comment]
I like this solution. Thanks @dieuwkehupkes!
