### ISSUE TITLE
[Feature]Input shape api inconsistency with Tensorflow Backend

### ISSUE THREAD

**Issue by manugarri** [fchollet/keras#4150]
When using tensorflow as the backend, there is an inconsistent api format regarding tensor shape.

For example, If i want an input placeholder tensor of shape, `[None, 10]`

In tensorflow I instantiate it as:

`tf.placeholder(tf.float32,shape=[None, 10])`
`In []: <tf.Tensor 'Placeholder_4:0' shape=(?, 10) dtype=float32>`

However if I use the same vector as a shape vector in Keras `Input` tensor:

`Input(shape=[None, 10])`
`<tf.Tensor 'input_3:0' shape=(?, ?, 10) dtype=float32>`

Si it adds an extra dimension. 

Is this the desired behaviour? Not sure if this should be a feature request or a bug to be honest.

**Comment by robertomest** [comment]
It is the desired behaviour because the shape from keras `Input` tensor does not include the batch dimension. If you want to instantiate a tensor with shape `(None, 10)` you cant just instantiate it as `Input(shape=(10,)`. Alternatively you can instantiate it including the batch shape with `Input(batch_shape=(None, 10))`.

**Comment by manugarri** [comment]
got it, so `batch_shape` is the way to go then. Just wanted to make sure since Im starting with Keras and found it confusing. Thanks!
