### ISSUE TITLE
train_on_batch causes really slow process

### ISSUE THREAD

**Issue by ritchieng** [fchollet/keras#4197]
Hi, I've a ResNet that runs fast on Keras when I use the normal `fit` method.

However as I require to use `train_on_batch`, it seems that it's much slower when I do that.

I've an external call, that calls train_on_batch for every iteration.

**Comment by carlthome** [comment]
Perhaps this isn't all that surprising considering `train_on_batch` does some additional checks (_standardize_user_data and _make_train_function in particular, I guess) that you'll be doing on every batch instead of just once for all batches.

See [train_on_batch](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1199) vs [fit](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1002).

You could run a profiler such as [yappi](https://pypi.python.org/pypi/yappi) to see what extra function calls are costing you the noticeable performance difference. What do you see?

**Comment by kilotaras** [comment]
`_make_train_function` is "lazy generator" that is called in fit as well

**Comment by ritchieng** [comment]
I realised my issue was that I did some calculations on
