### ISSUE TITLE
Saving model does not save output_shape in deconv2D

### ISSUE THREAD

**Issue by PPACI** [fchollet/keras#4265]
Hello everyone.
I use keras last version and tensorflow 0.10.

I encoutered an issue with model serialization on disk.

I defined a model like : 
```python
model.add(Deconvolution2D(64,3,3, output_shape=(32, 8, 8, 64),border_mode='same', activation='relu'))
model.add(Deconvolution2D(64,3,3, output_shape=(32, 8, 8, 64), border_mode='same', activation='relu'))
model.add(UpSampling2D(size=(2,2)))
```
(I couldn't use a viariable batch size in output_shape like (None, 8, 8,64) but that's another issue)

everything is fine, i could train, predict, etc.
but when i try to save on disk with `model.save(...)` and load with `keras.models.load_model(...)` i got the following : 
`TypeError: Expected binary or unicode string, got None`

So i checked the saved config file and i got this for the layer previously described: 
```json
{
    "config": {
        "activity_regularizer": null,
        "W_regularizer": null,
        "b_constraint": null,
        "init": "glorot_uniform",
        "nb_filter": 64,
        "nb_row": 3,
        "border_mode": "same",
        "name": "deconvolution2d_1",
        "nb_col": 3,
        "W_constraint": null,
        "b_regularizer": null,
        "trainable": true,
        "output_shape": [
            null,
            8,
            8,
            64
        ],
        "bias": true,
        "activation": "relu",
        "subsample": [
            1,
            1
        ],
        "dim_ordering": "tf"
    }
}
```
Note the `"output_shape": [null,...`

Also, `model.summary()` gave me : `deconvolution2d_2 (Deconvolution2(None, 8, 8, 64)`

So i have two question : 
* Can i save the *real* fixed ouput_shape ?
* Is there a way to use a dynamic batch number in output_shape with conv2d and tensorflow ? (using None gave me the same error in layer definition)

Thanks for all and for this wonderful framework

**Comment by hengyuan-hu** [comment]
Hey, I just ran across the same problem. Here is how I solved it!

First of all, when define the model you should not give it a specific batch_size. But I guess if you use None while defining the model, you will get the same error. Same here.

It actually has nothing to do with keras. If you look at the python trackback carefully, you will see that the error occurs in tensorflow. Notice one line in the traceback:
`File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 276, in conv2d_transpose`

So the real problem is that conv2d_transpose in tensorflow does not accept None as its shape. My solution is to use 'symbolic None' instead. For example, the input the this layer has shape [None, h, w, nb_channel], then you can write `deconv_shape = [tf.shape(x)[0], new_h, new_w, new_channel]`. Pass this deconv_shape to the Deconv layer should work. I use functional API in my model so you may need a bit more tricks to make it work in yours.
