### ISSUE TITLE
Docstrings for interactive users

### ISSUE THREAD

**Issue by lukedeo** [fchollet/keras#427]
Hi @fchollet, 

I find myself (as is the goal in Keras) experimenting with models a lot and running my code interactively both in vanilla `iPython` and in `iPython` notebooks. Frequently, I forget the exact meanings of arguments in the constructors, and I think adding docstrings to make `In [1]: FancyLayerHere?` informative would be super helpful. I know you're focused on substance PRs vs. style / PEP8 nitpicking, but would you be interested in something like this if I pulled it together?

**Comment by phreeza** [comment]
I would like to second this. We can put all the documentation in the docstrings and pull them in, using [mkdocs_autodoc](https://github.com/erichulser/mkdocs_autodoc/).

This would have several advantages:
- docstrings work from interactive environments
- docstrings are discoverable by IDEs, with the correct annotations type inference can be done.
- the proximity of implementation and docstring will serve as a reminder to developers to make appropriate changes to the documentation when needed.

**Comment by fchollet** [comment]
I think it can be valuable. Since it would have significant implications for the docs (changing the way they are built, deployed, kept up to date, and probably forcing us to use different styling), I will take the time to investigate the trade-offs here myself. 

Please no PR for now, I'll get back to it later.
