### ISSUE TITLE
why can't I use SVC in KerasClassifier

### ISSUE THREAD

**Issue by kirk86** [fchollet/keras#4598]
Hi, can someone shed some light on this issue. I've been trying to use the SVC from sklearn with KerasClassifier `model = KerasClassifier(SVC, verbose=1)` but I've been getting this error `AttributeError: 'SVC' object has no attribute '__call__'`. Has anyone else encountered this. I was hopping to use KerasClassifier in order to speed up SVC to use all available cores since its backend utilizes tensorflow but the above error is keeping me away from my goal.

**Comment by jmhessel** [comment]
This isn't exactly a bug, so this question is better asked on the [google group](https://groups.google.com/forum/#!forum/keras-users). If you're interested in using keras to build an SVM, I would first mention that a) you're probably not going to beat the speed of something like liblinear b) if you want to do batch training, you're probably not going to beat the speed of something like vowpal wabbit c) you need to define an SVM in keras, rather than using SVC (which isn't a keras object) an SVM with regularization parameter C in keras can be implemented with a single dense layer.

```
m_svm = Dense(1, W_regularizer=l2(C), activation = 'linear')
... #use m_svm in the model
model.compile(loss = 'hinge', optimizer = 'sgd')
```

**Comment by kirk86** [comment]
@jmhessel thanks a bunch for the useful information. Especially part c) was something I was looking into but since I'm kind of new to keras and used to work directly at theano or tf level I guess it stumbled me for a while.

I agree that SVC is not a keras object but it would be useful to have such a blend.

One last question. If I have a multi class problem and I change the dense layer to `Dense(nb_classes, ...)` would that work as an svm operating on one-vs-all or one-vs-one? Finally since my measure on my problem is the log loss should I change that to be depicted instead of `hinge`. In that case does that stop being an sum?
