### ISSUE TITLE
Models without a defined input size: how to pass training data?

### ISSUE THREAD

**Issue by fusionlove** [fchollet/keras#4610]
Hi,

I'm using a CNN without shape parameters which can accept any size of input image.

However, I can't see how to pass input data of different sizes. I can't use a normal Numpy array, since this would constrain all images to be the same size.

I've also tried using a list, which doesn't seem to work.

Should I use a Numpy array with dtype object? Is there a particular convention for passing images of different sizes?

Cheers,
Fintan

**Comment by Wha1e** [comment]
Unless I am mistaken, I believe a model must have a well defined input shape.  This means that you cannot build a CNN whose input layer changes dimension during runtime.

From the docs: 

> input_dim: dimensionality of the input (integer). This argument (or alternatively, the keyword argument input_shape) is required when using this layer as the first layer in a model.

An alternative solution would be to convert all of your image data to a consistent shape by scaling them, then creating a model that accepts as input this new input shape.

**Comment by vision-mcgm** [comment]
Hi Tristan,

It's possible to build convolutional layers without defined input size:

https://github.com/fchollet/keras/issues/1920

This is because filters can be scanned over any size image. It's the fully-connected layers which must have a defined size.

I've verified this by building a model with just convolutional layers, and using it to predict individual images. It's how to do this in a batch that I don't understand - because as I see it, a batch must be a Numpy array, which constrains each image to be the same size.

I'm wondering if I can pass differently-sized images as a list (doesn't seem to work), or a dict, or something.

**Comment by crowsonkb** [comment]
Use a batch size of 1?

**Comment by fusionlove** [comment]
I suspect this would be really inefficient for training...

**Comment by yhenon** [comment]
You have the pass images of the same size in each mini-batch. I usually just vary the size for each minibatch, for example:
minibatch 1: 64x3x224x224
minibatch 2: 64x3x256x256
minibatch 3: 64x3x192x192

**Comment by fusionlove** [comment]
Understood, thanks. I'll close this now.

Do you do minibatch training as in fchollet's comment in here?
https://github.com/fchollet/keras/issues/68
