### ISSUE TITLE
Cropping only works on defined-length time sequences

### ISSUE THREAD

**Issue by psmaragdis** [fchollet/keras#4722]
The following example works fine because the input is defined as being of length 4:
```
x = keras.layers.Input( shape=(4,1))
y = keras.layers.Cropping1D( (0,1))( x)
xn = arange( 4)[None,:,None]
print keras.backend.function([x],[y])( [xn])
```
If I change the first line to ``x = keras.layers.Input( shape=(None,1))``, i.e. not specifying the input's length ahead of time, I get the error:

```
/usr/local/anaconda/lib/python2.7/site-packages/keras/layers/convolutional.pyc in call(self, x, mask)
   1679     def call(self, x, mask=None):
   1680         input_shape = self.input_spec[0].shape
-> 1681         return x[:, self.cropping[0]:input_shape[1]-self.cropping[1], :]

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

It seems to me that line 1681 in convolutional.py above should instead be:

```
        return x[:, self.cropping[0]:-self.cropping[1], :]
```
That would allow one to use input sequences of arbitrary lengths, which can be very useful for many time-sequence models. I presume the 2D and 3D variants can be similarly updated.

**Comment by keunwoochoi** [comment]
Agreed. I was not available back then, it is now for both backend. Could you PR?

**Comment by psmaragdis** [comment]
Given that I haven't done that before, I'd rather not. Whoever PR's it should probably fix the 2d/3d versions, which I didn't have the time to look into anyway.

**Comment by keunwoochoi** [comment]
Fixed in #4765. Please close this issue.

**Comment by zaccharieramzi** [comment]
Somehow related, I wanted to know whether it was possible to have the Cropping layer potentially accept dynamic cropping (adapt to a potentially changing input shape).

Basically I have an input of undefined shape, and I always want to keep the `n` innermost points. Right now I can't do it because I have to specify the cropping beforehand.

**Comment by keunwoochoi** [comment]
it'd be pretty straightforward if you check out the implementation - just changed the slicing part with what you want.

**Comment by zaccharieramzi** [comment]
I am not sure it's that straightforward. Basically, since I have an undefined input shape, I cannot use it to compute the slice I need (as you mentionned [here](https://github.com/keras-team/keras/issues/4722)).

Just to be clear the function I want to implement has the following all numpy implementation:
```python
def crop_center(img, cropx, cropy=None):
    if cropy is None:
        cropy = cropx
    y, x = img.shape
    startx = x//2 - (cropx//2)
    starty = y//2 - (cropy//2)
    return img[starty:starty+cropy, startx:startx+cropx]
```

So the `call` function of `_Cropping` should look something like:
```python
def call(self, inputs):
        slices_dims = []
        to_crop_shape = inputs.shape[1:rank+1]
        for crop, dim in zip(self.cropping, to_crop_shape):
            start = dim // 2 - (crop // 2)
            end = start + crop
            slices_dims.append(slice(start, end))

        slices = [slice(None)] + slices_dims + [slice(None)]
        slices = tuple(slices)
        spatial_axes = list(range(1, 1 + self.rank))
        slices = transpose_shape(slices, self.data_format, spatial_axes)
        return inputs[slices]
```

But I will have a problem since one of the `dim` will be `None`.

I guess this could work with the eager execution of tensorflow 2.0, but I am really not familiar with that, which is why I am asking.

**Comment by keunwoochoi** [comment]
> But I will have a problem since

I think it's still worth trying. `None` size is still considered as legit during `call` function is executed (e.g., at that point, `size[0]` is `None`).

**Comment by zaccharieramzi** [comment]
Yes but if `size[2]` is also `None`, which is the case for me, then I can't do `size[2] // 2`, which I need to center crop.

**Comment by keunwoochoi** [comment]
oh, i was confused with `call` and `build`.during `build`, it's fine when the size is `None`. during `call`, yes, it needs to know the size, but when `call` is executed don't we know the size anyway? because as far as i know, `call` is called when there's real data and the layer is really used.

**Comment by zaccharieramzi** [comment]
Well in my case I have data with variable sizes coming in: it can be `(36, 640, 322, 1)` or `(35, 640, 372, 1)` (2 examples out of many). It works well because I have a fully convolutionnal network but I would like to crop the center at the end.

**Comment by keunwoochoi** [comment]
yes. i understood that. and you can do it by dynamically finding the center x and y i think, because `call` is called when there's real data - hence no need to worry about the `None` size when the layer is initiated and built.

also, if you're gonna crop the center after some conv layers only, you can crop at the input, if it helps.

**Comment by zaccharieramzi** [comment]
But don't you need to call the layer when building the model?

The way I build models is always in the following fashion (if I were to have a center crop layer, `CroppingCenter2D`):
```python
from keras.layers import Inputs, CroppingCenter2D
form keras.models import Model

x = Inputs((640, None, 1))
x_cropped = CroppingCenter2D((320, 320))(x)

model = Model(inputs=x, outputs=x_cropped)
```

In this case, I need to call the layer on `x` whose shape is not specified. Maybe you were thinking of another way to build a model.

**Comment by zaccharieramzi** [comment]
I managed to build a cropping layer for the center portion of an image using `tf.shape(inputs)` instead of `inputs.shape` (as suggested by [this person](https://github.com/tensorflow/tensorflow/issues/26989#issuecomment-517365016) in this other thread I was involved in).

I don't know if it would be worth it to have a `CroppingCenter2D` layer. If it's the case, I can always make a PR for it.
