### ISSUE TITLE
L2L learning to learn optimizer implementation

### ISSUE THREAD

**Issue by ahundt** [fchollet/keras#4734]
This is a request for an implementation of learning to learn (L2L) as a keras optimizer option published by google deepmind.

paper: https://arxiv.org/abs/1606.04474
TensorFlow implementation: https://github.com/deepmind/learning-to-learn

This may require some design modifications to work with something like the following from the [cifar10_cnn.py](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py) example:
```
# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
```

That is because the MetaOptimizer has to be [tuned for the specific problem](https://github.com/deepmind/learning-to-learn#problems).

**Comment by sarim-zafar** [comment]
Any update regarding this?

**Comment by ahundt** [comment]
I'm sure contributions are welcome.

**Comment by ahundt** [comment]
Low interest, closing

**Comment by Ericvulpi** [comment]
It wouldn't be an optimizer option per say, since the deepmind paper describes an architecture of a meta-optimizer that they have used to create different optimizers optimized for different problems.
I still think it would be interesting to see if they or somone can develop an RNN optimizer using the method deepmind used, but trained on a large enough variety of problems that it becomes general in a way RMSProp or Adam optimizers are, but able to beat these standard optimizers on every use case
