### ISSUE TITLE
what the 'pad = 1' for?

### ISSUE THREAD

**Issue by jedi00** [fchollet/keras#475]
@fchollet : I'm reading the codes of Keras, and I noticed that for every RNN layer, the get_output() function has a line 
```
padded_mask = self.get_padded_shuffled_mask(train, X, pad=1)
```
My question is, why there's 'pad=1' additional padding? If a model consists of stacked RNN layers, this will mean the mask will become longer and longer

**Comment by fchollet** [comment]
@wxs ?

**Comment by wxs** [comment]
It won't keep getting longer and longer! `theano.scan` only loops as much as the shortest input sequence (see docs here: http://deeplearning.net/software/theano/library/scan.html). In every case where we create the padded mask we input both `x` and `mask` to the scan function, and x has the size of the output..

The reason we pad the mask is because this is how the `taps` parameter to `theano.scan` works. Here is a quote from their docs:

```
For example if we use -5, -2 and -1 as past taps, at step 0, fn will require (by an abuse of notation)
 output[-5], output[-2] and output[-1]. This will be given by the initial state, which in this case should have
 the shape (5,)+output.shape. If this variable containing the initial state is called init_y then init_y[0]
 corresponds to output[-5]. init_y[1] correponds to output[-4], init_y[2] corresponds to output[-3], init_y[3]
 coresponds to output[-2], init_y[4] corresponds to output[-1]. While this order might seem strange, it
 comes natural from splitting an array at a given point. Assume that we have a array x, and we choose k
 to be time step 0. Then our initial state would be x[:k], while the output will be x[k:]. Looking at this split,
 elements in x[:k] are ordered exactly like those in init_y.
```

So in the cases where in the scan function we need to know if the *previous* timestep was masked (i.e. all recurrent layers), that corresponds to a tap on the mask at -1. So we need to pad the mask array by 1. But it won't grow for subsequent layers!

Is this clear? Happy to clarify further.

**Comment by jedi00** [comment]
As I understand, each time an RNN layer added, the mask will be augmented by a matrix with shape (pad, nb_samples, 1). So why it won't get longer?

**Comment by wxs** [comment]
No that's not how it works. The padded_mask is never output. It is simply a function of X. The output of the layer is not a function of the mask length because of what I mentioned above: scan iterates to the length of the shortest array.

It's a quirk of the way `scan` works that tap = [0], tap = [-1], tap = [-2] all actually have exactly the same behaviour. Refer to the docs I linked above.

If you passed an unpadded mask into scan then you would be getting `mask_t` at each call to the function, not `mask_tm1`, but `mask_tm1` is what we want.

Does this figure make it more clear?

```
mask            m0  m1  m2  m3  m4

x               x0  x1  x2  x3  x4 

padded_mask     1   m0  m1  m2  m3  m4

scan iteration  0    1   2   3   4

```

We want to align each x_t with m_tm1. Hence the pad. And scan will only iterate as many times as the shortest sequence.

Anyway this is easy to confirm if you want, put in a print of x.shape in each of your layers and you will see that it does not grow. Something like:

```
x = T.dot(X, self.W) + self.b
x = theano.printing.Print('x shape: ')(x, attrs=['shape'])
```

**Comment by jedi00** [comment]
According to Recurrent::get_padded_shuffled_mask() function, firstly the mask from the previous layer will be searched by
```
mask = self.get_input_mask(train)
```
if None is returned, then a
```
mask = T.ones_like(X.sum(axis=-1))
```
will be used instead, and then padded by
```
padding = alloc_zeros_matrix(pad, mask.shape[1], 1) 
mask = T.concatenate([padding, mask], axis=0)
```
It seems the mask should be passed from the previous layer to the following layer, or do I get it wrong? (I do notice there is no get_input_mask() function overriding for every RNN class in recurrent.py, but can not understand the reason)

The padded mask, which in Keras, is not (1   m0  m1  m2  m3  m4 ...). Actually 0 is padded instead, as you can see from the code above.
And, for tap = [0], let's see the code of JZS1:
```
    def _step(self,
              xz_t, xr_t, xh_t, mask_tm1,
              h_tm1,
              u_r, u_h):
        h_mask_tm1 = mask_tm1 * h_tm1  
        z = self.inner_activation(xz_t)
        r = self.inner_activation(xr_t + T.dot(h_mask_tm1, u_r))
        hh_t = self.activation(xh_t + T.dot(r * h_mask_tm1, u_h))
        h_t = hh_t * z + h_mask_tm1 * (1 - z)
        return h_t
```
h_t is updated based on h_tm1, when t=0, h_tm1 is provided by the 'outputs_info' input of theano.scan(); and when t=1, we already have h_0 computed. So I can not figure output why the additional padding of mask is reasonable. Do I get any wrong here too?

**Comment by wxs** [comment]
> Actually 0 is padded instead, as you can see from the code above.

Sorry yes my mistake. Should have written 0 in my figure.

> It seems the mask should be passed from the previous layer to the following layer

It does not pass the padded mask to the next layer. This easy to see. The only place the padded mask is created is in the `get_output()` function, it used internally for some calculations, and then is not returned. The function `get_padded_shuffled_mask` has no side-effects and does not alter the un-padded mask of the layer.

> h_t is updated based on h_tm1, when t=0, h_tm1 is provided by the 'outputs_info' input of theano.scan(); 

Yes `outputs_info` behaves differently from `sequences` in scan. `outputs_info` is designed to provide the result of the previous scan iteration to the next one. `sequences` are pre-computed, as is the case with the mask. 

Certainly a different design would have been to pass an un-padded mask into `scan`, and *also* have the mask in `outputs_info` but a) that would make everything more complicated for no reason (the step function would need to return `h_t, mask_t` just so that the next iteration could get `m_tm1`. Further that design would not be able to handle more complex cases like `SimpleDeepRNN` for which there are multiple taps.

Anyway please try adding a print statement as I described and you will see that the masks do not grow with each layer.

**Comment by jedi00** [comment]
I traced back the `self.previous.get_output_mask()` of `MaskedLayer` class, found that only `Embedding` class returns an output mask, meanwhile all other RNN layers just inherit the `get_output_mask()` from `MaskedLayer` class which will always return None. So, this means only when `Embedding` layer is included in the model then there will be mask transmition process (and all the subsequent layers get the same mask returned by `Embedding` layer); otherwise all RNN layers will just use a self-generated `mask = T.ones_like(X.sum(axis=-1))` as mask without any  mask transmition. Do I get this right?

 As for the padding mechanism, I understand your explanation, my question is whether this pad=1 additional padding necessary? The document of theano.scan() says:
```
outputs_info is the list of Theano variables or dictionaries describing the initial state of the outputs computed recurrently.
If an output is not wrapped in a dictionary, scan will wrap it in one assuming that you use only the last step of the output (i.e. it makes your tap value list equal to [-1]).
```
since the outputs_info is already zero:
```
outputs_info=T.unbroadcast(alloc_zeros_matrix(X.shape[1], self.output_dim), 1),
```
which means (except `SimpleDeepRNN`) the h_-1 is already set to 0, so there should be no need for the pad=1 zero-padding, right?

**Comment by wxs** [comment]
> So, this means only when Embedding layer is included in the model then there will be mask transmition process (and all the subsequent layers get the same mask returned by Embedding layer); otherwise all RNN layers will just use a self-generated mask = T.ones_like(X.sum(axis=-1)) as mask without any mask transmition. Do I get this right?

Yes, though they've added other "mask generation" layers since then, see `Masking` which turns special input values into masks.

> which means (except SimpleDeepRNN) the h_-1 is already set to 0, so there should be no need for the pad=1 zero-padding, right?

No: `outputs_info` is what determines `h_tm1` *not* `mask_tm1`.

We need to pad, because otherwise how would Theano know what value at scan iteration 0 to put for `mask_tm1`?

**Comment by jedi00** [comment]
Thanks @wxs for your generous help, I finally understand this mask padding mechanism.

**Comment by wxs** [comment]
No problem :)

**Comment by placebokkk** [comment]
@wxs 
I found that in SimpleRNN, the mask is applied to T.dot(h_tm1, u))
```python
    def _step(self, x_t, mask_tm1, h_tm1, u):
        return self.activation(x_t + mask_tm1 * T.dot(h_tm1, u))
```

But in GRU and LSTM, the mask is applied to h_tm1 firstly and then the T.dot is calculated.
```python
    def _step(self,
              xz_t, xr_t, xh_t, mask_tm1,
              h_tm1,
              u_z, u_r, u_h):
        h_mask_tm1 = mask_tm1 * h_tm1
        z = self.inner_activation(xz_t + T.dot(h_mask_tm1, u_z))
        r = self.inner_activation(xr_t + T.dot(h_mask_tm1, u_r))
        hh_t = self.activation(xh_t + T.dot(r * h_mask_tm1, u_h))
        h_t = z * h_mask_tm1 + (1 - z) * hh_t
        return h_t
```
I think they have the same effect but the second one is more reasonable.Why not make them consistent?

And for the simpleRNN, I have read you explanation in this thread. But I am still confused with why the left pad is needed. Why not just use this without left padding
```python
    def _step(self, x_t, mask_tm1, h_tm1, u):
        return mask_tm1 * self.activation(x_t + T.dot(h_tm1, u))
```
Please correct me if I am wrong. Thanks very much.
