### ISSUE TITLE
Request: add more trigonometric functions to backend

### ISSUE THREAD

**Issue by brortao** [fchollet/keras#4929]
Both Theano and Tensorflow support (at least) the following basic trigonometric functions that are not currently in `keras.backend`:

- tan
- arccos
- arcsin
- arctan

As far as I can tell, Theano has supported these [since version 0.6](https://theano.readthedocs.io/en/rel-0.6rc3/NEWS.html) and Tensorflow since v0.8.0. It's not listed in the TF release notes, but see [this commit](https://github.com/tensorflow/tensorflow/pull/1573).

It should be simple to add these functions to both Keras backends. Is this a good idea? If so, I'm happy to submit the pull request.

**Comment by bstriner** [comment]
Definitely should be added if it doesn't bloat the backend. Maintaining a giant list of trig functions sounds like a pain.

The function names are the same in both TF and theano. So, if you added one function like `get_backend()` that returned `tf` or `theano.tensor`, then `K.get_backend.sin(...)`, etc., should work for most functions with either backend.

You could also write a fancy loop of function definitions copying functions by name into the backend.

Going even further, you could use `__getattr__` to dynamically check function invocations. That way, `K.tanh` would automatically call `theano.tensor.tanh` or `tf.tanh` if it exists, otherwise throw a missing method.

Honestly, something like that could replace a large chunk of the functions in the backend. Could be an interesting experiment in meta-programming and also clean up the code.

Cheers,
Ben

**Comment by bstriner** [comment]
Seemed like a unique project, so I just put a PR together: https://github.com/fchollet/keras/pull/4932

This adds dynamic dispatching to the keras backend. Existing functions work as they did before. If you try to call a function that isn't in the backend, it will check if the function exists in `tf` or `theano.tensor`.

So, anything listed in theano or tensorflow can be invoked through keras. If someone adds some custom functionality to the backend, your code will transparently start using that custom code instead of the theano or tensorflow function.

Since most functions are relatively straightforward and have the same name, you can instantly write code using arccos or whatever that should work on either backend.

Cheers,
Ben

**Comment by brortao** [comment]
Very nice pull request! I like the idea, and it looks like a clean & simple implementation.

For these trigonometric functions specifically, they have different names in Theano and TF (like `theano.tensor.arccos()` and `tf.acos()`). In these cases, the backends will need custom functions (if people agree that they'd be useful). In that case, here's the PR: https://github.com/fchollet/keras/pull/4939

I'd be interested in finding out how many equivalent functions differ in name in Theano and TF.

**Comment by bstriner** [comment]
Thanks! We could also try an aliasing scheme in cases where we are just doing pass-through. `help` and `dir` still work correctly and then the backend functions are pre-documented. 

Please let me know if anyone can find a downside to just aliasing functions to make it easier to add new functions. Hypothetically, it means one less function call required but shouldn't make a meaningful difference.

For example, add this to theano backend, using fancy python assignment:

```
#Aliases
acos, asin, atan = theano.tensor.arccos,  theano.tensor.arcsin,  theano.tensor.arctan

```
And for tf backend, if I got the names right (writing this on Windows)
```
#Aliases
arccos, arcsin, arctan = tf.acos,  tf.asin,  tf.atan

```

This will simply copy the functions in each backend with the change of names. If you use this together with https://github.com/fchollet/keras/pull/4932, then both backends will have both `arcsin` and `asin` as aliases using one line of code each.

So, if tensorflow or theano comes out with a new function, just start using it. If the other library comes out with the same function, your code will start working on the other library. If the other library has a different name, add an alias to that other library and everything should still work fine.

One of the interesting upsides, is if someone runs `help(K.asin)` or `help(K.arcsin)`, they get the original theano or tensorflow documentation, which is bound to be better than ours.

We would still need to update the keras documentation accordingly.

Cheers,
Ben

**Comment by howthebodyworks** [comment]
OK, so we are now considering

1. putting trigonometric functions in the backends
2. creating some kind of backend dispatch abstractions

Based on #4932 I understand that point 2 is on hold for now;
to return to point 1... Is anyone doing this? 

I need to take a tangent of something right now, so I'm happy to prepare a pull request... if no-one else is in the middle of doing it.

**Comment by brortao** [comment]
I submitted a pull request: https://github.com/fchollet/keras/pull/4939

But I don't think the maintainers are merging new APIs at the moment. For now, it may be easiest just to use `theano.tensor.tan()` or `tf.tan()`.

**Comment by bstriner** [comment]
@howthebodyworks The code @brortao put together should be good for you to use, it just hasn't been merged in yet. Please go like or comment on that PR to help it get through a little faster.

https://github.com/fchollet/keras/pull/4939

To pull his PR into your local keras:
```python
git remote add brortao https://github.com/brortao/keras.git
git fetch brortao
git merge brortao/add_trig_functions
```

Use that trick for any PRs you want that aren't merged in yet.

Alternatively, you could just use `theano.tensor.tanh` directly until something like that gets into the backend.

@brortao Once the contrib repo is off the ground, it should be much easier to get stuff into Keras. If this still isn't in Keras by then we'll put it into contrib.

Keras has got a lot going on with trying to make new releases and integration with tensorflow, so I wouldn't be surprised if PRs are slow for a little while.

Cheers

**Comment by howthebodyworks** [comment]
How weird; your PR didn't show up for me in the search that turned up this issue, @brortao  - nonetheless, nice work.
