### ISSUE TITLE
PyBrain like Dataset Loading

### ISSUE THREAD

**Issue by pranv** [fchollet/keras#495]
The way datasets are loaded in PyBrain seems to be more elegantl and user friendly. I think keras should have something like this.

http://pybrain.org/docs/quickstart/dataset.html

**Comment by fchollet** [comment]
> he way datasets are loaded in PyBrain seems to be more elegantl and user friendly.

I believe the opposite is true. Not having a custom Dataset class that users have to deal with (and which doesn't scale, with a sample-by-sample API) is just about the worst thing I can think of. The best thing I can think of is to use raw numpy arrays (like Scikit-learn, or like Keras). Plugs right into your workflow.  

So what's the argument here?

**Comment by pranv** [comment]
Some ideas:

* Automatic Loading from Files (Folders in Case of images)
* Auto `np_utils.to_categorical()` & other utils. 
* Preprocessing/Data Augmentation

If such an object could be created by passing a file/folder/array and passed directly to `fit()`, I think it would improve UX.

**Comment by fchollet** [comment]
These are useful features, but I think we should be able to add them via util functions, without the user having to deal with the added cognitive load of going through a custom DataSet class.

> If such an object could be created by passing a file/folder/array and passed directly to fit(), I think it would improve UX.

Such polymorphism makes for a nice UX when everything works, but can also be dangerous. First, because because it makes the code more complicated and bug-prone, and second because it does operations that were not explicitly requested by the user. This can hide critical errors from the user, do things they didn't expect, etc. Polymorphism should be used with parsimony; explicitness is good even if it creates more verbosity.

**Comment by pranv** [comment]
> Polymorphism should be used with parsimony; explicitness is good even if it creates more verbosity.

I can agree with that.
