### ISSUE TITLE
Deconvolution2D padding

### ISSUE THREAD

**Issue by DonghyunK** [fchollet/keras#4997]
Hi, I think there is a bug in Deconvolution2D.

I run the example code in the tutorial, 
----
model = Sequential()
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 3, 14, 14), border_mode='valid', input_shape=(3, 12, 12)))
-----
The output shape is equal to (3, 14, 14). according to the formula,
s (i - 1) + a + k - 2p = 1 (12 - 1) + 0 + 3 - 0 = 14 (s = stride, i = input size, a = user -defined, p = padding)

However, If I add padding layer, 
----
model = Sequential()
model.add(ZeroPadding2D((1,1), input_shape=(3, 12, 12)))
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 3, 14, 14))
-----

The output shape should s (i - 1) + a + k - 2p = 1 (14 - 1) + 0 + 3 - 2 = 14

However, keras produces an error, "ValueError: impossible convolution output dim: expected 32x3x12x12 but received gradient with shape 32x3x14x14"

I think that Deconvolution2D does not count pad for calculating output shape. 

Do you what happens?

The error can be resolved if I use moder_mode = 'full', and I don't understand this one too.

Thanks,

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [o ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ o] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [o] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [o] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by patyork** [comment]
I was unable to reproduce this issue, with Theano 0.8.2 and a dim_ordering manually set to 'th':

```python
from keras.models import Sequential
from keras.layers import ZeroPadding2D, Deconvolution2D
from keras import callbacks
import numpy as np

model = Sequential()
model.add(ZeroPadding2D((1,1), input_shape=(3, 12, 12), dim_ordering='th'))
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 3, 14, 14), border_mode='valid', dim_ordering='th'))

model.compile(loss='mse', optimizer='adam')

print 'Actual Output Shape: ', model.predict(np.ones((1, 3, 12, 12))).shape
# >> Actual Output Shape:  (1, 3, 14, 14)

print 'Training completed successfully?:', isinstance(model.fit(np.ones((1,3,12,12)), np.ones((1,3,14,14)), nb_epoch=1, verbose=0), callbacks.History)
# >> Training completed successfully?: True
```

Could you please try to run the above code, exactly as it is? It should produce the same print statements that are in the `#comments`

**Comment by DonghyunK** [comment]
Hi, @patyork. Thank you for your answer.

I used Theano 0.8.2 and Keras 1.2.0

I run the code that you posted it and I got this error message,

  File "C:\Users\DD\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-d717cdd1d0b5>", line 12, in <module>
    print 'Actual Output Shape: ', model.predict(np.ones((1, 3, 12, 12))).shape
  File "C:\Users\DD\Anaconda2\lib\site-packages\keras\models.py", line 723, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "C:\Users\DD\Anaconda2\lib\site-packages\keras\engine\training.py", line 1229, in predict
    batch_size=batch_size, verbose=verbose)
  File "C:\Users\DD\Anaconda2\lib\site-packages\keras\engine\training.py", line 907, in _predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\DD\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 957, in __call__
    return self.function(*inputs)
  File "C:\Users\DD\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\DD\Anaconda2\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Users\DD\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
ValueError: impossible convolution output dim: expected 1x3x12x12 but received gradient with shape 1x3x14x14
Apply node that caused the error: GpuDnnConvGradI{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 31
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x00000000277F3240>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(3, 3, 3, 3), (1, 3, 14, 14), (1, 3, 14, 14), 'No shapes', (), ()]
Inputs strides: [(27, 9, 3, 1), (0, 196, 14, 1), (0, 196, 14, 1), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x00000000276DAD80>, 1.0, 0.0]
Inputs name: ('kernel', 'grad', 'output', 'descriptor', 'alpha', 'beta')

**Comment by patyork** [comment]
My apologies, I cannot force this error on Ubuntu at all. I also see no mention via google of anyone having this issue before..

**Comment by gvtulder** [comment]
If you get that error, I don't think you're using Theano 0.8.2 but a recent development version. The example script might work in Theano 0.8.2 because it doesn't check whether the output shape makes sense. The current development version does check the shapes for consistency and will raise the exception you're seeing.

The padding in the formula refers to the padding value that you pass to the deconvolution function, not to any padding that has been added before. With `border_mode='valid'`, the padding is set to `(0, 0)`. After the `ZeroPadding2D` layer, the image shape is `14 x 14`, so the output of the `Deconvolution2D` layer should be 14 - 1 + 3 = 16 and not 14.

**Comment by DonghyunK** [comment]
Hi, @gvtulder. Did you run the code that @patyork posted?

and how do you pass the padding parameters?

Thanks.

**Comment by patyork** [comment]
@gvtulder I agree that this looks like it is the dev Theano branch (that error message was added fairly recently). However, based on both the formula, and the actual output from Theano 0.8.2 and Tensorflow 0.11, the output shape from the model is indeed `(1, 3, 14, 14)` (when taking the dim_ordering into account). [This paper](https://arxiv.org/abs/1603.07285) really helped me get an intuitive understanding of the Deconv operation, and also provides all of the math.

**Comment by gvtulder** [comment]
@patyork: Thanks for the link to the paper.

Perhaps I'm making a mistake somewhere, but I'm still not convinced that the output should be 14 and not 16.

First: I wouldn't trust Theano 0.8.2 too much, because it more or less gives you any output you ask for. If you ask for `(16, 16)` it also works. It also depends on the backend: 14 works with `device=gpu`, but it gives me an error if I set `device=cpu`.
TensorFlow might do something similar (I haven't checked the code). You checked 14 in 0.11, where it works. TensorFlow 0.12.0-rc1 I have here gives me an error if I ask for 14, but works with 16.

As for the formula, I think the padding refers to the padding of the bottom of the convolution (i.e., the output of the deconvolution).

> The output shape should s (i - 1) + a + k - 2p = 1 (14 - 1) + 0 + 3 - 2 = 14

Suppose that `p` is the padding of the top (the input of the deconvolution). Then giving the deconvolution a _larger_ input (i.e., increasing `p`) would produce a _smaller_ output. That wouldn't make sense to me, so I think `p` is the padding of the bottom.

@DonghyunK: Yes, I ran @patyork's script. It doesn't work for me with the current Theano master, or with TensorFlow 0.12-rc1. If I change the output shapes from 14 to 16 it works.

**Comment by patyork** [comment]
I'll try to do a deeper explanation later, but it's very possible that newer theano breaks Kera's theano implementation of the deconv. Suffice it to say that `output_shape` with Theano backend, currently, is just a guide (note: the code below relies on a currently open PR to fix 'tf' ordering for deconv on theano):
![image](https://cloud.githubusercontent.com/assets/1304633/21906713/390a0dc8-d8c1-11e6-997a-10900e332412.png)

**Comment by gvtulder** [comment]
Thanks, I look forward to the explanation. :) With `input_shape = (12, 12, 3)` and no `ZeroPad` an output shape of 14 is correct, I agree.

> Suffice it to say that `output_shape` with Theano backend, currently, is just a guide

That is often true, but not always. (I assume 'currently' refers to Theano 0.8.2.) It depends a bit on the convolution implementation, because some implementations do use the given shape as an strict instruction. In particular, this is true for [these lines](https://github.com/Theano/Theano/blob/7f1c36774f7c5163cf83790a44df6775244cf5da/theano/sandbox/cuda/dnn.py#L1358-L1362) in the implementation using cuDNN. I don't remember if there were other implementations that also did this. ([This PR](https://github.com/Theano/Theano/pull/5267) started explicitly checking the shapes, but that was after 0.8.2.)

Example script:
```python
from keras.models import Sequential
from keras.layers import ZeroPadding2D, Deconvolution2D
import numpy as np
model = Sequential()
model.add(ZeroPadding2D((1,1), input_shape=(3, 12, 12), dim_ordering='th'))
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 3, 8, 16), border_mode='valid', dim_ordering='th'))
model.compile(loss='mse', optimizer='adam')
print model.predict(np.ones((1, 3, 12, 12))).shape
```

Run with Theano 0.8.2, cuDNN available.
* With `device=cpu`, the output shape is `(1, 3, 16, 16)`. It ignores the `output_shape`. Values > 16 also work, that doesn't change the result.
* With `device=gpu`, the output shape is `(1, 3, 8, 16)` (if using cuDNN). Asking for a shape > 16 gives a cuDNN error, at least on my system.

So with Theano 0.8.2, the results you get depend on your environment and `device` settings.

**Comment by patyork** [comment]
So, I don't have time for a full example, but I'll just point out an inconsistency in what you've stated so far:

> After the `ZeroPadding2D` layer, the image shape is `14 x 14`, so the output of the `Deconvolution2D` layer should be 14 - 1 + 3 = 16 and not 14.

The `ZeroPadding2D((1, 1))` layer we are talking about applies what is called "half" or "same" padding; that is, the `padding = floor(kernel/2) = floor(3/2) = 1`. An alternate way to write this is `k = 2p + 1`  The paper I linked to, in section 4.4.1 on page 21 gives a formula for this exact situation:

```
output_size = input_size + (kernel_size -1) - 2*padding
# given k = 2*padding + 1 in this situation
output_size = input_size + (2*padding +1 -1) - 2*padding
output_size = input_size
```
For your statement that the output size must be 16, it follows, according to the equation above, that the input size must also be 16. We know for a fact that it is not. Depending on how you look at it, the input size (and therefore the output size, again) is either:
- 12 
  - If we don't include the half/same zero padding as actually a part of the input
- 14
  - If we do include the zero padding as a part of the input

I don't think the paper ever states whether or not `i'` should contain the padding values in its size or not, which is fairly annoying. Hopefully you can take it from there, realizing that you can now **Convolve** both of those 2 possible shapes, remove the border, and see which one gives us a Convolved and DePadded shape of 12. In pseudocode:
```
ZeroPad((1,1), input_size=(12,12))
DeConvolve(3, 3, 3, ...)
# we are now at an output size of either (12,12) or (14,14)
Convolve(3, 3, 3, input_size=????)
RemoveZeroPad((1,1))
# Which shape (12 or 14) gives us back our original input shape of (12,12)?
```

**Comment by gvtulder** [comment]
I think that the `padding` in your formula should be the padding that was applied to the input of the forward the convolution. So that would be the padding that should be removed from the output of the deconvolution, not the padding that is added to the input of the deconvolution. Since the deconvolution is using `border_mode='valid'`, `padding` should be 0. So then we'd be in 4.3 and not in 4.4.1.

The forward convolution example you give is quite useful, I think. My answer to your question "which shape (12 or 14) gives us back our original input shape of (12, 12)?" would be 16:

1. Input shape: 16.
2. Valid convolution with kernel size 3 (no padding).
3. Shape after convolution: 16 - 3 + 1 = 14.
4. Remove zero padding (1 on each side).
5. Final shape: 14 - 2 = 12.

But it seems we're going in circles. I find this an entertaining thought exercise, but I'm going to give up for now. (Thanks again for the link to the paper, it's a nice overview.)

**Comment by patyork** [comment]
@DonghyunK Did the example DeConv (without the ZeroPadding layer) work for you? If so, just setting `border_mode='same'` should be equivalent to having that Zero Padding layer with a 3x3 kernel.

@gvtulder I am feeling the same way. I've been looking at DeConv all day and am getting eyesore from it. One thing I don't think I've mentioned: the difference between the No padding and Zero padding equations is just the `- 2p`, which I take to mean something along the lines of "get rid of the padding from the input shape"; meaning `i` includes the padding and the `-2p` gets back rid of it (obviously with 0 padding that term just drops out, making it interesting when there's padding). That said, I think I could now argue for your view as well.

Just an interesting note: DeConvolution is implemented as the derivative of a Convolution, making the derivative that Theano/TF creates for the DeConv, again, a simple Convolution. Very circular and neat, IMO.

**Comment by DonghyunK** [comment]
@patyork I reinstall theano 8.0.2. I have same output shape that you posted. I want to upsample so that border_mode = 'same' is meaningless to me.
@gvtulder, Do you how to pass the padding parameter to the Deconv? I think Zeropadding does. So, if you simply use border_mode ='valid', p can be changed.

**Comment by patyork** [comment]
@DonghyunK border_mode='same' essentially applies a (1,1) zero padding. It should be equivalent to your original question, and it should provide the same output shape. But, if installing 0.8.2 worked, then it is a moot point.

Also, there is no way to pass padding params to the DeConv layer; the standard zero paddings ( like (0, 0),  (1,1), (kernel size - 1, kernel size-1)) are available as the `border_modes` 'valid', 'same', and 'full' respectively,

**Comment by gvtulder** [comment]
@DonghyunK: As @patyork writes, Keras doesn't let you pass a custom padding to the Deconv layer.

> Do you how to pass the padding parameter to the Deconv? I think Zeropadding does. So, if you simply use border_mode ='valid', p can be changed.

No, I don't think that's entirely correct, unfortunately. ZeroPadding just makes your input image larger, so it increases the `i` in your formula, it doesn't change `p`. Moreover, `p` refers to the padding of the forward convolution, so it's the padding that will be removed at the end of the deconvolution. In the equations in [the paper @patyork linked](https://arxiv.org/pdf/1603.07285v1.pdf) (for example, Relationship 13 or Relationship 14) they use `p' = k - p - 1` for the padding that you apply to the deconvolution input.

If you want to compute the output given a padding `p'` before deconvolution, I think you could rewrite Relationship 14 a bit:

> o' = s (i' - 1) + a + k - 2 p
> o' = s (i' - 1) + a + k - 2 (k - p' - 1)
> o' = s (i' - 1) + a - k + 2 p' + 2

where o' is the deconvolution output, i' is the deconvolution input, k is the kernel size, p' is the padding applied before deconvolution and a in {0, ..., s - 1}.

**Comment by DonghyunK** [comment]
@patyork  @gvtulder  Can we only use the padding as the "border_mode" offers?  Because only way to pass padding parameters to the Deconv layer is to use a "border_mode"

**Comment by gvtulder** [comment]
@DonghyunK: Theano supports custom padding as the `border_mode` but the Keras Deconv layer does not. TensorFlow supports only `valid` or `same`, so I'm not sure if support for custom padding would be added. You can still add the zero-padding afterwards, of course.

**Comment by kushia** [comment]
Hi,
Excuse me to interrupt you like this, but I see than in your codes, you use output_shape with a None size for the batch_size.
When I try it, I got this error : TypeError: Expected binary or unicode string, got None

I'm working with Tensorflow in backend, maybe that's why ?
Or maybe not, do you know how to fix it ?

**Comment by DonghyunK** [comment]
@kushia Yes, I think it is due to Tensorflow. You may use 1 instead of None.

**Comment by kushia** [comment]
@DonghyunK :
Thanks for you answer.
I tested it, but failed with :  
```
InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInput: input and out_backprop must have the same batch size
	 [[Node: conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv2d_transpose/output_shape, transpose, Reshape_4)]]

```

My model is : 
```
def generator_model(BATCH_SIZE):
    model = Sequential()
    nch = 256
    reg = lambda: l1l2(l1=1e-7, l2=1e-7)
    h = 5
    model.add(Dense(input_dim=100, output_dim=nch * 4 * 4, W_regularizer=reg()))
    model.add(BatchNormalization(mode=0))
    model.add(Reshape((4, 4, nch)))

    model.add(Deconvolution2D(256, h,h, output_shape=(None,8,8,256 ), subsample=(2,2)))
    model.add(BatchNormalization(mode=0, axis=1))
    model.add(LeakyReLU(0.2))

    model.add(Deconvolution2D(256, h,h, output_shape=(None,16,16,256 ), subsample=(2,2)))
    model.add(BatchNormalization(mode=0, axis=1))
    model.add(LeakyReLU(0.2))

    model.add(Deconvolution2D(64, h,h, output_shape=(None,32,32,64), subsample=(2,2)))
    model.add(BatchNormalization(mode=0, axis=1))
    model.add(LeakyReLU(0.2))

    model.add(Convolution2D(3, h, h, border_mode='same', W_regularizer=reg()))
    model.add(Activation('sigmoid'))
    model.summary()
    return model
```
