### ISSUE TITLE
How to convert eeg data to the Keras training data?

### ISSUE THREAD

**Issue by YuetianLiu** [fchollet/keras#5038]
I am a new learner of Keras. I want to classify the eeg data by Keras. But I don't know how to convert the eeg data to Keras.

**Comment by mbotumbo** [comment]
You are probably going to have trouble getting help here because most people here don't use EEG data. 

To give you a basic direction to go in, though: ultimately when you've created and compiled your network, keras is going to be expecting numpy objects as input. So, a better direction to look in would be how to read EEG data in python and get it into numpy arrays. Once you've managed that, you'll need to figure out the most appropriate network for processing your data. (e.g. if a single EEG sample is a time series of vectors, you might consider a 1d convolutional approach or a recurrent neural network). You may find that you need to slice your data in some way to work with it.
