### ISSUE TITLE
Good news, Tensorflow chooses Keras!

### ISSUE THREAD

**Issue by kli-nlpr** [fchollet/keras#5050]
Keras is gaining official Google support, and is moving into contrib, then core TF. If you want a high-level object-oriented TF API to use for the long term, Keras is the way to go.

http://www.fast.ai/2017/01/03/keras/

**Comment by faroit** [comment]
👎 that would probably mean that theano support is dropped in near future. 

Maybe @fchollet can speak about these plans here?

**Comment by hubayirp** [comment]
👊

**Comment by patyork** [comment]
@faroit @fchollet works for Google - pretty sure this is his initiative. I highly doubt he will be deleting the Keras github library here, purging all the theano code, and just moving the TF related code to the TF library.

**Comment by faroit** [comment]
>  I highly doubt he will be deleting the Keras github library here, purging all the theano code, and just moving the TF related code to the TF library.

Lets talk again in 1y, but I highly doubt this decision would allow have both low level libs be first class citizens in keras. There will be TF-only features that will not get backported to theano. And at one point the theano compatible version will significantly diverge from the tf-version so that it become too hard to maintain both.

**Comment by patyork** [comment]
@faroit In that case, you should probably start writing a theano replacement for keras now, before that happens.

Talk to you in a year.

**Comment by farizrahman4u** [comment]
Our contributions though... :(

**Comment by fchollet** [comment]
> pretty sure this is his initiative

In fact this is not my initiative, it was decided by the TF leads at Google. But I do believe this is absolutely the way to go.

To set the record clear: Theano support will continue for as long as Keras exists, because Keras is meant as an *interface* rather than as an end-to-end framework. In fact, we will even expand the multi-backend aspect of Keras in the future: for instance Microsoft is working on a CNTK backend, and I'm excited about what comes out of that initiative. Keras is a front end for deep learning --not a front end for TensorFlow.

> Our contributions though... :(

I don't understand this comment. Can you clarify? Our contributions what?

**Comment by faroit** [comment]
> To set the record clear: Theano support will continue for as long as Keras exists, because Keras is meant as an interface rather than as an end-to-end framework. In fact, we will even expand the multi-backend aspect of Keras in the future: for instance Microsoft is working on a CNTK backend, and I'm excited about what comes out of that initiative. Keras is a front end for deep learning --not a front end for TensorFlow

@fchollet that is strong message to the community and for the devs here. Thanks! When the keras-tf-integration is finished this should def be something I'd put in a blogpost ;-)

**Comment by farizrahman4u** [comment]
> I don't understand this comment. Can you clarify? Our contributions what?

What exactly would happen to this repository? Will this be the Keras home or the tensorflow repo? If tensorflow repo is the new "home" of Keras, then contributors of this repo will loose the credits right? Technically they would have contributions to this repo.. but this repo itself would be obsolete ?

**Comment by faroit** [comment]
> If tensorflow repo is the new "home" of Keras, then contributors of this repo will loose the credits right? Technically they would have contributions to this repo.. but this repo itself would be obsolete..

Also interesting would be to know how exactly these integration would legally look like. Contributions for tensorflow require to sign googles [CLA](https://cla.developers.google.com/about/google-individual?csw=1). So would all keras contributors need to sign this?

**Comment by fchollet** [comment]
@farizrahman4u : nothing happens to this repository. It keeps being the home of Keras, and contributor credits aren't lost. What happens is that a TF-only version of the Keras interface will be added to TensorFlow (this works has already started). The two versions will be coupled but relatively independent.

> Also interesting would be to know how exactly these integration would legally look like. Contributions for tensorflow require to sign googles CLA. So would all keras contributors need to sign this?

You don't need to sign anything to contribute to Keras, that doesn't change. As for any Keras code getting copied over to TensorFlow, that is possible because Keras and TensorFlow have interchangeable OSS licenses.

**Comment by dusenberrymw** [comment]
Congratulations to you and the overall project, @fchollet!  Keras is fantastic! 👍

**Comment by tstandley** [comment]
Does this mean we will have to choose between the Keras in the TF repository and this Keras? Will the TF people attempt to keep the two versions compatible?

**Comment by fchollet** [comment]
Hopefully the two versions will be completely compatible. However, that
remains to be seen.

**Comment by ypxie** [comment]
Just curious, Is it possible to mix keras_tensor with native tensorflow functions without using lamda layer?

**Comment by pianoman4873** [comment]
@fchollet when will it be possible to use the keras in TF's contrib ? I've your demo at Google's dev summit and was very impressed by the api.

**Comment by sun9700** [comment]
@fchollet What's your suggestion to TF beginner, TF.learn or TF.contrib.keras?
The TF offical tutorial is still focus on TF.learn. Will this tutorial be replaced?

**Comment by ahundt** [comment]
[Keras has been merged to tf.contrib.keras](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/keras)

**Comment by sun9700** [comment]
will  tf.contrib.keras be the offical first choice TF API?

**Comment by ahundt** [comment]
fchollet/keras will be a spec, all other locations will be implementations of that spec

**Comment by sahil0094** [comment]
Its been 3 years. Anyone there?
