### ISSUE TITLE
sometimes MLP network does not converge

### ISSUE THREAD

**Issue by bislak** [fchollet/keras#5173]
running Keras MLP for a regression task. Most of the time it runs well, however it happens that when I try with different seeds, sometimes the NN does not converge (it predicts all 0s). I would have expected the result to change with different seeds as it does most of the times that I run it, but to the point of not converging? Could you advise?

I am using the following basic network:
- topology: 1 hidden layer; neurons: in=2xfeatures, hidden=1xfeatures, out=1
- dropout: 0.001 at input
- activation: = all relu activated
- loss: mean_squared_logarithmic_error
- optimization: Adam with default parameters

On the following data:
- 17k points with  34 features

**Comment by ParthaEth** [comment]
@bislak you are going to a local minimum. Somehow perhaps 0 is your regression target mean or something. Why worry if you have a good network most of the times.

**Comment by bislak** [comment]
@ParthaEth thanks for the input. Is a behavior that I don't understand, which I don't like. Even increasing the batch sizes still behaves the same. But yes, not critical!

**Comment by bstriner** [comment]
Predicting all 0s is converging, just converging to 0. You should be looking at your loss when it does that and when it doesn't and comparing the loss. If the loss with 0s is about your loss when its not 0s, then that's why it isn't doing what you want.

Do you get the same results with mean_squared_error or other losses?

Also, you have very few hidden units. What happens when you pump the hidden layer to 256 or something?

Also, you would mainly use dropout after the hidden layers, not after the input layer, with a rate of 0.25 or 0.5. If you're looking to add some noise to input layers, use something like gaussian noise, not dropout.

Finally, relu can sometimes get stuck due to bad initialization. If you switch that out for LeakyReLU, does the problem go away?

Cheers

**Comment by bislak** [comment]
Hi Ben, thank you very much for those tips. I'll try them out and report back.

**Comment by bislak** [comment]
I confirm that increasing the numbers of neurons in the hidden layer as well as removing the dropout from the input layer has solved the issue!
