### ISSUE TITLE
Keras model.predict_stochastic function problem

### ISSUE THREAD

**Issue by zhaowencang** [fchollet/keras#5184]
Hi,

Today, when I use the keras I met the problem dropout_score = model.predict_stochastic ,AttributeError: 'Sequential' object has no attribute 'predict_stochastic'. Where or how can I find the description of the parameter about the function？ 

Thanks！
Peter

**Comment by bstriner** [comment]
predict_stochastic isn't a function anywhere in keras. If you search the code for predict_stochastic there are no results. There is one PR that had a function with that name at one point.

What are you trying to do?

**Comment by ahmaurya** [comment]
Just to add some context, I think the predict_stochastic function was added by Yarin Gal and Riashat Islam for getting uncertainties thru dropout in neural networks of various kinds. I found the function at https://github.com/Riashat/Active-Learning-Bayesian-Convolutional-Neural-Networks/blob/master/ConvNets/keras/models.py It is also used in Yarin's code at https://github.com/yaringal/BayesianRNN/blob/master/Example/sentiment_lstm_regression.py I ended up at Keras github for LSTM uncertainty estimation because Yarin's page mentions that droput in RNNs has been incorporated in Keras: https://github.com/yaringal/BayesianRNN
