### ISSUE TITLE
Embedding fail on Graph

### ISSUE THREAD

**Issue by ipod825** [fchollet/keras#520]
I failed to add an <code>Embedding</code> layer on <code>Graph</code> model.

Here's the code that works:
<pre><code>
from keras.models import Sequential, Graph
from keras.layers.core import Dense
from keras.layers.embeddings import Embedding
lookup = Sequential()
lookup.add(Embedding(2, 1))
lookup.compile(loss='binary_crossentropy', optimizer='sgd')
</pre></code>

And here's the code that fails:
<pre><code>
from keras.models import Sequential, Graph
from keras.layers.core import Dense
from keras.layers.embeddings import Embedding
model = Graph()
model.add_input('input')
model.add_node(Embedding(2,1), input='input', name='emb')
model.add_output(name='output', input='emb')
model.compile('sgd', {'output':'binary_crossentropy'})
</pre></code>

The error message is:
<pre><code>
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    model.compile('sgd', {'output':'binary_crossentropy'})
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 525, in compile
    y_train = output.get_output(True)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/embeddings.py", line 62, in get_output
    out = self.W[X]
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 474, in __getitem__
    return self.take(args[axis], axis)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 506, in take
    return theano.tensor.subtensor.take(self, indices, axis, mode)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2290, in take
    return take(a, indices.flatten(), axis, mode).reshape(shape, ndim)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2268, in take
    return advanced_subtensor1(a, indices)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 509, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 1608, in make_node
    raise TypeError('index must be integers')
TypeError: index must be integers
</pre></code>

Bleeding edge theao is used.

**Comment by fchollet** [comment]
> add_input(name, ndim=2, dtype='int')

will tell the Graph to expect an integer matrix input.

**Comment by cbarokk** [comment]
One problem is when ndim=3. Then you get: 
**Exception: Type "int" can only be used with ndim==2 (Embedding).**
I encountered this when trying to reproduce examples/lstm_text_generation.py using a Graph model instead of Sequential, and then adding an Embedding node before the LSTM node. I don't know how to make this work, so I've asked for help in a [post](https://groups.google.com/forum/#!topic/keras-users/2R_mEinnEcc) to keras-users.
Do you have an idea Francois?
Thanks in advance.
Cyril.

**Comment by baobao7766** [comment]
@ipod825 hi, did you work out the "TypeError: index must be integers" problem? I have that quenstion too.

**Comment by ipod825** [comment]
@baobao7766 , yeah, as @fchollet answered.
<code>add_input(name, ndim=2, dtype='int')</code>

**Comment by baobao7766** [comment]
@ipod825 OK! Thands!

**Comment by baobao7766** [comment]
@ipod825 OK, Thanks!

**Comment by kallewoof** [comment]
When I do this, I am unable to store the graph using to_json, getting a `TypeError: <type 'int'> is not JSON serializable.`

(I tried to use the solution at https://stackoverflow.com/questions/3488934/simplejson-and-numpy-array/24375113#24375113 to address, but then I started getting `RuntimeError: maximum recursion depth exceeded`. Raising max rec to 10k didn't fix that so I suspect something's inf-looping.)

Why wouldn't to_json work just because you switch to an int? I'm confused.
