### ISSUE TITLE
Is CUDA used in callbacks?

### ISSUE THREAD

**Issue by YingweiZhou** [fchollet/keras#5275]
Hi, I added some element-wise matrix calculations at `on_epoch_end()` but it turns quite slow. So I wonder, in my case, is CUDA used in handling these calculations? I'm considering accelerate these calculations by add some CUDA codse into the `callback` function.

**Comment by patyork** [comment]
The data used in the callbacks are not tensors, so unless you've implemented theano/tf functions then the calculations are not done on the GPU.

Also, if you have actually implemented your calculations symbolically, they will probably be slower than just running on the CPU due to the transfer time to the GPU (unless the calculations are large and mostly on matrices).

**Comment by YingweiZhou** [comment]
Thanks  @patyork, Do you think it's useful to move those calculations to optimizer (subclass of an optimizer such as SGD) ?

**Comment by patyork** [comment]
I have no idea what the "calculations" are, so I'd say no.

**Comment by YingweiZhou** [comment]
@patyork  Sorry for my careless, these calculations are matrix multiplications and compute mean, square root from it. For the MNIST dataset, matrix size would be 30000*500. The reason to use numpy instead of Tensors in `on_epoch_end()` is that, I didn't find a way to execute tensor calculations in callbacks and numpy works there. The idea to move it to optimizer is that change numpy formulas to tensors so that I guess the backend `K.function()` maybe make it work.

Sorry for my bad description.
