### ISSUE TITLE
Model visualization

### ISSUE THREAD

**Issue by AziziShekoofeh** [fchollet/keras#5313]
```python
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
```
based on the https://github.com/erocarrera/pydot/issues/126 , It seems it's a Keras problem and maybe Keras need a update in this part. 

I can import pydot.find_graphviz, either using pydot_ng or pydot in my own codes but it is generating the error.  Apparently it's trying to call:

```python
<try:
    # pydot-ng is a fork of pydot that is better maintained.
    import pydot_ng as pydot
except ImportError:
    # Fall back on pydot if necessary.
    import pydot
if not pydot.find_graphviz():>
```
"Firstly, that the line if not pydot.find_graphviz() is reached means that either pydot_ng or pydot was imported. That an ImportError is raised on the next line means that either pydot_ng was succesfully imported, or an older version of pydot. With the current pydot, an AttributeError would have been raised instead by the line if not ...."

**Comment by ctmakro** [comment]
I met this problem before. did you install graphviz? on OSX `brew install` will work, on Windows download the binary from its homepage.

**Comment by AziziShekoofeh** [comment]
Thanks, I have the  graphviz installed and I can run dot -h, too.

**Comment by johnyf** [comment]
@AziziShekoofeh, thanks for reporting the issue here. In support of the OP, I should note that this is a bug in `keras`: https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/keras/utils/visualize_util.py#L13.

The `ImportError` message on this line: https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/keras/utils/visualize_util.py#L14 is inaccurate. By the reasoning above, some `pydot` variant was successfully imported. What cannot be found is GraphViz, not `pydot`.

I recommend the following changes to `keras`:

1. update the lines referenced above to use `pydot == 1.2.3`, following this comment: https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e#commitcomment-18236709, which was implemented in `theano`
2. rephrase the error message
3. remove the dependence on `pydot_ng`
4. possibly add `pydot == 1.2.3` to the `install_requires` of `keras` (https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/setup.py#L13).

Also, [`pydot_ng`](https://github.com/pydot/pydot-ng/tree/master/pydot_ng) is unmaintained (last commit in 2015), in favor of upstream (https://github.com/erocarrera/pydot). The comment "pydot-ng is a fork of pydot that is better maintained." is outdated, it was introduced with https://github.com/fchollet/keras/commit/e5d3abdf09d8c281ca8817b6292a044673ba3007, so before maintenance of `pydot` resumed.

**Comment by johnyf** [comment]
cf also https://github.com/fchollet/keras/issues/3216, which didn't resolve the issue.

**Comment by AziziShekoofeh** [comment]
@johnyf Thanks for the thorough explanation.

**Comment by ViktorM** [comment]
Still have the same error even after installing pydot_ng. OS Windows 10, latest Keras + TF 1.0

**Comment by johnyf** [comment]
@ViktorM please see the comments [above](https://github.com/fchollet/keras/issues/5313#issuecomment-278457653).

**Comment by ftkurt** [comment]
Is there any activity on this issue? I am having difficulty addressing the problem. I have graphviz installed on windows (using anaconda) and also able to import following libraries: `pydot_ng`, `pydotplus` and `pydot`

**Comment by ganav** [comment]
I have spent all day installing and reinstalling all those pydot(latest version), pydot=1.1.0, pydot-ng....but nothing gave difference...python succesfully imports them but cannot run this line (plot_model(rm.model,  to_file=meth + '.png'))  and arises error "cannot import pydot please install bla bla.."
