### ISSUE TITLE
Multiple output model Prediction 

### ISSUE THREAD

**Issue by fouadb66** [fchollet/keras#5331]
I designed a multi-output model  with 3  loss. here is the output of my model: 
output1 = Dense(outoutClaas,activation='softmax')(BT1)
output2 = Dense(outclassL12,activation='softmax')(BT1)
output3 = Dense(outclassL3,activation='softmax')(BT1)
model = Model(input=inputs, output=[output1, output2,output3])

The model training well, but i am getting errors during the prediction:
model.predict(input)
ValueError: Tensor Tensor("Softmax:0", shape=(?, 7201), dtype=float32) is not an element of this graph.
7201 is the number of the classes of the first output. 
My questions is how can it get the prediction from output1, output2, output3, separately? 

Thank you for your help...

**Comment by unrealwill** [comment]
Hello,
Your model should work. and predict the 3 outputs simultaneously.
If you want you can create 3 different models which share the same weights, but not necessarily the same inputs
...Your previous code
model1 = Model( input = [inputsfor1], output = [output1] )
model2 = Model( input = [inputsfor2], output = [output2] )
model3 = Model( input = [inputsfor3], output = [output3] )

**Comment by nijianmo** [comment]
Hi fouadb66, have you solved your question?

I am not sure how you train your models? Since these 3 models share the same layer, I think train the models separately will not lead to global optimal.

**Comment by Euler10** [comment]
@fchollet This is still not solved. Any alternative method to predict the outputs in such a case? Thanks in advance.

@fouadb66 Did you find any solution to this problem?

**Comment by Euler10** [comment]
This issue has been handled in #2397 . The problem is not in output prediction, but occurs when doing inference in a different thread than where you load the model.

Hope it helps.

**Comment by cshenton** [comment]
For reference, since there's two components to the solution.

1. Calling predict from another thread requires pre-compiling the predict function:
```python
from keras.models import Model

# in the main thread
my_model = Model(inputs = [inputs], outputs = [outputs])
my_model._make_predict_function()
# my_model.compile(... if you're doing training as well

# in another thread
my_model.predict(inputs) # should work now
```

2. Calling predict in the context of a callback
This could be either with `asyncio` using `loop.run_in_executor`, or using `concurrent.futures` directly, either way, if you do the above, you'll get told:
```
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().
```
So you'll need to manually carry around a copy of the tensorflow graph that keras creates and use it as context when you do inference in a thread:
```python
import tensorflow as tf
from keras.models import Model

# in the main thread
my_model = Model(inputs = [inputs], outputs = [outputs])
my_model._make_predict_function()
# my_model.compile(... if you're doing training as well
graph = tf.get_default_graph()

# in another thread
with graph.as_default():
    my_model.predict(inputs) # should work now
```

It's a pain, and really should be handled by Keras, but at least it works, so you can do something like serve your keras model using an asynchronous webserver to handle requests, and a threadpool to do the actual inference.
