### ISSUE TITLE
problems about 3D data augmentation

### ISSUE THREAD

**Issue by qinhaifangpku** [fchollet/keras#5334]
hi~ I want to write a data augmentation for 3D data to random rotation and shift before every epoch. 
Anybody there could give me some advice?
thank you very much for your help!

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by unrealwill** [comment]
Hello,
If the problem is calling your data augmentation function before every epoch you can have a look at https://keras.io/callbacks/

Or use a custom generator. 

For a problem specific question, you will probably have more success there : 
"please ask your question on StackOverflow or join the Keras Slack channel and ask there instead of filing a GitHub issue. "
Thank you
