### ISSUE TITLE
Binary Accuracy for multi-label classification discrepancies

### ISSUE THREAD

**Issue by maximus009** [fchollet/keras#5335]
While training, or evaluation, the model returns accuracies in the range of 90%.

However, per-class accuracy (while plotting precision vs recall graph) or the mean average precision is only about 40%.

Can someone please shine some light on why this might be happening?

Thanks in advance.

**Comment by unrealwill** [comment]
Class imbalance could explain it for example.
Imagine you have 90% of class A and 1% class B 1% class C 1% class D, ... 1% class J 
You predict only A 100% of the time. Your model accuracy is thus 90%
But per-class accuracy is much lower.

**Comment by maximus009** [comment]
That's what I wondered too; I have over 20 classes and some of them have a lot more data than other classes; and I am performing a multi-label multiclassification.

I understand the way binary crossentropy loss is calculated for this case; but I wanted to know in a more granular way how the accuracy was calculated. I looked up the implementation and it says that it performs an element-wise equality of the ground truth and predicted labels; and then gives the mean of the result.

I wanted to test that out myself by giving a dummy data to see how it works, but I guess it requires tensors and not numpy arrays (I am sure I ran into some issue like 'object does not have attribute dtype').

Is there any way we could test out the metrics by giving our own data (like sklearn does)?

**Comment by maximus009** [comment]
Thank you! That should surely help. 👍 Closing this issue (for now)

**Comment by keunwoochoi** [comment]
Is it multi-label AND multi-class? If so, prediction False for all value can result in very high accuracy.

**Comment by lipeipei31** [comment]
@maximus009 , could you explain how binary-crossentropy loss is calculated for this case? I noticed very small loss with binary crossentropy but  much larger loss with 'categorical_crossentropy'. The same for accuracy, binary crossentropy results in very high accuracy but 'categorical_crossentropy' results in very low accuracy. I believe it's just how the metrics calculated causing this big difference.

**Comment by maximus009** [comment]
@lipeipei31 I think it depends on what activation you are using. If you are using 'softmax', you should use 'categorical crossentropy'; it does not make sense to use 'binary crossentropy'. 

Binary crossentropy is just a special case of categorical crossentropy, where you deal with 2 classes.

**Comment by lipeipei31** [comment]
@maximus009 Thanks for the response! I agree with you. But I found online that many people suggest 'sigmoid' and 'binary crossentropy' for multi-label classification. When I say multi-label, I mean for one sample, y_target is something like [1,0,0,1,0...]. You mentioned in the post that your problem is a multi-label classification problem. Is it the same as what I understood? Or your y_target is a one hot vector,i.e.[1,0,0,0,0...]. If it's the latter, then I think I am clear how the loss and accuracy are calculated. If it's the former, then I am curious how the loss is calculated if I choose  'binary crossentropy'.

**Comment by myhussien** [comment]
@lipeipei31  the current `binary_crossentropy` definition is wrong. It should be `K.sum(K.binary_crossentropy(y_pred, y_true), axis=-1)` . For the accuracy if you are doing one-vs-all use `categorical_accuracy` as a metric instead of `accuracy`.

**Comment by dminh** [comment]
I agree with @myhussien. The current implementation of binary_crossentropy with K.mean makes the loss very low in the case of multilabel classification. For example, y_target has 100 elements with 99 zeros and 1 one, even though the model predicts all zeros, the loss value is still very low, like 1/100.

**Comment by dminh** [comment]
I do agree with @myhussien. K.mean makes the loss value of binary_crossentropy very low in the case of multilabel classifier. For example, y_target has 100 elements with 98 zeros and 2 ones, the value of loss is something like 2/100 in the case that the model predicts all elements as zeros.

**Comment by jerrypaytm** [comment]
I found the result of the binary_accuracy calculation for multi-label classification is very misleading too.
If you have 100 labels and only 2 of them are 1s, even the model is always wrong (that is it always predict 0 for all labels), it will return 98/100 * 100 = 98% accuracy based on this equation I found in the source code.

```
def binary_accuracy(y_true, y_pred):
    return K.mean(K.equal(y_true, K.round(y_pred)), axis=-1)
```

**Comment by keunwoochoi** [comment]
But the accuracy computation is correct. What matters is if accuracy is a relevant metric when it's about multi-label -- and it is not relevant due to those cases. So it might be misleading, but how could Keras automatically know this? It's user's responsibility to set a correct and relevant metric.

**Comment by jerrypaytm** [comment]
@keunwoochoi You are right. Keras cannot know about this. However, if you google the topic "multi-label classification using Keras", this is the recommended metric in many articles/SO/etc. 
What I'm trying to say is that this metric is misleading for the "multi-label classification" in general especially for when there are many zeros and small number of ones for the labels as I showed in the example.

**Comment by jerrypaytm** [comment]
There are some metrics in sklearn for multi-label classification: http://scikit-learn.org/stable/modules/model_evaluation.html

**Comment by silburt** [comment]
So is there any recommendation for how to get around this issue? For example, I'm trying to train a network to predict binary semantic segmentation (i.e. output a mask with pixel-wise predictions of 0 or 1), however the number of 0's dominate the number of 1's. It sounds like the keras binary cross-entopy is not going to capture the class imbalance as is. Can anyone advise either a different metric or maybe a way to tweak that metric to account for class imbalances? From https://github.com/fchollet/keras/issues/3653 it looks like using sample_weights would work, however the kicker for my problem is I'm using a generator to augment my images, and fit_generator doesn't seem to have a sample_weight option (which makes sense, since the sample weights will change depending on the image augmentation and how to map that correctly isn't trivial..). 

I have something so far like:
```
def weighted_binary_XE(y_true, y_pred):
    y_true_0, y_pred_0 = y_true[y_true == 0], y_pred[y_true == 0]
    y_true_1, y_pred_1 = y_true[y_true == 1], y_pred[y_true == 1]
    s0 = K.mean(K.binary_crossentropy(y_pred_0, y_true_0), axis=-1)
    s1 = K.mean(K.binary_crossentropy(y_pred_1, y_true_1), axis=-1)
    Npix = y_true.shape[0]*y_true.shape[1]*y_true.shape[2]
    return s0*len(i1)*1.0/Npix + s1*len(i0)*1.0/Npix
```

but at the first line in the above snippet I get:
    y_true_0, y_pred_0 = y_true[y_true == 0], y_pred[y_true == 0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 338, in _SliceHelper
    sliced = slice(tensor, indices, sizes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 388, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2001, in _slice
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2312, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1704, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1510, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 621, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, ?, ?) must have rank 1

Any idea how to proceed? Thanks to anyone in advance.

**Comment by saxenarohit** [comment]
What is the right metric to be used in such cases (Multi-label with sparse output vectors)?

**Comment by nsarafianos** [comment]
@silburt Although it has nothing to do with Keras, the [Focal Loss](https://arxiv.org/abs/1708.02002) could be an answer to your question. Otherwise, you can check the weighted_cross_entropy_with_logits function from Tensorflow

**Comment by tjdurant** [comment]
@myhussien Just wanted to point out that your answer seems to be concordant with a recently published paper: [https://arxiv.org/pdf/1711.05225.pdf](url) 

See where they say "sum of unweighted binary cross entropy losses" -- in the section referring to the multi-label classification problem. 

I am still wondering how to implement this type of loss function in Keras. Would it be the following?:

```
def sum_binary_crossentropy(y_true, y_pred):
    return K.mean(K.binary_crossentropy(y_true, y_pred), axis=-1)

parallel_model.compile(
    loss=sum_binary_crossentropy, 
    optimizer=opt,
    metrics=['categorical_accuracy'])

```

And would `metrics` = 'accuracy' or 'categorical_accuracy' ?

**Comment by FrugoFruit90** [comment]
@keunwoochoi what could be used as a metric for a multi-class, multi-label problem?

**Comment by nsarafianos** [comment]
@FrugoFruit90 The best thing to do for such a problem is a) do not compute metrics per batch but per epoch and b) compute F-1 score and mAP for all your samples in the training and validation set for every epoch; which means that you compute independent metrics per label (AP) and then you average across them to get mAP. For F-1 or mAP you can use either the scikit learn implementations or if you want you can check the mAP implementation here: https://github.com/zhufengx/SRN_multilabel/tree/master/tools

**Comment by DanielDIQA** [comment]
> I found the result of the binary_accuracy calculation for multi-label classification is very misleading too.
> If you have 100 labels and only 2 of them are 1s, even the model is always wrong (that is it always predict 0 for all labels), it will return 98/100 * 100 = 98% accuracy based on this equation I found in the source code.
> 
> ```
> def binary_accuracy(y_true, y_pred):
>     return K.mean(K.equal(y_true, K.round(y_pred)), axis=-1)
> ```

Hi,

when dealing with multi-label classification, then don't use categorical_accuracy, because it can miss false negatives. Example:
#   y_true: [1.0, 1.0]
#   y_pred: [1.0, 0.0]
#   ==> categorical_accuracy: 1

binary_accuracy is better suited, but, as you say, not ideal if you have sparse ground truth-vectors.

**Comment by prativadas** [comment]
I am getting higher accuracy value while using binary accuracy as a metric but getting low value while using accuracy as a metric. using dstl kaggle satellite dataset for segmentation problem. Can anyone explain how this metrics are working?

**Comment by rachadlakis** [comment]
maybe  tf.keras.metrics.CategoricalAccuracy(name='accuracy') can be useful
