### ISSUE TITLE
masking problem when output length is different from input

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#5366]
Hi, dear all,

I have two inputs. One is with length of 50, the other one is with the length of 50. I will concatenate them along the time axis. The output length should be same as the input 1 (50). When I use keras and its extension Seq2seq, I define the input length is the summation (50+50) and output is 50.

However, when I use masking layer, it has the error:
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 100, but the output's size on that axis is 50.
**If I remove the masking layer, everything is OK.** Could anyone tell if the masking will see the output and detect the length of the output? Should I make the input and output exactly same long?

Thank you.

**Comment by unrealwill** [comment]
Hello, 

I don't think I understand your question. But it seems you are referring to a problem with https://github.com/farizrahman4u/seq2seq. (project which imho, in its current state, is not faithful to Graves Seq2Seq : it is attempting to solve a much harder problem, and had (last time I checked) several blunders). I recommend not using it and sticking with the tensorflow Seq2Seq implementation, or rolling your own Seq2Seq implementation in Keras which is a good week-end project.

"If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue."
