### ISSUE TITLE
Input Error on Second Layer of Recurrent Example from Doc

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [fchollet/keras#5447]
Running latest Keras 1.2.2, on either TF or Theano...

Code/comment below taken directly from `https://keras.io/layers/recurrent/`

```
model = Sequential()
model.add(LSTM(32, input_dim=64, input_length=10))

# for subsequent layers, not need to specify the input size:
model.add(LSTM(16))
```

Running the first two lines of code above throws no error. Then running the third line throws the following error:  

> "Input 0 is incompatible with layer lstm_2: expected ndim=3, found ndim=2"

...The code (and comment) in the documentation (linked) says that we do not need to specify input size for the second layer, so why am I getting incorrect ndim when I execute the second model.add() statement? Thanks for your time and any help is much appreciated.

(also posted this question on [Stack Overflow](http://stackoverflow.com/questions/42331396/input-shape-error-in-second-layer-but-not-first-of-keras-lstm) )

**Comment by patyork** [comment]
Well, that snippet was not meant to be run standalone; per the comments it's just to show how you can instantiate an LSTM layer in the cases where a) it is the first layer b) it is not the first layer.

To answer the question fully, it is as the error suggests: the second LSTM layer is not getting a 3D input that it expects (with a shape of `(batch_size, timesteps, features)`. This is because the first LSTM layer has (by fortune of default values) `return_sequences=False`, meaning it only output the last feature set at time `t-1` which is of shape `(batch_size, 32)`, or 2 dimensions that doesn't include time.

**Comment by MaxPowerWasTaken** [comment]
Hi patyork, thanks a lot for the very quick reply, that solves my issue. 

In my case, I don't want my network to return_sequences=True. But given your explanation and after tweaking my code, I understand that if I want to stack recurrent layers, I need to at least return_sequences=True on the recurrent layers that feed into subsequent recurrent layers.

**Comment by nadavb** [comment]
If you have 3 stacked LSTMS, make the first two return_sequences=True and only the last one return_sequences=False
