### ISSUE TITLE
border_mode = 'same' in pooling layers still changes the dimentions 

### ISSUE THREAD

**Issue by ypeleg** [fchollet/keras#5448]
I am trying to use a pooling layer (both 1D and 2D) with border_mode = 'same' but it seems to change the dimensions anyway

**Comment by patyork** [comment]
1D: `stride=(pool_length/2)`
2D: `stride=(pool_size[0]/2, pool_size[1]/2)`

Also, this is entirely expected behavior - pooling is generally used to decrease output size, and definitely will when you use the default stride.

**Comment by ypeleg** [comment]
Yes but border_mode = 'same' should ZeroPad back to the original dimensions.

**Comment by patyork** [comment]
Yes, if stride == poolSize / 2. By default, stride == poolSize

-----Original Message-----

**Comment by ypeleg** [comment]
can't i use a different stride size? as far as i know, strides are used to "skip" cells when applying the pooling filter, am i right?

**Comment by patyork** [comment]
Yes, and if you skip cells (more than poolSize/2) you reduce dimensionality.

Draw a picture of a simple example (4x4 image, 2 pool and 2 stride) see what size you end up with when you do no padding, 1 (same) padding, and 2 (full padding). You'll see the dimensionality is reduced in the first 2 cases, but not in the 3rd. However, in the third you'll find that the output has a border of padding, which is essentially the output of border_mode=valid followed with a Padding2D((1,1)) layer. In other words, sure the dimensionality is technically the same, but its because it was padded with zeros..

-----Original Message-----

**Comment by ypeleg** [comment]
Thank you, this is what i was asking. If this is intentional, i just wanted to pad the output with zeros even though it is not at the same dimensions.
I'll just use zero padding layers for this. 

However i still think automatic zero padding should be considered to be added as a border mode.

**Comment by patyork** [comment]
With border mode=full it is exactly what you are asking for: An artificially inflated output size. I don't know if keras allows that border mode in pooling layers, because it is only available in Theano and is equivalent to just padding afterwards. You're right that a subsequent padding layer will accomplish what you need. However, I recommend you still draw a picture so that you understand why the border mode, pool size, and stride interact in the way they do.


Please close this issue, and direct any future implementation/non-bug questions to the Slack channel or Stackoverflow.

-----Original Message-----
