### ISSUE TITLE
 `TimeDistributedDense` for LSTM mean pooling

### ISSUE THREAD

**Issue by MahdiKhodayar** [fchollet/keras#5513]
I'm still confused about the TimeDistributedDense layer. If we add a LSTM layer in the Sequential model and then add the TimeDistributedDense layer, can we do mean pooling on all the "hidden states" of the LSTM for k time steps: t=0, t=1, ... , t=k-1 ? 

I mean is this code doing mean pooling on all the hidden_state_size **hidden states** of LSTM ? 

```
sequence = Input(shape=(max_sent_len,), dtype='int32')
embedded = Embedding(vocab_size, word_embedding_size)(sequence)
lstm = LSTM(hidden_state_size, activation='sigmoid', inner_activation='hard_sigmoid',
return_sequences=True)(embedded)
distributed = TimeDistributed(Dense(1))(lstm)
pool = AveragePooling1D()(distributed)
output = Dense(1, `activation='sigmoid')(pool)`

```

**Comment by unrealwill** [comment]
Hello,

Here you are not doing mean pooling on the  **hidden states** of LSTM (i.e the "memory cell" doesn't have mean pooling).
You are also not doing mean pooling on the output cell of the LSTM.
Layers are computed one after the other.
The whole LSTM calculations are done as usual. 
Then for each time step you apply Dense(1).
Then you "blur" and compress along time using average pooling.

If you want to do mean pooling on the hidden states of LSTM implement your own Recurrent Layer by modifying LSTM but you will probably encounter a lot of difficulties because as RNN are computed timestep after timestep you would need either to implement a CausalAveragePooling using only values from the past, or the ability to use values not already computed (or solve an implicit system).

**Comment by MahdiKhodayar** [comment]
Suppose that I have T instances and each instance contains a time series with lenght N . 
What I am looking for is an LSTM that sees the N data in one instance. While the LSTM is seeing each of the N data, its state changes (N times). I want to have an average over those N outputs captured by LSTM.

**Comment by unrealwill** [comment]
Sorry, I don't understand.
Maybe have a look at https://keras.io/layers/pooling/#globalaveragepooling1d
