### ISSUE TITLE
Modifying GRU code

### ISSUE THREAD

**Issue by griff4692** [fchollet/keras#5596]
Hi -

I am trying to modify the GRU code to handle a fixed scalar vector of the same length as the number of time sequences.

Basically in the step code, I want to modify the returned h to be a weighted average of the new h and the old h.  

`h = self.g[i] * h + (1 - self.g[i])*h_tm1`

I want `i` to represent the time step of the GRU but am unable to figure out how to access that index `i`.  I am instantiating my GRU by passing in a scalar vector `g`.

Any and all help would be much appreciated!

**Comment by unrealwill** [comment]
Hello,

The g should be given as an additional input, as it is a sequence.

The hackish easy way, is to concatenate it to the x, and inside your custom GRU layer, split it back into x and g.
The cleaner way is probably to define multiple InputSpec but I remember playing with it a little but I'm not sure I succeeded. The official doc say input without 's'.

(Rant ON)
IMHO Recurrent Layers in Keras currently are not satisfactory, this probably is because Tensorflow has for a long time lagging behind Theano about scan, though they are catching up, but as usual they are even more lagging with regard to documentation, so it is probably hard to build a compatible API. 
(Rant OFF)

What I currently do, is I encapsulate my recurrent layers as standard layers and I use "scan" inside call, the old school way. There is a little pre-processing to do (which you can copy from K.rnn backend code https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L985 ) and post-processing.

There are have been various attempts to build a generic Recurrent architecture (for example Recurrent shop but which is build on top of K.rnn so it probably won't be useful), so you can get some idea on how to structure your recurrent code correctly, otherwise it will quickly become a mess (although nicely encapsulated in a Layer, so that the mess won't spread).
