### ISSUE TITLE
Transfer Learning and Custom Loss Function.

### ISSUE THREAD

**Issue by GauravBh1010tt** [fchollet/keras#5613]
I am working on transfer learning as described in the paper [Correlational Neural Networks](http://www.mitpressjournals.org/doi/pdf/10.1162/NECO_a_00801).
The architecture of the DNN is 
![1](https://cloud.githubusercontent.com/assets/22491381/23598057/bff58856-025d-11e7-9b76-d2d29d856912.PNG)
The loss function corresponding to the network is given by
![2](https://cloud.githubusercontent.com/assets/22491381/23597749/980cc4b4-025b-11e7-929f-289f6ace8fbd.PNG)
Z = (X,Y), the concatenated vector. If only one representation is given then the other is set to 0. (See the figure below).
Basically, I need my loss function to learn the representation from one view and be able to reconstruct the other view of the data. Here, X and Y are two representations of the data, let's say one is a textual feature and the other is the visual feature. I used functional API to design this architecture and with the help of #2121 and #2662 designed a custom loss function that works. 
- The problem is that the functional API is computing the two output layers independently (as opposed to the sequential model where one loss function is used). According to the above loss equation, I need to share same loss function for both of the outputs(something like sequential models). Is it possible?
- My designed loss function converges smoothly and I am getting some results, which are inferior to the results given in the paper. I do not know what am I missing. In #386 (see the last comment) the results of autoencoder are not good. Does this problem has to do something with my implementation? 

Results from the paper (On MNIST dataset):
![a](https://cloud.githubusercontent.com/assets/22491381/23609168/bcd89dea-0292-11e7-8259-4bbb79e4b529.PNG)
Keras Result:
![b](https://cloud.githubusercontent.com/assets/22491381/23609169/be3765d6-0292-11e7-8fea-f171ecb5e4ff.PNG)

Below is the snippet of custom loss function:
```python
def cornet_loss(params):
    def loss(y_true,y_pred):
        def cor(y1,y2,lamda):
            y1_mean = K.mean(y1, axis=0)
            y1_centered = y1 - y1_mean
            y2_mean = K.mean(y2, axis=0)
            y2_centered = y2 - y2_mean
            corr_nr = K.sum(y1_centered * y2_centered, axis=0)
            corr_dr1 = K.sqrt(T.sum(y1_centered * y1_centered, axis=0)+1e-8)
            corr_dr2 = K.sqrt(T.sum(y2_centered * y2_centered, axis=0)+1e-8)
            corr_dr = corr_dr1 * corr_dr2
            corr = corr_nr/corr_dr
            return K.sum(corr) * lamda

        if params[5] == 'left_model':
            input_l = y_true
            input_r = params[0]
            output_l = y_pred
            output_r = params[1]
        elif params[5] == 'right_model':
            input_l = params[0]
            input_r = y_true
            output_l = params[1]
            output_r = y_pred
        hidden_l = params[2]
        hidden_r = params[3]
        L1_1 = K.mean(K.square(output_l-input_l), axis=-1)
        L1_2 = K.mean(K.square(output_r-input_r), axis=-1)
        L1 = (L1_1+L1_2)/2
        L2_1 = K.mean(K.square(output_l-input_l), axis=-1)
        L2_2 = K.mean(K.square(K.zeros_like(input_r)-input_r), axis=-1)
        L2 = (L2_1+L2_2)/2
        L3_1 = K.mean(K.square(K.zeros_like(input_l)-input_l), axis=-1)
        L3_2 = K.mean(K.square(output_r-input_r), axis=-1)
        L3 = (L3_1+L3_2)/2
        L4 = cor(hidden_l,hidden_r,params[4])
        return L1+L2+L3-L4
    return loss
```
Parameters as defined in the paper: - hidden_neurons = 50, inp_dim = 392, lamda = 2, l_reg = 0.01, optimizer = rmsprop.  
``` python
model.compile(loss=[cornet_loss([input_r,output_r,hidden_l,hidden_r,lamda,'left_model']),
                        cornet_loss([input_l,output_l,hidden_l,hidden_r,lamda,'right_model'])],
                  optimizer=rmsprop,
                  metrics=['accuracy'])
```
Because the loss function is being called two times for each output layer, I feel that might be causing inconsistency during backpropagating the weights.  If this is the case what can be a possible remedy?

**Comment by unrealwill** [comment]
Hello,

Here is what I would do : 
The first three terms are tree usual losses. The correlation term is more like a regularization term.

You can then handle it like I explained in : 
https://github.com/fchollet/keras/issues/5563

**Comment by GauravBh1010tt** [comment]
@unrealwill - I think the actual problem is with losses L2 and L3 because they enforce the model to reconstruct the other view. I had run some experiments with L1+L2+L3 and the result by Keras' model is somewhat bad(that means the correlation term is dominant for reconstruction the other view as per cornet_loss above). On the other hand, the actual CorNet is able to give good performance using these 3 losses (or just L2+L3).  That means there is some issue while transferring the information to the loss function (can be in the implementation of cornet_loss).
Wel, l I have my bet on a single loss function and will try out your solution. If my speculation regarding a single loss function is correct, then this will do the job, otherwise, I'll have to figure out something else.

**Comment by unrealwill** [comment]
I don't see any fundamental problem with the way you were computing the loss.

Are you sharing the layers weights properly? ( https://keras.io/getting-started/functional-api-guide/#shared-layers )

I'm not familiar with the paper Correlation Neural Network.
I skimmed quickly through it and wrote an implementation which I believe capture the gist of it. (There are small differences like bias). It runs and hopefully is ok, but I've not tested for convergence yet (My machines are busy).

Running but not tested code (may be buggy) : 

```
import numpy as np
from keras.models import Model
from keras.layers import Input, Merge

import keras.backend as K
from keras.engine.topology import Layer
from keras.layers.core import  Activation, Dense

from theano import tensor as T


class ZeroLike(Layer):
    def __init__(self, **kwargs):
        super(ZeroLike, self).__init__(**kwargs)

    def call(self, x, mask=None):
        return K.zeros_like(x)

    def get_output_shape_for(self, input_shape):
        return input_shape

class MultiplyBy2(Layer):
    def __init__(self, **kwargs):
        super(MultiplyBy2, self).__init__(**kwargs)

    def call(self, x, mask=None):
        return 2*x

    def get_output_shape_for(self, input_shape):
        return input_shape


class CorrelationRegularization(Layer):
    def __init__(self,lamda, **kwargs):
        super(CorrelationRegularization, self).__init__(**kwargs)
        self.lamda = lamda

    def cor(self,y1, y2, lamda):
        y1_mean = K.mean(y1, axis=0)
        y1_centered = y1 - y1_mean
        y2_mean = K.mean(y2, axis=0)
        y2_centered = y2 - y2_mean
        corr_nr = K.sum(y1_centered * y2_centered, axis=0)
        corr_dr1 = K.sqrt(T.sum(y1_centered * y1_centered, axis=0) + 1e-8)
        corr_dr2 = K.sqrt(T.sum(y2_centered * y2_centered, axis=0) + 1e-8)
        corr_dr = corr_dr1 * corr_dr2
        corr = corr_nr / corr_dr
        return K.sum(corr) * lamda

    def call(self ,x ,mask=None):
        h1=x[0]
        h2=x[1]

        corr = self.cor(h1,h2,self.lamda)

        self.add_loss(corr,x)
        #we output junk but be sure to use it for the loss to be added
        return h1

    def get_output_shape_for(self, input_shape):
        return (input_shape[0][0],input_shape[0][1])

def zero_loss(y_true, y_pred):
    return K.zeros_like(y_pred)


def buildModel():
    hdim = 300
    dimx = 100
    dimy = 200

    inpx = Input(shape=(dimx,))
    inpy = Input(shape=(dimy,))

    hx = Dense(hdim)(inpx)
    hy = Dense(hdim)(inpy)

    h = Activation("sigmoid")( Merge(mode="concat")([hx,hy]) )

    recx = Dense(dimx)(h)
    recy = Dense(dimy)(h)

    branchModel = Model( [inpx,inpy],[recx,recy,h])

    inpx = Input(shape=(dimx,))
    inpy = Input(shape=(dimy,))

    [recx1,recy1,h1] = branchModel( [MultiplyBy2()(inpx), ZeroLike()(inpy)])
    [recx2,recy2,h2] = branchModel( [ZeroLike()(inpx), MultiplyBy2()(inpy) ])

    #you may probably add a reconstruction from combined
    #[recx3,recy3] = branchModel([inpx, inpy] )

    corr=CorrelationRegularization(-1.0)([h1,h2])

    model = Model( [inpx,inpy],[recx1,recx2,recy1,recy2,corr])
    model.compile( loss=["mse","mse","mse","mse",zero_loss],optimizer="adam")

    return model


def trainModel(m):

    nbSamples = 1000

    hdim = 300
    dimx = 100
    dimy = 200

    x = np.random.randn(nbSamples,dimx)
    y = np.random.randn(nbSamples,dimy)

    m.fit( [x,y] , [x,x,y,y,np.zeros((nbSamples,hdim))] )

m = buildModel()
trainModel(m)
```

**Comment by unrealwill** [comment]
Edited previous code

**Comment by GauravBh1010tt** [comment]
Hi @unrealwill, 
I wrote the script and got some results. That cleared one of my initial doubt. Although Keras' functional API computes the loss functions independently but it aggregates all the losses prior to gradient computation. 
I used the method described in the paper to create the experimental setup.  
![u2](https://cloud.githubusercontent.com/assets/22491381/23666506/3397c6b0-0381-11e7-90ef-955ec5db084a.PNG)
As you can see the model is able to achieve comparable results when L4 or the correlation loss is not being used, but the performance drops when I use the L4 term. So, that means there is something wrong in the correlation computation.
I have few queries related to your code above:
- what does the following lines in your code do? Can you explain how the **call** module is being used here?
```python
 self.add_loss(corr,x)
        #we output junk but be sure to use it for the loss to be added
        return h1
```
I returned the corrnet loss as computed by the function:
```python
        corr = self.cor(h1,h2,self.lamda)
        return corr
```
Did I returned the correct variable? 

- You multiplied the inputs by a constant that is 2 here, I don't think it is needed. I have computed the above results without using the multiplication.

**Comment by GauravBh1010tt** [comment]
There is some issue while sharing the layer's weights. According to the paper, only the bias term is shared. I don't think Keras allows sharing of only the biases across multiple layers. Is there a way to do that?

**Comment by unrealwill** [comment]
About : 
```
 self.add_loss(corr,x)
        #we output junk but be sure to use it for the loss to be added
        return h1
```
This is the new way to write regularization terms. The add_loss line is the important one.
What you returns doesn't matter as we ignore it using zero_loss (But you should use the result of the Layer so that the Layer and add_loss is used during the construction of the symbolic graph). Usually you can return something meaningful, like corr but here it has not the right zeroth-dimension (number of samples) to be compatible so it would probably crash later on.

Regarding the multiply by 2, it's not needed when you have 2 view and you only show one, but it's an homogenization term (kind of what is done with dropout)

About why the Correlation term might be problematic, is that is computing some statistics on a mini-batch of size 32 if you leaved the default on. I copied/pasted your correlation code. I'm not sure it is a bias-less estimator of the correlation. 

Regarding the bias term, you could compute the Denses Layer without bias and create a custom Layer which just add bias, and sum them.

**Comment by GauravBh1010tt** [comment]
If the zero_loss is suppressing any return, I wonder how the error by the correlation term is getting added to the actual loss?
I think inside zero_loss the **y_pred** term is the output of the **CorReg**. So, if I output the **corr** from the **CorReg** and simply return this value from the zero_loss, then will it be added to the final loss?

**Comment by unrealwill** [comment]
That's the magic hack of the function "self.add_loss(corr,x)".
You remove all other losses and see that the total loss will not be zero (check-it).
Alternatively if you do not trust this you can return a term but it will need to have the same number of examples as the input, or keras will not be happy, so you will probably have to repeat somehow the loss.

**Comment by GauravBh1010tt** [comment]
That's really cool stuff. This also allows us to use more than one regularization term in a single loss function which is easy to debug. 
I'll be doing some more experiments today and will update here.

**Comment by GauravBh1010tt** [comment]
@unrealwill - I think Keras' model is working now. Final results are as follows:

![u3](https://cloud.githubusercontent.com/assets/22491381/23702922/5d7cf1d8-0423-11e7-99e6-e0996d1e8f17.PNG)

Regarding the **CorReg**:

- I passed the scalar term **corr** from **CorReg** to **Zero_loss**, and from there simply returned the value. I believe we don't have to worry about the shape of **y_pred** if we enforce the custom function **Zero_loss** to returns a scalar value (that is essentially the loss or cost for current batch).

- One problem with CorReg is that the correlation term is computed for full batch (as opposed to the actual implementation, where it is computed for one sample). I solved this problem by normalizing **lamda** (I simply divided **lamda** by **batch_size**).  So, the value of **lamda** used by the Keras' model is 0.02 (instead of 2, **batch_size** = 100).

I just have one last issue:
The normalization of **lamda** is kind of hack. Can you suggest something generic (that doesn't tend to convergence issue later on)?

**Comment by unrealwill** [comment]
Glad you got it to work.

You probably can divide corr by K.shape( h1 ) [0] to do the normalization automatically so you can have lamda independent of batch_size . 

Thanks for reporting back :)

**Comment by GauravBh1010tt** [comment]
I appreciate all your time and efforts for helping me out. 👍

**Comment by mdmustafizurrahman** [comment]
@unrealwill Hope you are fine. I would like to implement a custom loss function described in this [paper](https://arxiv.org/pdf/1612.04898.pdf) page 2 equation 2. 

Now the problem in in Keras custom loss function I need access to the individual input sample so that I can weight the second term of the equation and also calculate KL-divergence. Is it possible to access the individual sample in custom loss function? 
Will wait for your reply.

**Comment by mdmustafizurrahman** [comment]
@GauravBh1010tt : can you help me to implement the a custom loss function described in this paper page 2 equation 2. I desperately need help for it. I only need the second part. All other are done.

**Comment by GauravBh1010tt** [comment]
@mdmustafizurrahman - hey, apologies for a late reply. I am really busy these days so I couldn't reply to your query even though I have seen it a week ago. 
Regarding your problem, I am not sure about the exact computations of _**t**_ and _**p_theta**_. Provided these are computed using neural transformations you can create a combination of losses as follows:
```python

class KLDCost(Layer):
    def __init__(self,reg_param=1, **kwargs):
        super(KLD, self).__init__(**kwargs)
        self.reg_param = reg_param

    def call(self ,x ,mask=None):
        h1=x[0]
        h2=x[1]
        y_1 = K.clip(h1, K.epsilon(), 1)
        y_2 = K.clip(h2, K.epsilon(), 1)
        kld_loss = self.reg_param * (K.sum(y_1 * K.log(y_1 / y_2), axis=-1))
        return kld_loss

    def get_output_shape_for(self, input_shape):
        #print input_shape[0][0]
        return (input_shape[0][0],input_shape[0][1])

class loss2_layer(Layer):
    def __init__(self,inp_size,out_size, **kwargs):
        super(loss2_layer, self).__init__(**kwargs)
        self.k = out_size
        self.test_out = 0
        
    def build(self,input_shape):
        self.W = self.add_weight(name='w',shape=(self.k,),
                                 initializer='glorot_uniform',
                                  trainable=True)                   
        super(loss2_layer, self).build(input_shape)     

    def call(self ,x ,mask=None):
        h1=x[0]
        h2=x[1]
        y_1 = K.clip(h1, K.epsilon(), 1)
        y_2 = K.clip(h2, K.epsilon(), 1)
        kld_loss = self.reg_param * (K.sum(y_1 * K.log(y_1 / y_2), axis=-1))
        loss2_product = self.W*kld_loss
        return loss2_product

    def compute_output_shape(self, input_shape):
        return (input_shape[0][0],self.k)

def build_model():
    t =  computing the t param in equation 2
    p_theta = computing the p_theta_x using combination of dense layers
    loss1 = KLDCost()([t,p_theta])
    
    u = uniform distribution
    k = hyperparameter at term 3 in equation 2
    loss3 = KLDCost(reg_param=k)([t,p_theta])

    p_theta_i = computing the p_theta_x_i using combination of dense layers
    p_theta_j = computing the p_theta_x_j using combination of dense layers
    
    loss2 = loss2_layer()([p_theta_i,p_theta_j])

    model = Model( [inpx,inpy],[loss1,loss2,loss3])
    model.compile( loss=["KLD","KLD","KLD"],optimizer="rmsprop")
    return model
```

Hope this helps,
best regards.

**Comment by mdmustafizurrahman** [comment]
@GauravBh1010tt  Thanks a lot for your help. Basically t_i is the y_true label which is a delta distribution .e.g. of we have three class then t_i could be (1,0,0) and p_theta is the output from the network which is basically y_pred and again a distribution. 

From your solution it looks like you set W (eq 2, part, 2)as a trainable parameter, but W is basically weigtmetrx from the graph and it is not learn-able and is fixed for a batch, I need to pass it as a parameter to the custom loss function. And based on different batch, I need to pass different W.

For P_theta_i and P_theta_j, it is basically the same y_pred, so we can set P-theta_i = y_pred and P-theat_j = y_pred. So basically we need to take one element (which is basically a distribution ) from P_thetha_i and one element from  (which is basically a distribution ) P_theta_j and compute the KL Divergence between those. As a result if y_pred is of size 3, output should look like:

(1,1),(1,2),(1,3)
(2,1),(2,2),(2,3)
(3,1),(3,2),(3,3)
  
Since we are calculating KLD all the diagonal element should be zero. Now we need compute elemet wise matrix multipication between the above computed matrix and the W matrix that we provided as a parameter in custom loss function. 

I am providing the code what I have done so far, can you confirm whether it is correct?

`'''Trains and evaluate a simple MLP
on the Reuters newswire topic classification task.
'''
from __future__ import print_function

import theano
from keras import backend as K
from keras.layers import Input, merge
from keras.models import Model
from copy import deepcopy
from sklearn.metrics import f1_score

# Dynamic background setup
import os


def set_keras_backend(backend):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        reload(K)
        assert K.backend() == backend


set_keras_backend("theano")

import numpy as np
import keras
from keras.datasets import reuters
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.preprocessing.text import Tokenizer
from keras.engine.topology import Layer
from keras.layers.core import Dense
from keras.regularizers import Regularizer
from keras import objectives
from keras import regularizers

max_words = 1000
batch_size = 32
epochs = 5

print('Loading data...')
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=max_words,
                                                         test_split=0.2)

x_train = x_train[0:1000,]
y_train = y_train[0:1000,]
x_test = x_train[0:100,]
y_test = y_train[0:100,]

print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

num_classes = np.max(y_train) + 1
print(num_classes, 'classes')

print('Vectorizing sequence data...')
tokenizer = Tokenizer(num_words=max_words)
x_train = tokenizer.sequences_to_matrix(x_train, mode='binary')
x_test = tokenizer.sequences_to_matrix(x_test, mode='binary')
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)


'''
instance_to_index = {}
counterIndex = 0
for instance in x_train:
    instance_to_index[str(instance)] =  counterIndex
    counterIndex = counterIndex + 1
print('hashmap shape:', len(instance_to_index))
'''


print('Convert class vector to binary class matrix '
      '(for use with categorical_crossentropy)')
y_train = keras.utils.to_categorical(y_train, num_classes)
original_y_test = deepcopy(y_test)
y_test = keras.utils.to_categorical(y_test, num_classes)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

print('Building model...')

# model = Sequential()
# model.add(Activation('relu'))
# model.add(Dropout(0.5))
# model.add(Activation('softmax'))
# input = input_shape=(max_words,)

# np.random.uniform(0,1,5)

def custom_loss(input, weightInput):
    def loss(y_true, y_pred):


        #input1 = input
        #input2  = input
        #weights, updates = theano.scan(
        #    lambda input1, input2: input1, sequences=[input1, input2])

        # Part 1
        # supervised lost  D(t_i || p(x_i))
        # only for the labeled data point
        # assume that y_true will be all zeros [0,0,0, .. ]
        # for the unlabeled points
        # if y_true is all zero then np.nonzerocount will return 0, where we will simply put y_true in the tensor
        # otherwise we calculate the KL-divergences between each non_zero y_true and y_pred

        eps = 0.0001
        results, updates = theano.scan(
            lambda y_true, y_pred: (y_true + eps) * (K.log(y_true + eps) - K.log(y_pred + eps)) if np.count_nonzero(
                y_true) != 0 else y_true,
            sequences=[y_true, y_pred])
        L1 = K.sum(results, axis=- 1)

        # part 2

        # uniformDist = b = K.random_uniform_variable(shape=(num_classes), low=0, high=1)
        # L4 = objectives.kullback_leibler_divergence(y_pred, uniformDist)
        # kle2 =  K.sum(objectives.kullback_leibler_divergence(y_pred, uniformDist))


        # kle = objectives.kullback_leibler_divergence(y_pred, y_true)
        # L2 = K.mean(kle)

        # kle = objectives.kullback_leibler_divergence(y_pred, y_pred)
        # weightMatrix = np.random
        # L2 = K.sum(kle * y_pred, axis=-1)


        eps = 0.0001
        y_pred1 = y_pred

        '''result, update = theano.scan(
            lambda y_pred, y_pred1: (y_pred + eps) * (K.log(y_pred + eps) - K.log(y_pred1 + eps)),
            sequences=[y_pred, y_pred1])



         '''

        #result1 = objectives.kullback_leibler_divergence(y_pred, y_pred)

        initial_result = theano.tensor.alloc(np.array(0), num_classes)

        def rnn_step(y_pred, y_pred1): # y_pred vector and y_pred1 is matrix
            result2 = theano.scan(
                lambda y_pred1, y_pred: (y_pred + eps) * (K.log(y_pred + eps) - K.log(y_pred1 + eps)),
                sequences=[y_pred1], non_sequences=y_pred)
            return result2



        # y_pred and y_pred1 both matrix, first scan take one instance of y_pred and pass the whole y_pred1 as non seqenece to the secodn scan
        result1, updates1 = theano.scan(
            rnn_step,
            sequences=[y_pred],
            non_sequences=[y_pred1]
        )

        print (K.shape(result1))
        # weightMatrix = np.random.rand(8982,8982)
        # y = K.placeholder(shape=(3, 4))
        #weightMatrix = K.random_uniform_variable(shape=(global_size, global_size), low=0, high=1)
        result1Final = K.sum(result1, axis=-1)
        weightMatrix = weightInput
        #L2 = K.sum(K.dot(weightMatrix, result1Final), axis=-1)

        L2 = K.sum(np.multiply(weightMatrix,result1Final), axis=-1)

        uniformDist = np.random.uniform(0, 1, num_classes)

        L3results, L3updates = theano.scan(
            lambda y_pred, uniformDist: (y_pred + eps) * (K.log(y_pred + eps) - K.log(uniformDist + eps)),
            sequences=[y_pred], non_sequences=uniformDist)

        L3 = K.sum(L3results, axis=- 1)

        #L3 = objectives.kullback_leibler_divergence(y_pred, uniformDist)

        # return L1

        return L1 + L2 + L3

    return loss

#now the model will take as input arrays of shape (*, max_words)
#The most common situation would be a 2D input with shape (batch_size, input_dim). # batch_size is the number of instance in the input

input = Input(shape=(max_words,), name='input')
weightInput = Input(shape=(x_train.shape[0],), name= 'weights')
hd1 = Dense(256, activation='relu')(input)
out1 = Dense(num_classes, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(hd1)
model = Model(inputs=[input, weightInput], outputs=out1)
# Y_train = np.append(y_train, x_train, axis=-1)
# Y_test = np.append(y_test, x_test, axis=-1)
'''
print (len(Y_train[1]))
print (Y_train[0][0:45])
print (len(Y_train[0][46:]))
print (Y_train[0][46:])
'''
model.compile(loss=[custom_loss(input=input, weightInput=weightInput)], optimizer='adam', metrics=['accuracy'])

weightMatrix = K.eval(K.random_uniform_variable(shape=(x_train.shape[0], x_train.shape[0]), low=0, high=1))
#weightMatrix = np.random.random(x_train.shape,x_train.shape)

for epoch in range(10):
    print('epoch %d' % (epoch))
    model.train_on_batch({'input': x_train, 'weights': weightMatrix}, y_train)
    model.test_on_batch({'input': x_train, 'weights': weightMatrix}, y_train)

'''
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_split=0.1)
'''


# for test all weight matrix is ZEROS
weightMatrix = K.eval(K.zeros(shape=(x_train.shape[0], x_train.shape[0])))
prediction_distribution = model.predict({'input': x_test,'weights': weightMatrix})

y_pred = []
for distribution in prediction_distribution:
    y_pred.append(np.argmax(distribution))

print(f1_score(original_y_test, y_pred, average='macro'))


# score = model.evaluate(x_test, y_test, verbose=1)
# print('Test score:', score[0])
# print('Test accuracy:', score[1])


`

**Comment by raginisharma14** [comment]
@GauravBh1010tt I am also trying to solve a similar problem of adding intermediate loss layers, and i see an error like this
"if (output_shape[-1] == 1 or
IndexError: tuple index out of range"
in the model.compile. 
Here is my model.compile: 'model.compile(optimizer=opt,loss=['categorical_crossentropy', 'categorical_crossentropy', zero_loss],metrics=['accuracy'], loss_weights=[1.,0.0, 1.0])'

**Comment by alono88** [comment]
@GauravBh1010tt , @unrealwill 
I have built a similar architecture and tried to test my implementation by using Lamda = 0. Thus, the network should learn exactly the same as if I didn't include the regularization term at all. 

However, my network is showing different results with Lamda = 0 and without the regularization. Do you have any experience with this issue?

**Comment by GauravBh1010tt** [comment]
@alono88 - Have a look at this implementation - [CorrNet](https://github.com/GauravBh1010tt/DeepLearn/tree/master/CorrNet).

**Comment by alono88** [comment]
@GauravBh1010tt  Thank you very much.
