### ISSUE TITLE
Image Segmentation

### ISSUE THREAD

**Issue by KushalJ08** [fchollet/keras#5646]
I am working on Brain tumor Segmentation MRI images using CNN. but i don't know how to implement segmentation in cnn ?

Please help me with this.

Thanks
KJ

**Comment by unrealwill** [comment]
If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

You just have to make one prediction per pixel. So the output of your model should be an image with nb_labels channel.
