### ISSUE TITLE
setting any sample_weight = 0 causes dimension mismatch when using masks

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#573]
At some point this branch was added to the `weighted_objective` function:

```
else:
            # We assume the time index to be masked is axis=1
            wc = masked_weights * obj_output
            wc = wc.reshape(mask.shape)
            wc = wc.sum(axis=1) / mask.sum(axis=1)
            return wc.mean()
```

however the reshape will fail in the event that any of `sample_weight` are zero, because `obj_output` is filtered to only the nonzero `sample_weight`s. We're working on a fix, opening an issue here in case anyone else has beens truggling with this.

**Comment by EderSantana** [comment]
@wxs I wrote that for the cost function masking I mentioned you before. I don't think you are supposed to use both `sample_weights` and `mask` together since they try to do the same thing. Obviously, the fix should take care of checking when the user tries to input both. I believe `sample_weight` should block that branch if it is passed as input.

**Comment by fchollet** [comment]
Even so there is currently an implementation conflict, `sample_weight` and `mask` are two conceptually distinct features and should be usable at the same time...

**Comment by EderSantana** [comment]
I see... in that case we have to filter the `mask` only to the `non_zero` elements as well.

**Comment by wxs** [comment]
I've opened a PR #592  with a potential fix. It was a bit more involved since there were also some issues around the `mean()` calculations and their interactions with both masks and weights.
