### ISSUE TITLE
Siamese network with multi-input shared base-network

### ISSUE THREAD

**Issue by haoyangz** [fchollet/keras#5914]
**I wish to use Siamese network to distinguish a (text, image) pair from another similar pair.** 

I was following the official Siamese network [example](https://github.com/fchollet/keras/blob/master/examples/mnist_siamese_graph.py) in which the basenetwork takes only one input. To take multiple input, I made the following change to *create_basemodel()* using "Functional API in Keras" following instructions [here](https://keras.io/getting-started/functional-api-guide/):

```
def create_basemodel():
    image_input = Input(shape=(4, 1, 101))
    text_input = Input(shape=(2,))

    conv1 = Conv2D(64, 1, 5, border_mode='same', input_shape=(4,1,101), \
                               activation='relu')(image_input)
    max1 = MaxPooling2D(pool_size=(1, 5),strides=(1,3),border_mode='same')(conv1)
    image_output = Flatten()(max1)

    concat = concatenate([image_output, text_input])
   
    f1 = Dense(32, activation='relu')(concat)
    f1_drop = Dropout(0.5)(f1)
    f2 = Dense(2, activation='softmax')(f1_drop)
    
    model = Model(inputs=[image_input, text_input],outputs=[f2])
    return model
```

And in the main function I did:

```
image_input_a = Input(shape=(4, 1, 101))
text_input_a = Input(shape=(2, ))
image_input_b = Input(shape=(4, 1, 101))
text_input_b = Input(shape=(2, ))
basemodel = create_basemodel()
processed_a = basemodel(image_input_a,text_input_a)
processed_b = basemodel(image_input_b,text_input_b)
```

The last two lines gave me the error `__call__() takes exactly 2 arguments` . 

If I instead do:

```
processed_a = basemodel((image_input_a,text_input_a))
```

This gave me `ValueError: Layer model_1 expects 2 inputs, but it received 1 input tensors. Input received: <built-in function input>`.

It seems either way, I can't neither provide one input tensor or two tensors. I am wondering what would be the correct way to implement Siamese network with **multi-input shared base-network** as is in my case?

**Comment by haoyangz** [comment]
Using list instead of tuple fixed it.

```
processed_a = basemodel((image_input_a,text_input_a))
```

**Comment by shashankg7** [comment]
@haoyangz . How did you use the processed_a object? When I pass an input to it, I am getting error. Could you please give an example?

**Comment by tharuniitk** [comment]
@haoyangz I am facing a similar issue. could u pls check here.

I was running the following reproducible script to train a parallel multiple CNN's model each CNN with its own input. I receive the following error when I run the model in keras with tf backend. The screenshot of error is attached. Kindly help. My OS is Ubntu 14.04, Cuda 8.0. There are issues (kuza55/keras-extras#14) already present on a similar problem but it doesn't solve the error received when I run this script. Please help resolve!!

from keras.models import Sequential, Model
from keras.layers.embeddings import Embedding
from keras.layers.core import Activation, Dense, Dropout
from keras.layers import Merge, Conv1D, Conv2D, Flatten
from keras.layers.recurrent import GRU, LSTM
#from keras.datasets.data_utils import get_file
import tarfile
import numpy as np
from keras.callbacks import EarlyStopping
from workshop_utils import tokenize, parse_stories, get_stories, vectorize_stories
from keras import optimizers
import tensorflow as tf
import scipy.io
from keras import backend as K
from keras.layers import Input

import keras
nb_filters =20
kernel_size1= [1,64]
kernel_size2= [64,1]

no_parallel_CNN = 10
create seperate model graph for parallel processing with different filter sizes
apply 'same' padding so that ll produce o/p tensor of same size for concatination
cancat all paralle output

#https://stackoverflow.com/questions/43172122/easy-way-of-representing-multiple-inputs-in-keras
input1=np.random.rand(5169,30,125,1)
input2=np.random.rand(5169,30,125,1)
input3=np.random.rand(5169,30,125,1)
input4=np.random.rand(5169,30,125,1)
input5=np.random.rand(5169,30,125,1)
input6=np.random.rand(5169,30,125,1)
input7=np.random.rand(5169,30,125,1)
input8=np.random.rand(5169,30,125,1)
input9=np.random.rand(5169,30,125,1)
input10=np.random.rand(5169,30,125,1)
y1=np.random.rand(5169,1)

input_shape=(30,125,1)
inp1 = Input(shape=input_shape)
inputs_list = [Input(shape=(30,125,1)) for i in range(no_parallel_CNN)]
conv_1_list = [Conv2D(filters = 32, kernel_size = (1,64) , padding = "same" , activation = "relu" )(input_tensor) for input_tensor in inputs_list]
conv_2_list = [Conv2D(filters = 32, kernel_size = (64,1), padding = "same" , activation = "relu" )(input_tensor) for input_tensor in conv_1_list]
print len(inputs_list)
print inputs_list

if no_parallel_CNN > 1:
out=keras.layers.concatenate(conv_2_list)#out = Merge(mode='concat')(conv_2_list)
else:
out = conv_2_list[0]

conv_model = Model(input=inputs_list, output=out)

m1=Sequential()
m1.add(conv_model)
m1.add(Dropout(0.2))
m1.add(Flatten())
m1.add(Dropout(0.2))
m1.add(Dense(1000,activation='relu'))
m1.add(Dropout(0.2))
m1.add(Dense(500,activation='relu'))
m1.add(Dropout(0.2))
m1.add(Dense(1, activation='sigmoid'))

m1.compile(loss='mean_squared_error', optimizer='RMSprop')

early_stopping = EarlyStopping(monitor='val_loss', patience=2)
#with tf.device('/gpu:0'):
m1.fit([input1,input2,input3,input4,input5,input6,input7,input8,input9,input10], y1, validation_split=0.5, callbacks=[early_stopping])

![error_layer_expects_multipleinputs_but_receivedone](https://user-images.githubusercontent.com/18737816/34724743-006ca062-f575-11e7-8ff7-01db6f12be99.png)
