### ISSUE TITLE
Keras 2. - resnet training speed

### ISSUE THREAD

**Issue by oak-tree** [fchollet/keras#5989]
Description
-----------------------
I used to transfer learning from Resnet50, basicly retrain it with some different top network above it. It worked just fine. But now with Keras 2 it seems that it takes forever. I'm using `Tesla K80` and the code is runs on GPU ( I ran `sudo watch nvidia-smi` to verify that GPU is actually being used and it does)

I checked both `Tensorflow` and `Theano` backend. I'm getting huge number like 1151049s per epoch. Which means around 13 days! Where before the update I got around 4000s per epoch

Any ideas what can be the cause for that? 

Thanks!

Some details
-----------------------

1) Ubuntu 16 LTS
2) I'm using fit_generator
3) Tesla K80
4) tested with keras 2.0.1 and 2.0.2
5) Theano - update from branch master
6) Tensorflow - 1.0.1
7) Running python mnist_cnn.py from `example` takes aroudn 8s per epoch on `Theano` backend

- [Done ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [Done] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [Done] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Pekka4444** [comment]
Hi,
Just a wild guess:

In release notes it says:
"The methods fit_generator, evaluate_generator and predict_generator now work by drawing a number of batches from a generator (number of training steps), rather than a number of samples."

So can it be that you didn't change the value of argument when moving from "number of samples" to "number of batches".  That would explain it because your epochs would be batchsize times longer.  

Please check.

**Comment by oak-tree** [comment]
Wow! I have missed that! Thanks
