### ISSUE TITLE
How to get the current step number in recurrent layers?

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#6020]
I need to know the exact position in the sequence of word, not just the embedding vector. 

Is it possible to update the step number by states? Or is it possible to perform scan on the word id sequence?

**Comment by unrealwill** [comment]
Hello,

You can probably create your own layer.

```
#With Theano Not Tested (Not even Runned)
class Position(Layer):
    def __init__(self, **kwargs):
        super(Position, self).__init__(**kwargs)

    def build(self, input_shape):
        super(Position, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, x):
        shp = K.shape(x)
        ran = theano.tensor.arange(0,shp[1],1,dtype="int32")
        sx = K.zeros_like( K.sum( x,axis=2) )
        return sx + K.expand_dims(ran,0)

    def compute_output_shape(self, input_shape):
        return (input_shape[0], input_shape[1])

To use :
x = Input( batch_shape=(None,timesteps,featuredim) )
p = Position()(x)
m = Merge(mode="concat", concat_axis=2)([x,p])
gru = GRU( ...) (m)
model = Model( x,gru )
```
Though it probably won't work, as you expect
Because neural networks prefer one hot representations, or embedding representation of your integer.

For one hot, then you can't have a variable number of timesteps (and you just return an eye matrix).
For embedding representation, you create a shared_weight emb in your position layer and you return sx+ K.expand_dims(emb[0:shp[1] ],0)

Alternatively you can use a carefully initialized and freezed SimpleRNN, (just use a circulant matrix, and (1,0,...0) as initial state ), but it will be slower.
