### ISSUE TITLE
image generator exposure/contrast

### ISSUE THREAD

**Issue by kootenpv** [fchollet/keras#6111]
It appears there is no way to alter exposure / contrast with the image generator? Is there a reason this is not included? It would seem very useful to be part of generation of artificial images.

**Comment by crimedude22** [comment]
I suppose the reason might be that that level of image manipulation would be out of the scope of keras. Did you mean randomly adjust exposure/contrast for the sake of data augmentation? If so, both exposure and contrast are linear adjustments and don't add any new information: exposure is just a scale change so your (assumedly convolutional) network shouldn't care, and increases/decreases in contrast should wash out to neutral during training. If anything you'll be decreasing the information in the image through saturation/rounding errors. The *independent* random jittering values across channels already implemented instead actually increases the information in the dataset since the relationship between the channels is changed (recall that a filter in a conv. network is actually LxWxC, or a 3 '2D kernels' per 'filter'). If you still want to randomly expose/contrast your images, you can pass a function that takes a 3-dimensional numpy array to preprocessing_function, or define a function to do so in the preprocessing/image.py file and add it to the ImagePreprocessing class and the relevant .next() call in the iterator classes, 

If you just mean a global adjustment for the sake of *changing* the dataset rather than augmenting it, you can do that:
You can adjust 'exposure' (although that's not really a well-defined term in digital images) in a way that's similar but not exactly the same as photoshop using the 'rescale' argument. Digital exposure adjustment is essentially a multiplying channel intensities (in RGB space) or the value (in HSV space) by a constant - higher starting values grow/shrink by more than lower values, as opposed to a brightness adjustment which adjusts all values by the same amount. Photoshop does a bit of interpolation but that's about all that's different afaik.

Contrast is also a linear change, essentially doing the same thing as exposure adjustment except you subtract the median pixel value before doing the multiplication and then add it back in afterwards (see here: http://math.stackexchange.com/questions/906240/algorithms-to-increase-or-decrease-the-contrast-of-an-image). You can do this with a keras function (and actually just scaling it should be all the same to the network if you're centering/scaling the data) not sure why you would want to do that unless the light/dark values are intrinsically meaningful though.

**Comment by kootenpv** [comment]
Thank you so much for such an extensive answer @crimedude22. 

I do believe that we will "throw away" data when do over-exposure/over-contrast, so in fact the network would become more robust when it learns when the distribution between variables changes (at 255, some pixels cannot go higher, so they are capped, while other pixels can still increase)?

I'm mostly interested in it since I assume my data to sometimes be pretty dark, sometimes not, and I hoped that creating more (artificial) data would increase the robustness. You think this would not hold as it is a linear transformation?

**Comment by kootenpv** [comment]
Okay, I experimented with the transformations, and now have a better understanding. 

Since there is a cap of 255, the transformation for increase cannot be a constant.

E.g. you can divide the values by a constant (e.g. 2) and it will always still be between 0-255.
When you multiply, you cannot multiply by 2, because they would go outside the possible values (clipping is not the right way).

Instead, the formula should be:

Increasing values:

    (255 + frame) / 2

Decreasing values:

    frame / 2

It does not really seem like a purely linear transformation?

But as I understand convolution, it will be pretty much like weights learned for a sliding window *per image*. In this regard, I'm very confused.

MaxPooling will be weird when just simply randomly one image has more intense pixels and will thus be picked up by maxpooling? It seems maxpooling wouldn't really work with images with different intensities?

I really hope that by random augmentations the network would be more robust to the brightness received by a camera, but you're (@crimedude22) saying this probably won't help?
