### ISSUE TITLE
Is there somewhere I can go to see a list of new functionality as it's added?

### ISSUE THREAD

**Issue by simonhughes22** [fchollet/keras#613]
As this is a very actively maintained project, is it possible to have a page that lists newly added features of note? I used to frequently browse the commit history, but it's often hard to determine what's been added just from the check-in comments.

**Comment by fchollet** [comment]
Besides commit logs, I don't think there is any easy way to monitor what's being added. 

One possible way could be to monitor only changes made to the documentation files.

**Comment by wxs** [comment]
I've been scanning the [merged PRs list](https://github.com/fchollet/keras/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged) to get a sense, but that doesn't get me changes that @fchollet makes because he commits directly to master. @fchollet would you consider also using the PR interface for your contributions? That also gives us a place where we can discuss changes if something has broken.
