### ISSUE TITLE
How use Transfer Learning on keras 2.0.2

### ISSUE THREAD

**Issue by SpenserCai** [fchollet/keras#6205]
I want use keras develop a Face Recognition project, I think maybe need Transfer Learning and have some way can use Transfer Learning on keras 2.0.2
thank you

**Comment by asprenger** [comment]
Francois Chollet has written a blog post about transfer learning: [https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html). You may need to do some modifications because of API changes in Keras 2.0. 

The Keras docs have some code examples how to use the models included in the release:
[https://keras.io/applications](https://keras.io/applications)
