### ISSUE TITLE
pretrained_word_embeddings.py source code parameter issue

### ISSUE THREAD

**Issue by shaotongkai** [fchollet/keras#6358]
I am working on the pretrained_word_embeddings.py,
here is the link:  https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py

for this part:

sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
**x = MaxPooling1D(35)(x)**
x = Flatten()(x)
x = Dense(128, activation='relu')(x)

I think the parameter for last MaxPooling1D  (line 136) should be **5** not **35.**

**Comment by nmstoker** [comment]
I'm not in a position to judge but is there any particular reason you think this? Consistency with the entries for 5 elsewhere?

Note, there is a comment in the associated blog post for the code ( [here](https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html) ) which suggests that it's quite possibly intentional, as it says "**# global max pooling**"

**Comment by nmstoker** [comment]
Also, I meant to add: it does seem to work pretty well with 35 (for me at least, running with TF backend on CPU)

If it were broken, I could understand thinking it might be a mistake :smile:
