### ISSUE TITLE
Possible bug in `self._collected_trainable_weights` with effects on GAN training

### ISSUE THREAD

**Issue by yaringal** [fchollet/keras#6405]
Hi,
I was going over the source code to try to understand why changing a model's `Trainable` property failed to update the model parameters after calling `fit()` (even though they would appear in `model.trainable_weights`). I found that the property `self._collected_trainable_weights` is set only once in Model's `compile`:
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L995
and never updates afterwards, even if `self.trainable_weights` changes.
Then, when we call `fit()` for the first time, `_make_train_function` is called, which uses the old (and out of date) `self._collected_trainable_weights`. 
This might be caused from a code addition of `trainable_weights.sort` in `compile`, which makes a local variable instead of setting `self._collected_trainable_weights` to be a reference to  `self.trainable_weights`.
Is this intended behavior or a bug with updating model `Trainable` flag?
Many thanks,
Yarin

**Comment by fchollet** [comment]
This is intended: you always need to `compile` your model if you make any changes to it. A model is considered "finalized" at compile time and any further changes will not be taken into account by the forward/backward functions until `compile` is called again.

The fact that the backward/forward functions are generated one the fly when they are required is actually an implementation detail, due to performance reasons. They were originally generated in `compile` and it is reasonable to still think of them that way.

**Comment by fchollet** [comment]
In short, this is due to the fact that Keras models are graph. There's one point where the graph must be finalized, and that's `compiled`. This will no longer be the case in the imperative version of Keras, where models will be editable at any time.

**Comment by yaringal** [comment]
Thanks!
