### ISSUE TITLE
Keras - Tensor Flow in windows and python 2.7

### ISSUE THREAD

**Issue by michelegentili93** [fchollet/keras#6420]
Is it possible to use keras with tensor flow in windows and python 2.7?

**Comment by bstriner** [comment]
https://www.tensorflow.org/install/install_windows

Keras should work if tensorflow works, so more a tensorflow question than a keras question.

There is a windows package available but only for python 3.5. Building from source for python 2.7 might be possible but a lot of work and it is experimental. It is all because bazel, the google build engine, doesn't fully support windows. Supposedly, when bazel for windows is released everything else should work correctly. On windows, python 2.7, python 3.5 and python 3.6 have to build with 3 different compilers.

So for now you may be able to get it to work but it could take a lot of work. If you just need to do some testing do the docker on windows version which should be easy to do, or just switch to python 3.5.

Personally, tensorflow has a lot of backing from Google but it still isn't as advanced as theano yet, which also works just fine on windows. If you're working with Keras, most of what you do should be tensorflow/theano agnostic.

Cheers
