### ISSUE TITLE
keras backend tensorflow vs pure tensorflow 

### ISSUE THREAD

**Issue by MicBA** [fchollet/keras#6559]
Hi everyone.. 
i have model that i train with keras (backend tensorflow) 
and i'm thinking to use pure tensorflow  for the evaluation part. 
has someone done this before ? 
can someone tell if the performance are better ? by? 
Thanks! 

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Dref360** [comment]
Would be the same since keras is directly using Tensorflow. Keras is using `feed_dict` where a modern Tensorflow model is using [FIFOQueue](https://www.tensorflow.org/api_docs/python/tf/FIFOQueue) to feed the tensors. So you would save a copy using plain `Tensorflow`. But, Keras uses `multiprocessing` to feed the network so it's pretty much the same. (to enable multiprocessing use, `pickle_safe=True` in `evaluate_generator`)
