### ISSUE TITLE
Keras Image Generator MemoryError

### ISSUE THREAD

**Issue by kushia** [fchollet/keras#6651]
Hi everyone,
I have a reasonably big dataset of images, and I'm trying to train the Inception Model on it.
The problem is, when I try to use the Image Generator (To apply random transformations), I get a MemoryError.

This is weird, because, when I fit my model without the generator (So without transformations) I have no problem.
Possibly, the generator has some memory leaks ?
(I train the model with train_on_batch method and yield batch_size from the generator)

If there are no solutions, is there a way to apply transformations to images without the generator ?
(By each images possibly ?)
Thanks!

**Comment by StefanoD** [comment]
I had today a problem, too. I wrote a Unit Test and after the Unit Test I've got a warning about leaking files. It turned out the problem was the PIL library.
Please, try following: Replace this [line](https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py#L320) with
```python
from skimage import io
img = io.imread(path)
```
and report if you still have problems.

**Comment by kushia** [comment]
Thanks for your answer!
I resolved my problem using the random_tranform method of the generator to do it image by image.

I'll try your solution for the next train! Big thanks!
