### ISSUE TITLE
Debugging Keras function

### ISSUE THREAD

**Issue by LN5user** [fchollet/keras#6779]
Hello, I would be most grateful, if you could give me some help.

I wrote a simple function in Keras and I still want to test it whether it works properly or not. How can I do that? 

def cos_sim (inputs):
    i1,i2=inputs
    numerator = K.sum(i1*i2)
    denominator = K.sqrt(K.sum(i1**2)*K.sum(i2**2))
    return numerator/denominator

x = np.array([2,3,1,0])
y = np.array([0,8,6,9])

P.S I expected to get something like “0.595961149897”  but  with “print(model.predict([x,y],verbose=0))” I’ve got  [ 1.  1.  1.  1.]

**Comment by bstriner** [comment]
@LN5user Happy to help but please post a full example that someone can run and use the code formatting option so it will show up correctly.

If I had to guess, check all your axes. Every tensor should be (batch shape, features). If you're writing a custom Lambda function the inputs and outputs should be at least 2d.

From what you wrote, I can't tell if the x and y are supposed to be column or row vectors.

If you're just trying to run some calculations and not train a model, use `K.function` instead of `keras.models.Model`. Models have specific requirements about shapes and whatever.

Cheers

**Comment by LN5user** [comment]
Sorry for being late in answering you. You helped me sooooo much!!! Thank you!!
