### ISSUE TITLE
resnet50.py and AveragePooling2D

### ISSUE THREAD

**Issue by dineshbvadhia** [fchollet/keras#6797]
The code doc says:
```
 `avg` means that global average pooling will be applied to the output of the last convolutional layer, and thus the output of the model will be a 2D tensor.
```
Starting at ln232, the code is:
```
    x = AveragePooling2D((7, 7), name='avg_pool')(x)

    if include_top:
        x = Flatten()(x)
        x = Dense(classes, activation='softmax', name='fc1000')(x)
    else:
        if pooling == 'avg':
            x = GlobalAveragePooling2D()(x)
        elif pooling == 'max':
            x = GlobalMaxPooling2D()(x)
```
AveragePooling2D is applied to the output of the last convolutional layer and then GlobalAveragePooling2D is applied. Is that correct?

I ask because I get the same extracted vector for 'None', 'avg' and 'max'.

**Comment by jvanvugt** [comment]
When the input_shape is (224, 224, 3), the 7x7 `AveragePooling2D` layer will reduce the shape to ` (None, 1, 1, 2048)` .  Flatten will then make it `(None, 2048)` so it can be classified with a Dense layer. However, when you change the input_shape to something sufficiently larger, the output of the `AveragePooling2D` layer will also be larger. For instance, with an input_shape of (512, 512, 3) the output of the `AveragePooling2D` layer will be (None, 2, 2, 2048). It is then useful to apply `GlobalAveragePooling2D` or  `GlobalMaxPooling2D` to reduce the output shape to (None, 2048).

Lastly, when you use imagenet weights and include_top is True, none of it actually matters since the `else` block is not executed.

**Comment by dineshbvadhia** [comment]
For input_shape (224,224,3), with include_top=False the pooling options None|avg|max all return the same extracted feature vector. Why is that?
