### ISSUE TITLE
Extracting feature from the last layer before classification in keras

### ISSUE THREAD

**Issue by paultpa** [fchollet/keras#6802]
I have tried to extract feature in the keras ( with tensorflow and as well as with theano background). But became not successful.

My code is :
`model = Sequential()

model.add(Convolution2D(64, 5, 5, input_shape=(3,img_width, img_height)))
model.add(LeakyReLU(alpha=.01))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Convolution2D(64, 2, 2))
model.add(LeakyReLU(alpha=.01))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))

model.add(Dense(8))

model.add(ActivityRegularization(l2=0.01))
model.add(Activation('relu'))
model.add(Dropout(0.25))

 model.add(Dense(1))
model.add(Activation('sigmoid'))

model.load_weights("weights-improvement-01-0.79.hdf5")

rms =RMSprop( lr=0.0001)
model.compile(loss='binary_crossentropy',
              optimizer=rms,
              metrics=['accuracy'])

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test_data_dir,
    target_size=(img_width, img_height),
    batch_size=16,
    class_mode='binary')

scores = model.evaluate_generator(test_generator, 237)
print("Accuracy = ", scores[1])

get_activations = theano.function([model.layers[0].input], 
model.layers[3].output(train=False), allow_input_downcast=True)

activations = get_activations(test_generator)`

I have used fit_generator for train, validation and test cases.
I am getting accuracy correctly. But after that,I am getting an error when the code is trying to extract feature vector:
` File "test.py", line 96, in <module>
 get_activations = theano.function([model.layers[0].input], 
 model.layers[3].output(train=False), allow_input_downcast=True)
 TypeError: 'TensorVariable' object is not callable`

I have also tried in the tensorflow mode, but the error is coming. 

How can I do it In theano or in the tensorflow mode ( any of them or both). I have used fit_generator in my code for image augmentation.

Please help.

**Comment by xzj6795365** [comment]
https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

the above link maybe could solve your problem

**Comment by t-ae** [comment]
If you only need the output of last sigmoid layer, you can use this.
https://keras.io/models/sequential/#predict_generator

**Comment by sivajyothi82** [comment]
https://keras.io/applications/

Extract features from an arbitrary intermediate layer with VGG19

getting error
input_shapes=[x._keras_shape for x in self.inputs],
AttributeError: 'Tensor' object has no attribute '_keras_shape'

**Comment by sivajyothi82** [comment]
Extract features from an arbitrary intermediate layer with VGG19
from keras.applications.vgg19 import VGG19
from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input
from keras.models import Model
import numpy as np

base_model = VGG19(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('block4_pool').output)

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

block4_pool_features = model.predict(x)

when i was trying to execute the above code in order to extract features from an intermediate layer

I was getting this error stack.
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\deepak\vgg19.py", line 8, in <module>
    model = Model(inputs=base_model.inputs, outputs=base_model.get_layer('block4_pool').output)
  File "C:\Users\deepak\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\deepak\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Users\deepak\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 253, in _init_graph_network
    input_shapes=[x._keras_shape for x in self.inputs],
  File "C:\Users\deepak\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 253, in <listcomp>
    input_shapes=[x._keras_shape for x in self.inputs],
AttributeError: 'Tensor' object has no attribute '_keras_shape'

Its saying Tensor object has no attribute _keras_shape, is it so because of versions or ?

I am using Tensorflow
tensorflow (1.11.0)
Keras (2.2.2)
Keras-Applications (1.0.4)
Keras-Preprocessing (1.0.2)

Some blogs were saying to downgrade tensorflow to 1.0.0
I am confused.
Expecting help from people who already gone through this kind
