### ISSUE TITLE
tf.contrib lookup table issues with Keras Lambda/Custom layers

### ISSUE THREAD

**Issue by viksit** [fchollet/keras#6815]
@fchollet when doing as recommended in https://github.com/tensorflow/tensorflow/issues/8617, I'm running into the following issue,

```
In [88]: keys
Out[88]:
['a',
 'lovely',
 'sentence',
 'this',
 'is',
 'how',
 'are',
 'you',
 'flowers',
 'hello']

In [89]: values
Out[89]: [2, 9, 4, 5, 6, 7, 1, 8, 3, 10]

orig_input = Input(shape=(15,), dtype="string")
lookup_table_op = tf.contrib.lookup.HashTable(
                tf.contrib.lookup.KeyValueTensorInitializer(
                    keys,
                    values
                ),
                default_value=-1
            )
lut_output = Lambda(lookup_table_op.lookup)(orig_input)


TypeError: Signature mismatch. Keys must be dtype <dtype: 'string'>, got <dtype: 'float32'>.
```

Any ideas on what could be happening here?

**Comment by bstriner** [comment]
Sorry not to answer the original question, but it seems odd to be using strings in that way. The preferred way to do embeddings would be an `Embedding` layer and an `Input` layer that is an integer type. Nothing custom or complicated required.

As part of preprocessing, collect the vocabulary and convert all the text to a numpy array of ints. That will make training easier and faster.

Your issue might be related to switching keys and values, but you should probably be doing a different approach unless there is some particular reasoning you haven't given.

Cheers

**Comment by viksit** [comment]
The broader reason is simple - the integer input layer requires a lookup from string, and this table is inherent to a given models training corpus. I want to have an approach where the model encompasses all the details rather than the caller needing to know whcih lookup table to call for a given model.

The embeddings are lower down the stack anyway.

@bstriner

**Comment by viksit** [comment]
Also, that particular lookup table works in a regular tf context but not within a keras lambda function.

**Comment by bstriner** [comment]
Funny solution. So add `output_shape=lambda _x: _x` to the `Lambda` and your code runs. Not sure why exactly it was failing without but that is a problem for another time.

Safest to just use `output_shape` every time you write a `Lambda` because the default almost never seems to get it right.

Still think your best solution is to train with ints, but you could use this for the user-facing model. You should do whatever you can to try to make training as fast as possible. If you have the time, the ideal would be to have one version of the model that trains quickly running on just shuffling numpy integers around, and then load the weights from that model into the user-facing model that has the lookup table or whatever and you actually give out to people. 

Cheers

**Comment by viksit** [comment]
Thanks that was super helpful!

Ah did you mean that the model would train slower because of an extra layer for the lookup?

One thing I've considered is to have a separate step take the new lookup layer and tack it on top of an existing model. It's a bit tricky because I have the layer sandwiched between some complex custom layered.

**Comment by bstriner** [comment]
My main reasons:
* If you have a bunch of data you have to stream on and off of disk and shuffle on the cpu it is going to be a lot faster if it is `uint8` instead of `string`. Remember you are streaming and shuffling a large number of times during training.
* Fewer layers is less stuff to debug. Troubleshooting making a numpy array ahead of time on the CPU is easy to do and debug. Troubleshooting GPU code is notorious so if you can avoid it you should do so.

It is a simpler model just working straight with int inputs and an embedding. Troubleshooting and training that is going to be easier. When you're ready to make it part of a product or something you can worry about a hashtable that embeds everything in one place.

Good luck!

**Comment by viksit** [comment]
Thanks @bstriner.

Quick question - would you have pointers on how to do initializations of that lookup table within the keras context? For instance, in tf, you'd do it as 

```
with tf.Session() as sess:
  table.init.run()
```

**Comment by bstriner** [comment]
You can run the same code in keras. Only difference is that Keras probably already started the session. You can use `keras.backend.get_session()`.

How are you deploying this thing? If you're using a tf hash table to store the vocabulary, have you given any thought as to how you will save the vocabulary? If you want to save it separately you can handle it yourself. You might be able to use a custom Layer with non-trainable weights to get Keras to store the vocabulary in the h5 file, but I haven't tested myself.

**Comment by viksit** [comment]
@bstriner re your first comment, I got it to work. Turns out I was using 

```
with tf.Session() as sess:
  K.set_session(sess)
```
vs  using `K.get_session()`. That worked well.

Good point about (2). I haven't reached that point yet, but I'm now starting to think about it. Are there ways you've seen this done before/examples I could see on how to do this?

Also, in previous models, my first model layers have always expected embeddings, rather than word indexes that then look up embeddings. This works well for unknown words. However, in cases where the embedding layer is part of the model (or in this case, a lookup table is made part of the model itself), how do you deal with unknown words?

As an example like above, the "default" value returned by the lookup is -1, which won't be an entry in the embedding layer.

Cheers

**Comment by bstriner** [comment]
What are you trying to do? Make an android app? A web service? Embedded firmware?

You can't divorce the model from preprocessing. Maybe you downcase and remove punctuation or whatever. Standard is to replace unknowns with something like "__UNK__" then give that symbol a number too.

If you want something custom, you could either write out your own file with weights and vocabulary, or add the vocabulary as a non-trainable weight. The problem there is just making sure you run init and everything at the correct times. You can start by writing a custom layer instead of a lambda. Add the keys and values as non-trainable weights. Then inspect the h5 file and make sure it is including the vocabulary as well.

**Comment by viksit** [comment]
@bstriner it's a web service.

I'm actually thinking of adding an extra input into the embedding layer (maxlen+1) and then just use that as a default lookup.

Re: custom. Looks like I'll have to do it since keras is unable to load a model from json that contains a tf cop. Any pointers on doing such a custom layer?

**Comment by bstriner** [comment]
If it's a web service you have full control and you don't have to worry about the client being able to run the ML. Can really do whatever you want if that's the case. Shouldn't need to worry so much about format and so forth.

Depending on the load and what it is doing: setup something easy but fully featured like a drupal website. Should be good for getting your content, users, etc. all in one place. Requests for running the ML go into a database, which you can do pretty easily from the PHP.

How many users are you expecting? The ideal ML server isn't the same as your web server. You would write a python agent to poll for new requests and respond with the data.

Site then has some JSON to poll the DB and update the DOM after the ML is done.

You don't necessarily need to do the AJAX route. You could just have some pages that show jobs and statuses.

No matter how fast your model, it is going to be slower than people expect page responses. So you will usually end up with some sort of other server or servers to do the processing.

**Comment by viksit** [comment]
Sorry, I meant pointers on implementing a custom layer for a tensorflow operation vs putting it in a lambda layer, such that it can be serialized/deserialized easily. The fixed non trainable weights could  hold indexes, but not sure how they'd hold text.

**Comment by bstriner** [comment]
BTW, regarding unknowns, it looks like the lookup table has a default value you could leverage so you don't need to use a special unknown symbol.

Two options:
* Store vocab as JSON configuration. Your layer has two required constructor arguments, which are the two arrays. Add those same two arrays to your `get_config`. Keras will store those arrays as JSON text in an attribute of the h5 file, not in the file structure itself. When loading, they get passed to the constructor as before.
* Store vocab as H5 data. Your layer constructor arguments are something like `initial_keys` and `initial_values` and default to None. Do not use those in `get_config`. During `build`, load those into tensors with initial values if given and add to non-trainable weights. Keras will save those into the H5 data. When loading, `initial_keys` will be None, so you will not load the values during `build`. Keras will automatically load the values after `build`.  

Both ways you have to make sure you initialize the lookup table after loading. Haven't tested either. First method will definitely work but is inefficient. Second method would be preferred. Keras should save arrays of strings correctly, but it isn't common so I wouldn't be surprised if you find bugs there. First method will have problems if your vocabulary is too big.

Cheers

**Comment by viksit** [comment]
@bstriner So, I made a bunch of progress on method 2, but I think the biggest problem I see is this.

In `topology.py`, `save_weights_to_hdf5_group()` invokes `K.batch_get_value(symbolic_weights)`.

However,

```
In [34]: f.value()
Out[34]: <tf.Tensor 'lookup_layer_1/lookup_layer_1_kw/read:0' shape=(373,) dtype=string>

In [33]: K.batch_get_value(f)
Out[33]:
array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], dtype=object)
```

results in dtype=object for the return value, not string. and fails at the save level,

```
param_dset = g.create_dataset(name, val.shape,
                                          dtype=val.dtype) # dtype is "object"

Object dtype dtype('O') has no native HDF5 equivalent
```

Ideas on how to solve this?

**Comment by bstriner** [comment]
It looks like tensorflow string tensors come out as object arrays in numpy.
You can then `astype` to get string arrays back, but that would be a fix to
Keras. You can ask around on TF forums why that conversion is happening.

A simple fix would be to add an if statement to keras. If the source tensor
is a string, then convert the numpy array to a string.

If you only have 373 vocab items, then storing in configuration isn't all
bad.

**Comment by viksit** [comment]
@bstriner I investigated this, turns out I my model structure, which looks something like,

`Input(i) -> CustomLookup -> Embedding -> [custom layers] -> model1 `
`Input2(model1) ->  ..... model2`

Keras is only storing weights for model2 in the hdf5 file. I don't see any weights from the first model at all. Is this expected?

Re vocab - I actually have 40~100k on average. This was just a test I was running with 300 odd items.

**Comment by bstriner** [comment]
So you're currently seeing your vocabulary in the hdf5 but after you load the tensor doesn't have the value?

Does this happen with both load and load_weights? Is the key/value tensor not loading or is it not loading those into the hashtable?

I'm curious about what you had to change. Please link to your branch if you don't mind.

**Comment by viksit** [comment]
@bstriner I've got it working now after changing some things around. The issue I'm now facing is a weird one where a tf lookup works, but the custom layer it uses fails to do the same lookup.

Let me link you to a gist. [1]

The issue is this: calling the lookup table op directly does a good job of the lookup.
Calling it via the Layer however messes up the lookup.

(In order to reproduce this, you'll need to add this line to `tensorflow_backend.py`,

```
def _convert_string_dtype(dtype):
    """Get the type from a string.

    # Arguments
        dtype: A string representation of a type.

    # Returns:
        The type requested.

    # Raises
        ValueError if `dtype` is not supported
    """
    if dtype == 'float16':
        return tf.float16
    if dtype == 'float32':
        return tf.float32
    elif dtype == 'float64':
        return tf.float64
    elif dtype == 'int16':
        return tf.int16
    elif dtype == 'int32':
        return tf.int32
    elif dtype == 'int64':
        return tf.int64
    elif dtype == 'uint8':
        return tf.int8
    elif dtype == 'uint16':
        return tf.uint16
    elif dtype.lower().index("s") >= 0: # support for string dtypes
        return tf.string
    else:
        raise ValueError('Unsupported dtype:', dtype)


```
Any idea on what may be going on?

[1] https://gist.github.com/viksit/8e6e8de78e208e1ab1ea9ba3732d9e36

**Comment by viksit** [comment]
@fchollet would you have inputs as well? What would be the best way to store a lookup table in a keras layer, but also initialize it from a saved model in the right way? There seems to be no good place today to store a custom init op during a keras layer load.

**Comment by bstriner** [comment]
@viksit I don't think you need to init during architecture loading. You just need the key/value tensors to initialize before the lookup table initializes. Docs say lookup table is mutable until you call init. Make sure you call init on the lookup table after the key/value tensors load. Keras shouldn't be calling init on the lookup table for you, is it? I think it will only init the weights.

You can still try saving the key/values into JSON. Just a few minutes of coding to see how much it uses. Guaranteed to work but large tables in JSON seems like a bad idea. Might run out of memory or something but could be worth a try.

If you're just trying to get something out the door, write some custom code to save and load strings into a separate file.

That `if` should be a `==` like the others instead of a search. Need to write the same thing for the theano and it would be a good PR.

**Comment by viksit** [comment]
@bstriner I think thats where the problem is - aka, finding the place where key/values have been loaded, so i can call the lookup.init(). Is there a hook somewhere where the tensors are guaranteed to be loaded?

I've tried JSON and will fall back to that if this doesn't work!

Yes, I thought about cleaning it up for Theano, and will eventually do a PR.

**Comment by bstriner** [comment]
That's why I was asking about how you deploy it. If this is part of your web server or something, just call load then call init on the lookup table. You don't really need a hook.

You don't need to compile your model if you're just using it for predictions in your application. If someone calls `load_model` without compiling, it will create the model and then load the weights. No place in there for a hook after loading weights.

If anything, you could hook into something like make predict and make train function. You would need a custom model class that overrides those two functions and calls init before calling the super implementations. Also need a flag so you only init once.

```python
def _make_train_function(self):
  if not self.lookup_initialized:
    # do something to init the lookup
    self.lookup_initialized=True
   super(MyClass, self)._make_train_function()
```

Make sure your lookup is an attribute of the layer and you give the layer a name so you can easily find the layer and the lookup after you load the model.

Overall, seems like a pain to make a hook for calling init whenever `load_model` is called. If you have the flexibility, just call init after `load_model`.

**Comment by spate141** [comment]
Hi @bstriner, @viksit: I know this is pretty old issue thread, but seems like I'm trying to solve similar type of issue with Keras and Lambda layer with LookupTables. Would you mind looking into this SO thread? I could really use any useful pointers with this. Thanks!
https://stackoverflow.com/questions/57948726/tensorflow-failedpreconditionerror-table-not-initialized-in-keras-model-laye

**Comment by spate141** [comment]
Well, looks like this was solved with using `K.get_session().run(tf.tables_initializer(name='init_all_tables'))` before model.predict() and outside the lambda function!
