### ISSUE TITLE
Optimizer state

### ISSUE THREAD

**Issue by kevinthesun** [fchollet/keras#6978]
Does Keras optimizer store state for resuming training after saving/loading model? It seems Optimizer class has no state.

Thanks!

**Comment by TParcollet** [comment]
Do we have an answer about this problem ? Does loading a model restart with the right optimizers values ?

**Comment by cainmagi** [comment]
Yes. Both the optimizer configurations and its corresponding tunable parameters would be stored, if you call `save_model` (or `model.save`) and set `include_optimizer=True`. The configurations would be stored by JSON format and the parameters would be saved by HDF5 format, just like what we do when saving the whole model.
The same things also happen when using `ModelCheckpoint`, if you set `save_weights_only=False`, because in that case, the `ModelCheckpoint` would call `model.save` on the end of the epoch.
