### ISSUE TITLE
tensorboard callback doesn't work when using combined models into one

### ISSUE THREAD

**Issue by n1kt0** [fchollet/keras#6988]
tensorboard callback doesn't work when using combined models e.g. using a wide and a deep model combined in a third one.

it says:
`ValueError: No variables to save`

**Comment by bfishman** [comment]
I have the same issue, `ValueError: No variables to save` when using the model from https://github.com/ShobhitLamba/LSTM-FCN

**Comment by bfishman** [comment]
@fchollet  not sure of the proper reporting guidelines - since this issue was auto-closed, should I post a new issue instead of replying here?

**Comment by MCMcCallum** [comment]
Same problem here also

**Comment by teglaservin** [comment]
I've come across this issue and it was occurring because my combined models were cascaded, thus the Tensorboard callback has a hard time finding given layers (you might be able to give it a proper input like "model2/layer3" but my attempts at that have failed, I'm quite new at this).

Regardless this solution was an obvious fix in hindsight as I just eliminated the cascaded nature, so all layers are visible from the top, and so the Tensorboard callback can reach them, and finds "Variables to save". https://github.com/raghakot/keras-vis/issues/37#issuecomment-396919498
