### ISSUE TITLE
What is the difference between 'activation' and 'recurrent_activation' parameters in the LSTM?

### ISSUE THREAD

**Issue by aghasemi** [fchollet/keras#7319]
Any information or references are welcome

**Comment by dylanrandle** [comment]
This is not an issue, please ask for help in the slack channel: https://kerasteam.slack.com/messages/C0UDS3N1E/convo/C0QKGCQFM-1499893484.594570/

**Comment by antonimmo** [comment]
I believe this could be flagged as a "documentation issue" (IMO, the documentation is an issue by itself), as it doesn't have any reference or explanation on their effect. Just for comparison, Optimizers has some links to articles which (hopefully) explain what each of these parameters do, or have at least some explanation.

BTW, the Slack channel you shared needs a @stanford.edu, @nvidia.com, @holbertonschool.com, @google.com, @microsoft.com, @nyu.edu or @xbrain.io email in order to log in.

**Comment by Danielhiversen** [comment]
You request an invite here: https://keras-slack-autojoin.herokuapp.com/ if you do not have such an email adress
