### ISSUE TITLE
can't save model

### ISSUE THREAD

**Issue by Wario7** [fchollet/keras#7446]
Hello,

I am trying to save a sequential model, but the console is returning "module 'h5py' has no attribute 'File'"

```
from keras.models import load_model, Sequential

model = Sequential()
model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model
model = load_model('my_model.h5')
```
I've checked that keras is up to date. Is anyone else facing this issue? thanks for your time

**Comment by dsouzadaniel** [comment]
This could be because the h5 only saves the weights. You need to save the model architecture as well. You can find code on the keras documentation.

**Comment by inexxt** [comment]
No, model.save() should save the whole model architecture - as opposed to model.save_weights(), which can be used to save the only the weights.

When I try to recreate the bug, I'm getting `IndexError: list index out of range`, because save method expects the model to have at least one layer (the code relevant here:
```
   1192     def get_config(self):
-> 1193         if isinstance(self.layers[0], legacy_layers.Merge):
   1194             return self.legacy_get_config()
```
