### ISSUE TITLE
map the embedding vector back.

### ISSUE THREAD

**Issue by xcszbdnl** [fchollet/keras#7519]
I want to map the embedding vector back by using like this: `x = v * A.T`. `v` is the embedding vector and `A` is the embedding matrix.  How could I do it in keras?  like this?

    embedding_dim = 10
    voc_size = 5
    seq_length = 10
    x = Input(shape=(seq_length))
    embedding_layer = Embedding(voc_size, embedding_dim)
    x = embedding_layer(x)
    x = TimeDistributed(Dense(voc_size, ...))     # weights may be embedding_layer.embeddings.T

**Comment by mahnerak** [comment]
AFAIK, Keras doesn't support any weight sharing between layers. Only layer sharing inside model is possible, so what you want to do is hardly to be implemented right using Keras.
Anyways, you can define model without weight sharing and then change last layer weight from outside. The problem is that you'll have trouble using some Keras Model methods, such as save, count_weights, etc...
