### ISSUE TITLE
How about a doc for keras model in general? e.g. model.summary()

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#8105]
https://keras.io/models/about-keras-models/

This page seems manually created rather than collected from the source file. Maybe we could add a bit more on this page? E.g., 
```
print_summary(model, line_length=None, positions=None, print_fn=print):
```
The arguments can be explained along with summary().

**Comment by charlesreid1** [comment]
The `print_summary()` method is part of the Keras utilities (see [layer_utils.py](https://github.com/fchollet/keras/blob/master/keras/utils/layer_utils.py)), so it would be expected to be documented on the [utils documentation page](https://keras.io/utils/) page, and not the Keras models page.

However, it is not included on that page because it is not imported in the [utils/__init__.py](https://github.com/fchollet/keras/blob/master/keras/utils/__init__.py). This only imports select utilities. These are the ones that are documented on the [utils documentation page](https://keras.io/utils/) (see, for example, [convert_all_kernels_in_model()](https://keras.io/utils/#convert_all_kernels_in_model) on the documentation page, which is imported on [line 20 of utils/__init__.py](https://github.com/fchollet/keras/blob/master/keras/utils/__init__.py#L20)).

If it were, the arguments would be extracted automatically from the Python docstrings, as they are for `convert_all_kernels_in_model()`.

**Comment by charlesreid1** [comment]
This means your question is *really* why `print_summary()` is not included in `utils/__init__.py` - and I don't know the answer to that question.

**Comment by keunwoochoi** [comment]
`print_summary()` is, yes, layer utils, but I guess what people use more frequently is `model.summary()` and that's what I wanted to say.

**Comment by charlesreid1** [comment]
the `model.summary()` method is defined in `keras/engine/topology.py`, [line 2689](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L2689), also not included in the documentation. The `model.summary()` documentation is included in [about-keras-models.md](https://github.com/fchollet/keras/blob/master/docs/templates/models/about-keras-models.md) in the documentation, which is _not_ automatically generated and does not include any information about its parameters or arguments.

**Comment by keunwoochoi** [comment]
Exactly.
