### ISSUE TITLE
Use tf.eye and T.eye

### ISSUE THREAD

**Issue by artemyk** [fchollet/keras#8232]
Right now the backend code for creating an identity matrix creates a numpy identity matrix using `np.eye`, and then converts it to a tensor.  However, both tensorflow and theano provide `tf.eye` and `T.eye` methods specifically for this purpose.  Unlike `np.eye`, these allow the identity matrix to have a variable size.  Could the backend code be updated to use the native functions?

**Comment by ozabluda** [comment]
That would be inconsistent with K.zeros() and K.ones(), which are themselves inconsistent with zeros_like() and ones_like(). This seems to be by design, see  https://github.com/fchollet/keras/pull/3123.

**Comment by ozabluda** [comment]
Noticed that since https://github.com/fchollet/keras/pull/3123, tf.zeros() and tf.ones() were changed in TF backend (but not in Theano or CNTK). For this reason, I created PR above in TF only.

**Comment by ozabluda** [comment]
With TF backend, `K.eye()` used to produce a Keras variable and still does. But now (consistent with `K.zeros() and `K.ones()`) this Keras variable is constructed from `tf.Tensor` instead of `np.ndarray`. Theano and CNTK backends still construct `K.zeros(), K.ones(), K,eye()` Keras variables from `np.ndarray`. It's internally consistent, that's why I didn't change it.

**Comment by artemyk** [comment]
I see. Thanks.
