### ISSUE TITLE
Possibilties to create add low level (gpu kernel) layers ?

### ISSUE THREAD

**Issue by juliandewit** [fchollet/keras#829]
Hello,
After first rolling my own neural net. Then, hopping on the CxxNet bandwagon but being disappointed that they abondoned it, I'm looking at keras right now.

I want to extend the network with my own layers and ideas. For instance fractional max-pooling.
However.. I do not see an easy-fast implementation in theano. (partly due to my inexperience with it)

If I would make a c-based kernel.. Have you any idea how easy it would be to make it work with Keras/theano ? Are there any pointers ?

**Comment by nouiz** [comment]
(I'm a Theano dev, so I'm only going to talk about that part)

If you want c code to implement a new op (cpu or gpu), then you need to
create a new class that inherit from Op. This is documented here:

http://deeplearning.net/software/theano/tutorial/extending_theano.html

Do you want a GPU version? This isn't much documented.

What is fractional max-pooling? Maybe we can find a way to implement it
otherwise. There is images2neighbs that could be useful for that. It work
on the GPU:

http://www.deeplearning.net/software/theano/library/sandbox/neighbours.html#theano.sandbox.neighbours.images2neibs

**Comment by LetterRip** [comment]
Here is fractional max pooling

https://arxiv.org/abs/1412.6071

**Comment by nouiz** [comment]
We are in the process of deprecating the current GPU back-end. We are in
the process to document how to do new op in Theano in the new back-end:

https://github.com/Theano/Theano/pull/4584

You can also don't do any c code except the kernel and use pycuda to
compile it:

http://deeplearning.net/software/theano/tutorial/gpu_data_convert.html?highlight=pycuda

If you have questions, don't hesitate.

**Comment by MartinThoma** [comment]
See also: [Which deep learning framework(s) support fractional strides?](https://www.reddit.com/r/MachineLearning/comments/4bbod7/which_deep_learning_frameworks_support_fractional/)
