### ISSUE TITLE
Missing relu in Theano

### ISSUE THREAD

**Issue by vierja** [fchollet/keras#833]
In Keras 0.2.0, the `relu` activation is changed to use the `relu` function in Theano nnet module.
The problem is that there isn't a Theano Pypi release with this change.

**Comment by EderSantana** [comment]
That is true, it should be noted that people should use the following Theano 0.8 that was not released yet:

`git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git`

**Comment by kohpangwei** [comment]
Unfortunately, upgrading to the latest version of Theano breaks training on simple cases that used to work, e.g., https://github.com/fchollet/keras/issues/828. Do you know what might be the issue there? I agree that upgrading to the latest version of Theano would be nice – otherwise concatenate can't be used.

**Comment by fchollet** [comment]
I added a warning in the README and the docs.
