### ISSUE TITLE
Dimension after merge layer.

### ISSUE THREAD

**Issue by wtlim** [fchollet/keras#8444]
I'm using merge layer to solve some problem.
But after merge layer, it seems to be merged only two tensors each.
Am I right? 
Actually, I want to merge whole input tensors.

For example, build a model like
```
AA = Conv2D(32, (3, 3), activation='relu')
BB = Conv2D(32, (3, 3), activation='relu')
merged = merge([AA, BB], mode='mul')
```

I got merge layer,
```
input: (None, 32, 64, 64), (None, 32, 64, 64)
output: (None, 32, 64, 64)
```

What I want is
`output: (None, 1, 64, 64)
`

Could you give me some advice? Thanks in advance!

**Comment by roya0045** [comment]
I'll try to explain so that you understand why and how to fix this. Currently your "image" tensor is 64 by 64, the this is that you have 32 nodes that each produce a distinct 64 by 64 image. Bot output are 32 different tensor of a 64 by 64 image. Now how do you want to fix this? One way would be to have 1 unit of conv2d on each side instead of 32 or to add another layer that would "combine" all those 64 by 64 frames together. You would lose a lot of information that way. You could also simply put another layer after the merge that would have only 1 node, if this is your output node and you would only want a single 64 by 64 image as the output.

**Comment by wtlim** [comment]
@roya0045 
Thank you, Alex.
You mean like this?

```
AA = Conv2D(32, (3, 3), activation='relu')
BB = Conv2D(32, (3, 3), activation='relu')
merged = merge([AA, BB], mode='mul')
merged = Conv2D(1, (3, 3), activation='relu')(merged)
```

It could be one way, but what I really want is to multiply all 64x64 images from 32 x 2(AA, BB) different nodes.

**Comment by roya0045** [comment]
Yes, that should give you a single 64 by 64 image IF your stride is 1 and you have a padding of size 1.
 By default the stride is (1,1) but the padding is 'valid' this mean that for each convolutions pass the image would be smaller by 2 in each row and column. If you want to preserve the dimensions of the input use padding="same" in your convolution layer.
 i.e.:
```python
AA = Conv2D(32, (3, 3), activation='relu',padding="same")(input)
BB = Conv2D(32, (3, 3), activation='relu',padding="same")(input)
merged = merge([AA, BB], mode='mul')
merged = Conv2D(1, (3, 3), activation='relu',padding="same")(merged)
```

But be careful, if you multiply everything you will end up with a greatly polarized output because the values will either get stuck to 0 as (x1*x2*x3*x4*0)=0 or they will get capped at 255.
