### ISSUE TITLE
lstm_text_generation.py training speed

### ISSUE THREAD

**Issue by tadas-subonis** [fchollet/keras#855]
Hi all,

I've wanted to double check my setup with you guys for the example problem "lstm_text_generation.py".

I am currently training it on the GPU, and it takes 30min per one iteration. That's a long time.

What numbers are you getting? I am worried that I've configured something wrong and that's why it is so slow.

My machine: Geforce 650M, 12GB RAM, i7-3612QM@2.1GHz

**Comment by joshburkart** [comment]
I think I was getting ~600s per iteration on my Macbook Pro with somethingorother built-in GPU.

**Comment by tadas-subonis** [comment]
Thanks. It seems to be on the same magnitude :-). Could anyone that has a
high-end GPU (like 980 or Titan) post their times? I would be interested to
see what kind of speed-up it would be possible to get with the right
equipment.

On Tue, Oct 20, 2015 at 7:56 AM, Josh Burkart <notifications@github.com>
wrote:

> I think I was getting ~600s per iteration on my Macbook Pro with
> somethingorother built-in GPU.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/855#issuecomment-149433277>.
>



-- 

Kind Regards,
Tadas Šubonis

**Comment by nouiz** [comment]
Be sure to use Theano dev version. There is big speed up merged since the
last release. We keep the dev version pretty stable:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by tadas-subonis** [comment]
@nouiz Thanks. It reduced training time by epoc by 30% to 1100s . 

I would be still eager to hear what kind of performance people get with Titan or 980 GTX and then we can close this issue.

**Comment by gw0** [comment]
On GeForce GTX 980 Ti using Keras 1.0.4 and Tensorflow 0.8.0 ([Docker image](https://hub.docker.com/r/gw000/keras/) `gw000/keras:1.0.4-py2-tf-gpu`) I get 185 sec/iteration.

**Comment by nouiz** [comment]
For theano, to get the best speed of convolution for many iteration, (for
slower for the first bach), you should use those Theano flags:

dnn.conv.algo_fwd=time_once,dnn.conv.algo_bwd_filter=time_once,
dnn.conv.algo_bwd_data=time_once

see for explanation:
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

and lib.cnmem=0.8

**Comment by gw0** [comment]
Ok, it seems everyone wants some benchmarks...

(All examples are using Docker images from <https://github.com/gw0/docker-keras> on Intel Core i7 (3.2GHz 8 threads) with GigaByte GTX 980 Ti (1.1GHz 2816 cores) using Python 2.8 and Keras 1.0.4).

**On GPU** differences are neglectable:

- Tensorflow 0.8.0 on GPU (default):

```bash
$ docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') -v ~/keras/examples:/srv/ gw000/keras:1.0.4-py2-tf-gpu python /srv/lstm_text_generation.py
corpus length: 600901
total chars: 59
nb sequences: 200287
...
Iteration 1
Epoch 1/1
200287/200287 [==============================] - 184s - loss: 2.2505
...
Iteration 2
Epoch 1/1
200287/200287 [==============================] - 183s - loss: 1.7110
```

- Theano 0.8.2 on GPU (default `device=gpu,floatX=float32,nvcc.fastmath=True,lib.cnmem=1`):

```bash
$ docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') -v /root/keras/examples:/srv/ gw000/keras:1.0.4-py2-th-gpu python /srv/lstm_text_generation.py
corpus length: 600901
total chars: 59
nb sequences: 200287
...
Iteration 1
Epoch 1/1
200287/200287 [==============================] - 189s - loss: 2.2993
...
Iteration 2
Epoch 1/1
200287/200287 [==============================] - 191s - loss: 1.7289
```

- Theano 0.8.2 on GPU (with additional tweaks from [@nouiz](https://github.com/fchollet/keras/issues/855#issuecomment-227179812)):

```bash
$ docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') -e THEANO_FLAGS="device=gpu,floatX=float32,nvcc.fastmath=True,lib.cnmem=1,dnn.conv.algo_fwd=time_once,dnn.conv.algo_bwd_filter=time_once,dnn.conv.algo_bwd_data=time_once" -v /root/keras/examples:/srv/ gw000/keras:1.0.4-py2-th-gpu python /srv/lstm_text_generation.py
corpus length: 600901
total chars: 59
nb sequences: 200287
...
Iteration 1
Epoch 1/1
200287/200287 [==============================] - 190s - loss: 2.2964
...
Iteration 2
Epoch 1/1
200287/200287 [==============================] - 191s - loss: 1.7186
```

**On CPU** only to get an approximate feeling (estimated times left after ~3% of epoch):

- Tensorflow 0.8.0 on CPU (default):

```
  6016/200287 [..............................] - ETA: 2425s - loss: 3.1646
```

- Theano 0.8.2 on CPU (default `device=cpu,floatX=float32`):

```
  6016/200287 [..............................] - ETA: 4595s - loss: 3.1935
```

- Theano 0.8.2 on CPU (with additional tweaks from [@nouiz](https://github.com/fchollet/keras/issues/855#issuecomment-227179812)):

```
  8832/200287 [>.............................] - ETA: 4552s - loss: 3.1437
```

As expected tweaks from @nouiz do not have any effect, because only LSTM layers are used in this example (`lstm_text_generation.py`), no convolution or pooling. Speed-up when using a GPU is 13x-23x.

**Comment by fchollet** [comment]
(for anyone trying to reproduce this now, please note that the example code has been modified some time afterwards to use a smaller model and thus run faster).

**Comment by zaminjoz** [comment]
Clean up your Mac computer before it's too late...

I don't need to tell you Mac computers are expensive, because we both know that!

So I also don't need to tell you either that it's in your interest to keep your Mac computer tidy and clean. A trip to the Apple repair store can be costly and stressful. Believe me, I've been there.

So what can you do?

You can detox your Mac using Detox My Mac! Detox My Mac is the #1 Mac cleaning application out there right now and every second is saving users hours of waiting and hassle with their Mac computer.

Download Now >> http://adfoc.us/37141461107244

Not only will Detox My Mac remove unwanted and unnecessary files such as cache files, logs and application leftovers, it will greatly improve your Mac's performance, speed and responsiveness.

It's like a Mac upgrade in seconds!

The best part of Detox My Mac is it does not affect a single application or setting. The only difference you will notice is a faster and cleaner Mac, with a ton of extra disk space.

Scanning over 30 advanced elements in your Mac, I can tell you now you won't find a more comprehensive and safer Mac cleaner out there.

Priced at $37.95 - Personally I think that's a drop in the ocean compared to the extensive cost of a Mac repair or upgrade. What price would you put on your Mac's health and speed?

My advice: Check out their website and see for yourself Detox My Mac in action!

Watch Video >> http://adfoc.us/37141461107244

Speak soon,

PS. To put your mind completely at rest, you can grab a copy of Detox My Mac with zero risk through their rock-solid 60-day money back guarantee! Now that's pretty darn good if you ask me!

Download Now >> http://adfoc.us/37141461107244
