### ISSUE TITLE
Graph bug: "AttributeError: 'Dense' object has no attribute 'initial_weights'"

### ISSUE THREAD

**Issue by sergeyf** [fchollet/keras#946]
The following works just fine:

```
d_in = 10
d_out = 55
weights = np.random.random((d_in,d_out))
model = Sequential()
D = Dense(input_dim=d_in, output_dim=d_out, weights=[weights, np.zeros(d_out)])
model.add(D)
```

But trying the same thing with `Graph` results in an error:

```
model = Graph()
model.add_input(name='input',input_shape=(d_in,))
D = Dense(input_dim=d_in, output_dim=d_out, weights=[weights, np.zeros(d_out)])
model.add_node(D,name='dense', input='input')
```

Here's the full trace:

```
Traceback (most recent call last):

  File "<ipython-input-40-c6155a32b3d8>", line 12, in <module>
    model.add_node(D,name='dense', input='input')

  File "build\bdist.win-amd64\egg\keras\layers\containers.py", line 254, in add_node
    layer.set_previous(self.inputs[input])

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 39, in set_previous
    self.build()

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 645, in build
    if self.initial_weights is not None:

AttributeError: 'Dense' object has no attribute 'initial_weights'
```

**Comment by mmmikael** [comment]
The is a corner case that calls ```Dense.build()``` twice: once by ```Layer.set_input_shape``` and once by ```Layer.set_previous```. The code that set the weights is not robust to two calls as the variable ```initial_weights``` is deleted during [the first call](https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L771-L773). 

In your example, you can simply omit the argument ```input_dim``` in the ```Dense``` constructor since it can be inferred automatically. However a more general fix could be to check if ```Dense.inital_weights``` is defined in ```Dense.build()```. Something like:
```python
if hasattr(self, 'initial_weights') and self.initial_weights is not None:
    self.set_weights(self.initial_weights)
    del self.initial_weights
```

```

**Comment by sergeyf** [comment]
Ah thank you for the clarification!
