### ISSUE TITLE
Implementation of Dynamic Memory Networks

### ISSUE THREAD

**Issue by nerdylinius** [fchollet/keras#993]
I am confused for weeks how can I implement Dynamic Memory Networks (from the paper "Ask Me Anything: Dynamic Memory Networks for Natural Language Processing", a really excellent model) with Keras. Could anyone give me some hints or show me a simple implementation? Also, thank you guys for the awesome work to this software.

**Comment by dbonadiman** [comment]
I'm trying to work on these systems too. From what i understood the problem is that Keras at the moment despite is simple and easy for standard model can be messy to implement more complex architectures.

In particular attention models are fairly simple as a general implementation but using this library they require many tricks to be implemented properly (there was an issue some day ago that i cannot find showing one implementation). For an attention model you should focus on Graph based model. I recommend you to implement first "simpler" models like the ones in http://arxiv.org/pdf/1506.03340v2.pdf .

Once you did that you need some kind of recursive models that are under development in the Keras ecosystem.

In general by the way you could simplify the dynamic memory network to work on fixed size inputs (padded) and a fixed number of input sentences in this way you should be able to implement them (probably you cast them back to memory network)

As an advice if it is only for practice at the moment i recommend simpler model. If you need to implement dynamic memory networks you should think of implementing some layer and function by yourself and work with plain theano to achieve that.

**Comment by nerdylinius** [comment]
@dbonadiman Thank you a lot. I'll have a try

**Comment by EderSantana** [comment]
as @dbonadiman it is hard implement things like that with Keras high level API. It will be possible, I hope with the Recurrent container that I was working on (but had to stop to write my thesis proposal). Nevertheless, you can always write ad hoc layers like the Neural Turing Machine in here https://github.com/fchollet/keras/pull/990

That one does uses attention and stuff... you just have to write it in Theano, copy pasting from Keras when necessary.

**Comment by pasky** [comment]
In-sentence attention is perfectly possible, see for example https://github.com/brmson/dataset-sts/blob/master/examples/anssel_attn.py

The tricky part is trans-sentence attention - essentially, when we don't have a single time series to consider, but a 1D tensor of time series.  I don't know yet how to do that in Keras at all; see also #1399 late comments - we should figure this out, then fix the MemN2N Keras example to do it.

**Comment by cerisara** [comment]
@pasky Your link is broken; I'm eager to look at the code you mention for attention models; could you please give some updated link, if there is any ? Thanks a lot !

**Comment by pasky** [comment]
The original, free-standing code is https://github.com/brmson/dataset-sts/blob/b8a3722c9f6b0374a3d2d418c24fb984548326ee/examples/anssel_attn.py while the current code https://github.com/brmson/dataset-sts/blob/master/models/attn1511.py uses more abstraction; pick your poison.

**Comment by cerisara** [comment]
Thanks a lot !
Christophe

2016-03-05 11:58 GMT+01:00 Petr Baudis <notifications@github.com>:
